---
sidebar: sidebar 
permalink: br-limitations-vmware.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, vmware, vcenter 
summary: 'Le service de BlueXP backup and recovery doit d"abord détecter les données pour que vous puissiez l"utiliser. Lors de cette détection, BlueXP backup and recovery analyse tous les volumes et fichiers des environnements de travail de votre organisation.' 
---
= Limitations connues de la BlueXP backup and recovery pour les charges de travail VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites.

Les actions suivantes ne sont pas prises en charge dans la version Preview des charges de travail VMware dans la BlueXP backup and recovery:

* Monter
* Démonter
* Restaurer vers un autre emplacement
* Restaurer VMDK
* Attacher VMDK
* Détacher VMDK
* Prise en charge de vVol
* Prise en charge NVMe
* Intégration de courrier électronique
* Modifier la politique
* Modifier le groupe de protection
* Prise en charge du contrôle d'accès basé sur les rôles (RBAC)

