---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: bluexp, backup, back up, restore, recovery, aws, azure 
summary: Avant d’utiliser la BlueXP backup and recovery, effectuez quelques étapes pour configurer les destinations de sauvegarde. 
---
= Configurez les destinations de sauvegarde avant d'utiliser la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Avant d’utiliser la BlueXP backup and recovery, effectuez quelques étapes pour configurer les destinations de sauvegarde.

Avant de commencer, vérifiez link:concept-start-prereq.html["prérequis"]que votre environnement est prêt.



== Préparer la destination de sauvegarde

Préparez une ou plusieurs des destinations de sauvegarde suivantes :

* StorageGRID NetApp .
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Découvrez StorageGRID"^].

+
Se référer à  https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentation StorageGRID"^] pour plus de détails sur StorageGRID.

* Services Web Amazon. Reportez-vous à la https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["Documentation Amazon S3"^].
+
Procédez comme suit pour préparer AWS comme destination de sauvegarde :

+
** Configuration d'un compte dans AWS.
** Configurez les autorisations S3 dans AWS, répertoriées dans la section suivante.
** Pour plus d'informations sur la gestion du stockage AWS dans BlueXP , reportez-vous à https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Gestion de vos compartiments Amazon S3"^]la section .




* Microsoft Azure.
+
** Reportez-vous à la https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html["Documentation Azure NetApp Files"^].
** Configuration d'un compte dans Azure.
** Configure  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Autorisations Azure"^] dans Azure.
** Pour plus de détails sur la gestion de votre stockage Azure dans BlueXP, reportez-vous à  https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Gérez vos comptes de stockage Azure"^] .




Après avoir configuré les options de la destination de sauvegarde, vous la configurerez ultérieurement comme destination de sauvegarde dans le service de BlueXP backup and recovery . Pour plus d'informations sur la configuration de la destination de sauvegarde dans le BlueXP backup and recovery, consultez la section link:br-start-discover-backup-targets.html["Découvrir les cibles de sauvegarde"] .



== Configurez les autorisations S3

Vous devrez configurer deux ensembles d’autorisations AWS S3 :

* Autorisations permettant au connecteur de créer et de gérer le compartiment S3.
* Autorisations relatives au cluster ONTAP sur site afin de pouvoir lire et écrire les données dans le compartiment S3.


.Étapes
. Assurez-vous que le connecteur dispose des autorisations requises. Pour plus de détails, voir https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["Autorisations des stratégies BlueXP "].
+

NOTE: Lorsque vous créez des sauvegardes dans des régions AWS Chine, vous devez modifier le nom de ressource AWS « arn » sous toutes les sections _Resource_ des stratégies IAM de « aws » à « aws-cn », par exemple `arn:aws-cn:s3:::netapp-backup-*`.

. Lorsque vous activez le service, l'assistant de sauvegarde vous invite à entrer une clé d'accès et une clé secrète. Ces identifiants sont ensuite transmis au cluster ONTAP afin que ONTAP puisse sauvegarder et restaurer les données dans le compartiment S3. Pour cela, vous devez créer un utilisateur IAM avec les autorisations suivantes.
+
Reportez-vous à la https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Documentation AWS : création d'un rôle pour déléguer des autorisations à un utilisateur IAM"^].

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

