---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, bluexp backup and recovery frequently asked questions 
summary: Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question. 
---
= Questions fréquemment posées sur la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question.



== Déploiement

*Avez-vous besoin d'une licence pour utiliser la version préliminaire de sauvegarde et de récupération BlueXP ?*

Vous pouvez utiliser les types de licence suivants :

* Inscrivez-vous pour bénéficier d'un essai gratuit de 30 jours.


Comment activer la BlueXP backup and recovery? Aucune activation n'est requise . L'option de sauvegarde et de récupération est automatiquement activée dans le menu de navigation gauche de BlueXP .

Pour ce faire, vous devez vous inscrire ou contacter votre ingénieur commercial NetApp pour essayer ce service. Ensuite, lorsque vous utilisez le connecteur BlueXP, il inclut les fonctionnalités appropriées pour le service.

Pour commencer à utiliser la BlueXP backup and recovery, cliquez sur « Commencer à découvrir les charges de travail » à partir de sa page d'accueil initiale.

* La BlueXP backup and recovery sont-elles disponibles en modes standard, restreint et privé ?* À l'heure actuelle, la version Preview de la BlueXP backup and recovery est disponible uniquement en mode standard. Restez à l'affût de tout.

Pour obtenir une explication sur ces modes dans tous les services BlueXP , reportez-vous àla section https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modes de déploiement BlueXP"^].



== L'accès

*Quelle est l'URL de BlueXP backup and recovery ?* Pour l'URL, dans un navigateur, entrez : https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/backup-and-recovery"^] pour accéder à la console BlueXP .

*Comment les autorisations d'accès sont-elles gérées?* Seuls les administrateurs de l'entreprise ont la possibilité de lancer le service et de découvrir les workloads (car cela implique de s'engager à utiliser une ressource). Les interactions suivantes peuvent être effectuées par n'importe quel rôle.

*Quelle est la meilleure résolution de périphérique ?* La résolution de l'appareil recommandée pour la BlueXP backup and recovery est de 1920 x 1080 ou supérieure.

*Quel navigateur dois-je utiliser ?* N'importe quel navigateur moderne fonctionnera.



== Interaction avec d'autres services

* La BlueXP backup and recovery sont-elles conscientes des paramètres de protection définis dans NetApp ONTAP?* Oui, la BlueXP backup and recovery découvrent les planifications de snapshots définies dans ONTAP.

*Si vous définissez une politique à l'aide de la BlueXP backup and recovery, devez-vous effectuer les modifications futures uniquement dans ce service ?* Nous vous recommandons d'effectuer les modifications de politique à partir du service de BlueXP backup and recovery .



== Charges de travail

*Qu'est-ce qui constitue une charge de travail?* Une charge de travail est une application de la version Preview 2025. Une charge de travail inclut tous les volumes utilisés par une seule instance d'application. Par exemple, une instance de base de données Microsoft SQL Server déployée sur mssql3.host.com peut avoir respectivement les volumes vol1 et vol2 pour ses données et ses journaux. Ensemble, ces volumes constituent la charge de travail de cette instance spécifique de la base de données.

*Quelles charges de travail la BlueXP backup and recovery prennent-elles en charge ?*

Pour la version Preview 2025, la BlueXP backup and recovery peuvent identifier les charges de travail suivantes : applications Microsoft SQL Server.

*Qu'est-ce qu'une charge de travail « protégée »?* Dans la BlueXP backup and recovery, une charge de travail affiche un statut « protégé » lorsqu’une stratégie de détection principale est activée.

*Qu'est-ce qu'une charge de travail « à risque »?* Si aucune règle de détection primaire n'est activée pour une charge de travail, elle est « risquée » même si une règle de sauvegarde et de snapshot est activée.

*Nouvelle charge de travail ajoutée, mais n'apparaît pas encore* Si vous avez ajouté une nouvelle charge de travail à votre environnement, relancez la découverte et appliquez des politiques de protection pour protéger cette nouvelle ressource.



== Règles de protection

* La BlueXP backup and recovery sont-elles conscientes des paramètres de protection définis dans NetApp ONTAP?*

Oui, la BlueXP backup and recovery découvrent les planifications de snapshots définies dans ONTAP et si ARP et FPolicy sont activés dans une charge de travail découverte. Les informations que vous voyez initialement dans le tableau de bord sont agrégées à partir d'autres solutions et produits NetApp.

* La BlueXP backup and recovery sont-elles conscientes des politiques déjà définies dans SnapCenter?*

Oui, si vous avez des charges de travail gérées dans SnapCenter, les politiques gérées par ces produits sont intégrées à la BlueXP backup and recovery.

*Pouvez-vous modifier les politiques transférées depuis SnapCenter?*

Oui, vous pouvez modifier les politiques gérées par SnapCenter dans la BlueXP backup and recovery.

*Si des politiques existent à partir d' ONTAP (déjà activées dans System Manager telles que ARP, FPolicy et les instantanés), celles-ci sont-elles modifiées dans la BlueXP backup and recovery?*

Non. La BlueXP backup and recovery ne modifient aucune politique de détection existante (paramètres ARP, FPolicy) d' ONTAP.

*Que se passe-t-il si vous ajoutez de nouvelles politiques dans SnapCenter après vous être inscrit à la BlueXP backup and recovery?*

La BlueXP backup and recovery reconnaissent toutes les nouvelles politiques créées dans SnapCenter.

*Pouvez-vous modifier les politiques de ONTAP?*

Oui, vous pouvez modifier les politiques ONTAP dans BlueXP backup and recovery. Vous pouvez également créer de nouvelles politiques dans BlueXP backup and recovery et les appliquer aux charges de travail. Cette action remplace les politiques ONTAP existantes par celles créées dans BlueXP backup and recovery.
