---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: La BlueXP backup and recovery vous permettent de gérer les informations de votre hôte de charge de travail, de votre base de données et de vos instances. Vous pouvez afficher, modifier et supprimer les paramètres de protection de votre inventaire. 
---
= Ajouter et protéger les applications Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La BlueXP backup and recovery vous permettent de découvrir facilement vos clusters Kubernetes, sans générer ni télécharger de fichiers kubeconfig. Vous pouvez connecter des clusters Kubernetes et installer les logiciels requis à l'aide de commandes simples copiées depuis l'interface utilisateur BlueXP .

.Rôle BlueXP requis
Administrateur d'organisation ou administrateur SnapCenter . link:reference-roles.html["En savoir plus sur les rôles d'accès à la BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès BlueXP pour tous les services"^] .



== Ajouter et protéger une nouvelle application Kubernetes

La première étape pour protéger les applications Kubernetes consiste à créer une application dans la BlueXP backup and recovery. Lorsque vous créez une application, vous indiquez à BlueXP qu'elle est en cours d'exécution sur le cluster Kubernetes.

.Avant de commencer
Avant de pouvoir ajouter et protéger une application Kubernetes, vous devez link:br-start-discover.html["découvrir les charges de travail Kubernetes"] .

.Étapes
. Dans la BlueXP backup and recovery, sélectionnez *Inventaire*.
. Choisissez une instance Kubernetes et sélectionnez *Afficher* pour afficher les ressources associées à cette instance.
. Sélectionnez l'onglet *Applications*.
. Sélectionnez *Créer une application*.
. Entrez un nom pour l'application.
. Vous pouvez également choisir l’un des champs suivants pour rechercher les ressources que vous souhaitez protéger :
+
** Cluster associé
** Espaces de noms associés
** Types de ressource
** Sélecteurs d'étiquettes


. Vous pouvez également sélectionner « Ressources à portée de cluster » pour choisir les ressources à portée de cluster. Si vous les incluez, elles seront ajoutées à l'application lors de sa création.
. Vous pouvez également sélectionner *Rechercher* pour trouver les ressources en fonction de vos critères de recherche.
+

NOTE: BlueXP ne stocke pas les paramètres ou les résultats de recherche ; les paramètres sont utilisés pour rechercher dans le cluster Kubernetes sélectionné des ressources pouvant être incluses dans l'application.

. BlueXP affiche une liste de ressources correspondant à vos critères de recherche.
. Si la liste contient les ressources que vous souhaitez protéger, sélectionnez *Suivant*.
. Vous pouvez également, dans la zone *Politique*, choisir une politique de protection existante pour protéger l'application ou en créer une nouvelle. Si vous ne sélectionnez pas de politique, l'application est créée sans politique de protection. Vous pourrez en ajouter une ultérieurement.
. Dans la section *Préscripts et postscripts*, activez et configurez les hooks d'exécution de préscripts ou de postscripts que vous souhaitez exécuter avant ou après les opérations de sauvegarde. Pour activer les préscripts ou les postscripts, vous devez en avoir déjà créé au moins un. link:br-use-manage-execution-hook-templates.html["modèle de crochet d'exécution"] .
. Sélectionnez *Créer*.


.Résultat
L'application est créée et apparaît dans la liste des applications de l'onglet *Applications* de l'inventaire Kubernetes. BlueXP active la protection de l'application selon vos paramètres, et vous pouvez suivre sa progression dans la section *Surveillance* de la sauvegarde et de la restauration.



== Protéger une application Kubernetes existante

Activez une politique de protection sur une application Kubernetes que vous avez déjà ajoutée.

.Étapes
. Dans la BlueXP backup and recovery, sélectionnez *Inventaire*.
. Choisissez une instance Kubernetes et sélectionnez *Afficher* pour afficher les ressources associées à cette instance.
. Sélectionnez l'onglet *Applications*.
. Dans la liste des applications, choisissez une application que vous souhaitez protéger et sélectionnez le menu Actions associé.
. Sélectionnez *protéger*.
. Dans la zone *Politique*, choisissez une politique de protection existante pour protéger l'application ou créez une nouvelle politique.
. Dans la zone *Préscripts et postscripts*, activez et configurez les hooks d'exécution de préscripts ou de postscripts à exécuter avant ou après les opérations de sauvegarde. Vous pouvez configurer le type de hook d'exécution, le modèle utilisé, les arguments et les sélecteurs d'étiquettes.
. Sélectionnez *Done*.


.Résultat
BlueXP active la protection de l'application selon vos paramètres, et vous pouvez suivre sa progression dans la section *Surveillance* de la sauvegarde et de la restauration. Dès que vous activez la protection d'une application, BlueXP crée une sauvegarde complète de celle-ci. Les sauvegardes incrémentielles ultérieures sont créées selon la planification définie dans la politique de protection associée à l'application.



== Sauvegarder une application Kubernetes maintenant

Créez manuellement une sauvegarde d'une application Kubernetes pour établir une base de référence pour les futures sauvegardes et instantanés, ou pour garantir la protection des données les plus récentes.

.Étapes
. Dans la BlueXP backup and recovery, sélectionnez *Inventaire*.
. Choisissez une instance Kubernetes et sélectionnez *Afficher* pour afficher les ressources associées à cette instance.
. Sélectionnez l'onglet *Applications*.
. Dans la liste des applications, choisissez une application que vous souhaitez sauvegarder et sélectionnez le menu Actions associé.
. Sélectionnez *Sauvegarder maintenant*.
. Assurez-vous que le nom d’application correct est sélectionné.
. Sélectionnez *Sauvegarder*.


.Résultat
BlueXP crée une sauvegarde de l'application et affiche la progression dans la zone *Surveillance* de la sauvegarde et de la restauration. La sauvegarde est créée en fonction de la politique de protection associée à l'application.
