---
sidebar: sidebar 
permalink: br-use-manage-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 'Vous pouvez sauvegarder les données des applications Microsoft SQL Server depuis des systèmes ONTAP sur site vers Amazon Web Services, Microsoft Azure, Google Cloud Platform et StorageGRID, garantissant ainsi la protection de vos données. Les sauvegardes sont automatiquement générées et stockées dans un magasin d"objets de votre compte cloud public ou privé. Vous pouvez mettre en œuvre une stratégie 3-2-1 : vous disposez de trois copies de vos données sources sur deux systèmes de stockage différents, ainsi que d"une copie dans le cloud.' 
---
= Gérer les ressources avec la vue d'ensemble de la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La gestion des ressources dans la BlueXP backup and recovery est essentielle pour garantir la protection de vos données. Vous pouvez gérer des ressources telles que les sauvegardes, les bases de données, les instances, les hôtes d'applications et les environnements de travail. Vous pouvez consulter, modifier et supprimer les paramètres de protection de vos ressources.

Vous pouvez accomplir les tâches suivantes liées à la gestion de vos ressources :

* link:br-use-manage-inventory.html["Gérer l'inventaire"].
* link:br-use-manage-snapshots.html["Gérer les snapshots"].
* link:br-use-manage-kubernetes-clusters.html["Gérez les clusters Kubernetes"].
* link:br-use-manage-kubernetes-applications.html["Gérer les applications Kubernetes"].

