---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: La BlueXP backup and recovery vous permettent de gérer les informations de votre hôte de charge de travail, de votre base de données et de vos instances. Vous pouvez afficher, modifier et supprimer les paramètres de protection de votre inventaire. 
---
= Gérer les applications Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La BlueXP backup and recovery vous permettent de gérer vos applications Kubernetes et les ressources associées. Vous pouvez créer, afficher, modifier et supprimer les paramètres de protection de vos applications Kubernetes.

.Rôle BlueXP requis
Administrateur d'organisation ou administrateur SnapCenter . link:reference-roles.html["En savoir plus sur les rôles d'accès à la BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès BlueXP pour tous les services"^] .



== Modifier une application Kubernetes

Vous pouvez modifier les paramètres d’une application Kubernetes existante si les ressources associées à l’application ont changé.

.Étapes
. Dans la BlueXP backup and recovery, sélectionnez *Inventaire* > *Applications*.
. Dans la liste des applications, choisissez une application que vous souhaitez modifier et sélectionnez le menu Actions associé.
. Sélectionnez *Modifier*.
. Apportez les modifications nécessaires à la définition de l’application, telles que le nom ou les ressources incluses.
. Une fois terminé, sélectionnez *Suivant*.
. Apportez les modifications nécessaires aux paramètres de protection.
. Une fois terminé, sélectionnez *Terminé*.




== Déprotéger une application Kubernetes

Vous pouvez déprotéger une application si vous ne souhaitez plus la protéger. Lorsque vous déprotégez une application, la BlueXP backup and recovery interrompent la protection de l'application, mais conservent toutes les sauvegardes et snapshots associés jusqu'à leur expiration.

.Étapes
. Dans la BlueXP backup and recovery, sélectionnez *Inventaire* > *Applications*.
. Dans la liste des applications, choisissez une application que vous souhaitez déprotéger et sélectionnez le menu Actions associé.
. Sélectionnez *Déprotéger*.
. Lisez l'avis et, lorsque vous êtes prêt, sélectionnez *Déprotéger*.




== Supprimer une application Kubernetes

Vous pouvez supprimer une application dont vous n'avez plus besoin. Lorsque vous supprimez une application, la BlueXP backup and recovery cessent de la protéger et, si vous le souhaitez, suppriment toutes les sauvegardes et snapshots associés.

.Étapes
. Dans la BlueXP backup and recovery, sélectionnez *Inventaire* > *Applications*.
. Dans la liste des applications, choisissez une application que vous souhaitez supprimer et sélectionnez le menu Actions associé.
. Sélectionnez *Supprimer*.
. En option, activez *Supprimer les instantanés et les sauvegardes* pour supprimer tous les instantanés et toutes les sauvegardes de l'application.
+

CAUTION: Si vous faites cela, vous ne pourrez plus restaurer l’application à l’aide de ces instantanés et sauvegardes.

. Confirmez l'action et sélectionnez *Supprimer*.

