---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: 'Commencez à utiliser la BlueXP backup and recovery en vérifiant la disponibilité de votre environnement opérationnel, de votre connecteur BlueXP et de votre compte BlueXP . Pour utiliser la BlueXP backup and recovery, vous devez remplir les conditions suivantes :' 
---
= Conditions préalables à la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Commencez à utiliser la BlueXP backup and recovery en vérifiant la disponibilité de votre environnement opérationnel, de votre connecteur BlueXP et de votre compte BlueXP . Pour utiliser la BlueXP backup and recovery, vous devez remplir les conditions suivantes :



== Pour ONTAP 9.8 et versions ultérieures

Une licence ONTAP One doit être activée sur l’instance ONTAP locale.



== Conditions préalables pour les sauvegardes sur le stockage d'objets

Pour utiliser le stockage d'objets comme cibles de sauvegarde, vous avez besoin d'un compte avec AWS S3, Microsoft Azure Blob, StorageGRID ou ONTAP et des autorisations d'accès appropriées configurées.

* link:prev-ontap-protect-overview.html["Protégez vos données de volume ONTAP"]




== Exigences pour la protection des charges de travail Microsoft SQL Server

Pour utiliser la BlueXP backup and recovery pour les charges de travail Microsoft SQL Server, vous avez besoin des prérequis suivants en matière de système hôte, d’espace et de dimensionnement.

[cols="33,66a"]
|===
| Élément | De formation 


| Systèmes d'exploitation  a| 
Microsoft Windows Pour obtenir les dernières informations sur les versions prises en charge, consultez le  https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Matrice d'interopérabilité NetApp"^] .



| Versions de Microsoft SQL Server  a| 
Les versions 2012 et ultérieures sont prises en charge pour VMware Virtual Machine File System (VMFS) et VMware Virtual Machine Disk (VMDK) NFS.



| Version du serveur SnapCenter  a| 
SnapCenter Server version 5.0 ou supérieure est requise si vous souhaitez importer vos données existantes de SnapCenter dans la BlueXP backup and recovery.


NOTE: Si vous disposez déjà de SnapCenter, vérifiez d'abord que vous avez rempli les conditions préalables avant d'importer depuis SnapCenter. Voir link:concept-start-prereq-snapcenter-import.html["Conditions préalables à l'importation de ressources depuis SnapCenter"].



| RAM minimale pour le plug-in sur l'hôte SQL Server  a| 
1 GO



| Espace minimum d'installation et de journalisation pour le plug-in sur l'hôte SQL Server  a| 
5 GO

Allouez suffisamment d'espace disque et surveillez la consommation de stockage du dossier des journaux. L'espace requis pour les journaux varie en fonction du nombre de sauvegardes effectuées et de la fréquence des opérations de protection des données. En cas d'espace insuffisant, les journaux ne seront pas créés pour les opérations.



| Packs logiciels requis  a| 
* Pack d'hébergement ASP.NET Core Runtime 8.0.12 (et tous les correctifs 8.0.x ultérieurs)
* PowerShell Core 7.4.2


Pour obtenir les dernières informations sur les versions prises en charge, consultez le https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Matrice d'interopérabilité NetApp"^].

|===


== Exigences pour la protection des charges de travail VMware

Vous avez besoin d’exigences spécifiques pour découvrir et protéger vos charges de travail VMware.

*Support logiciel*

* Les datastores NFS et VMFS sont pris en charge. Les vVols ne sont pas pris en charge.
* Versions NFS prises en charge : NFS 3 et NFS 4.1
* Versions de VMware ESXi Server prises en charge : 7.0U1 et versions ultérieures
* Versions VMware vCenter vSphere prises en charge : 7.0U1 et supérieures
* Adresses IP : IPv4 et IPv6
* VMware TLS : 1.2, 1.3


*Exigences de connexion et de port pour la protection des charges de travail VMware*

[cols="33,66a"]
|===
| Type de port | Port préconfiguré 


| Port du serveur VMware ESXi  a| 
443 (HTTPS), bidirectionnel.  La fonction de restauration de fichiers invités utilise ce port.



| Port du serveur VMware vSphere vCenter  a| 
Si vous protégez des machines virtuelles vVol, vous devez utiliser le port 443.



| Cluster de stockage ou port de VM de stockage  a| 
443 (HTTPS), bidirectionnel.  80 (HTTP), bidirectionnel.  Ce port est utilisé pour la communication entre l'appliance virtuelle et la machine virtuelle de stockage ou le cluster contenant la machine virtuelle de stockage.

|===
*Exigences de contrôle d'accès basé sur les rôles (RBAC) pour la protection des charges de travail VMware*

Le compte administrateur vCenter doit disposer des privilèges vCenter requis.

Pour une liste des privilèges vCenter nécessaires, voir https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html#rbac-privileges-required["SnapCenter Plug-in for VMware vSphere privilèges vCenter requis"^] .



== Exigences pour la protection des applications Kubernetes

Vous avez besoin d’exigences spécifiques pour découvrir les ressources Kubernetes et protéger vos applications Kubernetes.

Pour connaître les exigences de BlueXP , reportez-vous à <<Dans BlueXP>> .

* Un système ONTAP principal (ONTAP 9.16.1 ou version ultérieure)
* Un cluster Kubernetes - Les distributions et versions Kubernetes prises en charge incluent :
+
** Anthos On-Prem (VMware) et Anthos sur bare metal 1.16
** Kubernetes 1.27 - 1.33
** OpenShift 4.10 - 4.18
** Rancher Kubernetes Engine 2 (RKE2) v1.26.7+rke2r1, v1.28.5+rke2r1


* NetApp Trident 24.10 ou version ultérieure
* NetApp Trident Protect 25.07 ou version ultérieure (installé lors de la découverte de la charge de travail Kubernetes)
* NetApp Trident Protect Connector 25.07 ou version ultérieure (installé lors de la découverte de la charge de travail Kubernetes)
+
** Assurez-vous que le port TCP 443 n'est pas filtré dans le sens sortant entre le cluster Kubernetes, le connecteur Trident Protect et le proxy Trident Protect.






== Dans BlueXP

* Un utilisateur BlueXP doit disposer du rôle et des privilèges requis pour effectuer des opérations sur les charges de travail Microsoft SQL Server et Kubernetes. Pour découvrir les ressources, vous devez disposer du rôle de super-administrateur BlueXP backup and recovery . Voir link:reference-roles.html["Accès aux fonctionnalités de BlueXP backup and recovery basé sur les rôles"] pour plus de détails sur les rôles et les autorisations requis pour effectuer des opérations dans la BlueXP backup and recovery.
* Une organisation BlueXP avec au moins un connecteur BlueXP actif se connectant à des clusters ONTAP locaux ou à Cloud Volumes ONTAP. Consultez le processus de configuration de l'aperçu initial ci-dessous.
* Au moins un environnement de travail BlueXP avec un cluster NetApp sur site ONTAP ou Cloud Volumes ONTAP .
* Un connecteur BlueXP
+
Reportez-vous à https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Apprenez à configurer un connecteur BlueXP"] et https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Exigences standard de BlueXP"^].

+
** La version Preview nécessite le système d'exploitation Ubuntu 22.04 LTS pour le connecteur.






=== Configurez BlueXP

L’étape suivante consiste à configurer BlueXP et le service de BlueXP backup and recovery .

Révision https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Exigences standard de BlueXP"^].



=== Créer un connecteur BlueXP

Vous devez contacter votre équipe produit NetApp pour essayer ce service. Ensuite, lorsque vous utilisez le connecteur BlueXP, il inclut les fonctionnalités appropriées pour le service.

Pour créer un connecteur dans BlueXP  avant d'utiliser le service, reportez-vous à la documentation BlueXP  qui décrit https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Comment créer un connecteur BlueXP"^].

.Où installer le connecteur BlueXP
Pour terminer une opération de restauration, le connecteur peut être installé aux emplacements suivants :

ifdef::aws[]

* Pour Amazon S3, le connecteur peut être déployé dans vos locaux.


endif::aws[]

ifdef::azure[]

* Pour Azure Blob, le connecteur peut être déployé sur vos locaux.


endif::azure[]

ifdef::gcp[]

endif::gcp[]

* Pour StorageGRID, le connecteur doit être déployé dans vos locaux ; avec ou sans accès Internet.
* Pour ONTAP S3, le connecteur peut être déployé dans vos locaux (avec ou sans accès à Internet) ou dans un environnement de fournisseur cloud



NOTE: Les références aux « systèmes ONTAP sur site » incluent les systèmes FAS et AFF .
