---
sidebar: sidebar 
permalink: prev-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail VMware avec la BlueXP backup and recovery NetApp BlueXP. 
---
= Présentation de la protection des charges de travail des machines virtuelles dans la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Protégez vos charges de travail de machines virtuelles avec la BlueXP backup and recovery. BlueXP backup and recovery offre des opérations de sauvegarde et de restauration rapides, peu encombrantes, cohérentes en cas de panne et compatibles avec les machines virtuelles (VM), les banques de données et les VMDK.

Vous pouvez sauvegarder des datastores dans Amazon Web Services S3, Microsoft Azure Blob, Google Cloud Platform et StorageGRID, et restaurer des machines virtuelles dans le plug-in SnapCenter sur site pour l'hôte VMware vSphere.

[]
====
*REMARQUE* Pour basculer vers et depuis les charges de travail de BlueXP backup and recovery , reportez-vous à link:br-start-switch-ui.html["Basculer vers différentes charges de travail de BlueXP backup and recovery"] .

====
Pour obtenir des instructions sur la protection des charges de travail des machines virtuelles, consultez les rubriques suivantes :

* link:prev-vmware-policy-create.html["Créer une politique pour les charges de travail VMware"]
* link:prev-vmware-backup-aws.html["Sauvegarder les banques de données VMware sur Amazon Web Services"]
* link:prev-vmware-backup-azure.html["Sauvegarder les banques de données VMware sur Microsoft Azure"]
* link:prev-vmware-backup-gcp.html["Sauvegarder les banques de données VMware sur Google Cloud Platform"]
* link:prev-vmware-backup-storagegrid.html["Sauvegarder les banques de données VMware sur StorageGRID"]
* link:prev-vmware-restore.html["Restaurer les charges de travail VMware"]
* link:prev-vmware-manage.html["Gérer la protection des charges de travail VMware"]

