---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Ou du fournisseur cloud
    default: Tous les fournisseurs cloud
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation sur la sauvegarde et la restauration BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/reference-limitations.html"
  - title: Commencez
    entries:
    - title: Découvrez la sauvegarde et la restauration BlueXP
      url: "/concept-backup-to-cloud.html"
    - title: Configuration des licences
      url: "/task-licensing-cloud-backup.html"
  - title: Surveillez la protection des données
    entries:
    - title: Reporting sur la couverture de la protection des données
      url: "/task-report-inventory.html"
    - title: Surveiller l'état des tâches de sauvegarde et de restauration
      url: "/task-monitor-backup-jobs.html"
  - title: Sauvegarde et restauration des données ONTAP
    entries:
    - title: Protégez les données de vos volumes ONTAP
      url: "/concept-ontap-backup-to-cloud.html"
    - title: Planifiez votre parcours en matière de protection
      url: "/concept-protection-journey.html"
    - title: Gérez les règles des volumes ONTAP
      url: "/task-create-policies-ontap.html"
    - title: Options de règle de sauvegarde sur objet
      url: "/concept-cloud-backup-policies.html"
    - title: Gérez les options de sauvegarde sur objet dans Paramètres avancés
      url: "/task-manage-backup-settings-ontap.html"
    - title: Sauvegarde d'Cloud Volumes ONTAP dans Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: Sauvegarde d'Cloud Volumes ONTAP dans Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: Sauvegarde de Cloud Volumes ONTAP dans Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: Sauvegarde d'ONTAP sur site dans Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: Sauvegarde d'ONTAP sur site dans Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: Sauvegarde d'un système ONTAP sur site dans Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: Sauvegarde d'ONTAP sur site dans ONTAP S3
      url: "/task-backup-onprem-to-ontap-s3.html"
    - title: Sauvegarde du système ONTAP sur site dans StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: Gérer les sauvegardes ONTAP
      url: "/task-manage-backups-ontap.html"
    - title: Restaurez vos données à partir de sauvegardes ONTAP
      url: "/task-restore-backups-ontap.html"
  - title: Sauvegarde et restauration des données des applications sur site
    entries:
    - title: Protection des données applicatives sur site
      url: "/concept-protect-app-data-to-cloud.html"
    - title: Enregistrez SnapCenter Server
      url: "/task-register-snapcenter-server.html"
    - title: Créez une règle pour sauvegarder les applications
      url: "/task-create-policies-apps.html"
    - title: Sauvegardez les données des applications sur site dans Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: Sauvegardez les données applicatives sur site dans Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: Sauvegardez les données des applications sur site dans Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: Sauvegardez les données applicatives sur site dans StorageGRID
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: Gérer la protection des applications
      url: "/task-manage-app-backups.html"
    - title: Restaurez les données des applications sur site
      entries:
      - title: Restaurez la base de données Oracle
        url: "/task-restore-oracle-data.html"
      - title: Restaurez la base de données SQL Server
        url: "/task-restore-sql-data.html"
      - title: Restaurez la base de données SAP HANA
        url: "/task-restore-hana-backup.html"
      - title: Restaurez les bases de données MongoDB, MySQL et PostgreSQL
        url: "/task-restore-customplugin-backup.html"
  - title: Sauvegarde et restauration des données des machines virtuelles
    entries:
    - title: Protection des données des machines virtuelles
      url: "/concept-protect-vm-data.html"
    - title: Enregistrez le plug-in SnapCenter pour l'hôte VMware vSphere
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: Créer une stratégie pour sauvegarder les datastores
      url: "/task-create-policies-vms.html"
    - title: Sauvegarde des datastores dans Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: Sauvegarde des datastores dans Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: Sauvegarde des datastores dans Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: Sauvegarde des datastores sur StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: Gestion de la protection des données des datastores et des machines virtuelles
      url: "/task-manage-vm-data-in-cloud.html"
    - title: Restaurer les données des machines virtuelles
      url: "/task-restore-vm-data.html"
  - title: Sauvegarde et restauration des données Kubernetes
    entries:
    - title: Protéger vos données Kubernetes
      url: "/concept-kubernetes-backup-to-cloud.html"
    - title: Sauvegarde dans Amazon S3
      flavor: aws
      url: "/task-backup-kubernetes-to-s3.html"
    - title: Sauvegarde dans Azure Blob
      flavor: azure
      url: "/task-backup-kubernetes-to-azure.html"
    - title: Sauvegarde dans Google Cloud
      flavor: gcp
      url: "/task-backup-kubernetes-to-gcp.html"
    - title: Gérer les sauvegardes Kubernetes
      url: "/task-manage-backups-kubernetes.html"
    - title: Restaurez vos données à partir de sauvegardes Kubernetes
      url: "/task-restore-backups-kubernetes.html"
  - title: Automatisez avec l'API REST
    url: "/api-backup-restore.html"
  - title: Référence
    entries:
    - title: Tiers de stockage d'archivage AWS pris en charge
      url: "/reference-aws-backup-tiers.html"
    - title: Tiers d'accès d'archivage Azure pris en charge
      url: "/reference-azure-backup-tiers.html"
    - title: Tiers de stockage d'archivage Google pris en charge
      url: "/reference-google-backup-tiers.html"
    - title: Configurer la sauvegarde pour l'accès à plusieurs comptes dans Azure
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: Restaurez la base de données de sauvegarde et de restauration BlueXP
        sur un site invisible
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: Redémarrez la sauvegarde et la restauration BlueXP
      url: "/reference-restart-backup.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
