---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Ou du fournisseur cloud
    default: Tous les fournisseurs cloud
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation sur la sauvegarde et la restauration BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limitations connues pour les charges de travail Microsoft SQL Server
      url: "/br-limitations.html"
    - title: Limitations connues pour les charges de travail des volumes ONTAP
      url: "/br-reference-limitations.html"
  - title: Commencez
    entries:
    - title: Découvrez la sauvegarde et la restauration BlueXP
      url: "/concept-backup-to-cloud.html"
    - title: Conditions préalables à la BlueXP backup and recovery
      url: "/concept-start-prereq.html"
    - title: Configurez les licences pour la sauvegarde et la restauration BlueXP
      url: "/br-start-licensing.html"
    - title: Configurez les destinations de sauvegarde avant d'utiliser la BlueXP
        backup and recovery
      url: "/br-start-setup.html"
    - title: Connectez-vous à la BlueXP backup and recovery
      url: "/br-start-login.html"
    - title: Découvrir les cibles de sauvegarde
      url: "/br-start-discover-backup-targets.html"
    - title: Basculer vers différentes charges de travail de BlueXP backup and recovery
      url: "/br-start-switch-ui.html"
    - title: Configurer les paramètres généraux de BlueXP backup and recovery
      url: "/br-start-configure.html"
  - title: Utiliser la BlueXP backup and recovery
    entries:
    - title: Afficher l'état de la protection dans le tableau de bord
      url: "/br-use-dashboard.html"
    - title: Créer des politiques pour régir les sauvegardes et les restaurations
      url: "/br-use-policies-create.html"
    - title: Protéger les charges de travail du volume ONTAP
      entries:
      - title: Présentation des charges de travail du volume Protect ONTAP
        url: "/prev-ontap-protect-overview.html"
      - title: Planifiez votre parcours de protection pour les volumes ONTAP
        url: "/prev-ontap-protect-journey.html"
      - title: Gérez les règles des volumes ONTAP
        url: "/prev-ontap-policy-manage.html"
      - title: Options de stratégie de sauvegarde sur objet pour les volumes ONTAP
        url: "/prev-ontap-policy-object-options.html"
      - title: Gérer les options des paramètres avancés de la politique de sauvegarde
          sur objet
        url: "/prev-ontap-policy-object-advanced-settings.html"
      - title: Sauvegarde d'Cloud Volumes ONTAP dans Amazon S3
        url: "/prev-ontap-backup-cvo-aws.html"
      - title: Sauvegarde d'Cloud Volumes ONTAP dans Azure Blob
        url: "/prev-ontap-backup-cvo-azure.html"
      - title: Sauvegarde de Cloud Volumes ONTAP dans Google Cloud
        url: "/prev-ontap-backup-cvo-gcp.html"
      - title: Sauvegarde d'ONTAP sur site dans Amazon S3
        url: "/prev-ontap-backup-onprem-aws.html"
      - title: Sauvegarde d'ONTAP sur site dans Azure Blob
        url: "/prev-ontap-backup-onprem-azure.html"
      - title: Sauvegarde d'un système ONTAP sur site dans Google Cloud
        url: "/prev-ontap-backup-onprem-gcp.html"
      - title: Sauvegarde d'ONTAP sur site dans ONTAP S3
        url: "/prev-ontap-backup-onprem-ontaps3.html"
      - title: Sauvegarde du système ONTAP sur site dans StorageGRID
        url: "/prev-ontap-backup-onprem-storagegrid.html"
      - title: Migration de volumes à l'aide de SnapMirror pour la resynchronisation
          cloud
        url: "/prev-ontap-migrate-resync.html"
      - title: Gérer les sauvegardes ONTAP
        url: "/prev-ontap-backup-manage.html"
      - title: Restaurez vos données à partir de sauvegardes ONTAP
        url: "/prev-ontap-restore.html"
    - title: Protéger les charges de travail Microsoft SQL Server (Aperçu)
      entries:
      - title: Présentation de la protection des charges de travail Microsoft SQL
          Server
        url: "/br-use-mssql-protect-overview.html"
      - title: Configurer des éléments supplémentaires en cas d'importation depuis
          SnapCenter
        url: "/concept-start-prereq-snapcenter-import.html"
      - title: Découvrez les charges de travail Microsoft SQL Server
        url: "/br-start-discover.html"
      - title: Sauvegarder les charges de travail Microsoft SQL Server
        url: "/br-use-mssql-backup.html"
      - title: Restaurer les charges de travail Microsoft SQL Server
        url: "/br-use-mssql-restore.html"
      - title: Cloner les charges de travail Microsoft SQL Server
        url: "/br-use-mssql-clone.html"
      - title: Gérer l'inventaire de Microsoft SQL Server
        url: "/br-use-manage-inventory.html"
      - title: Gérer les instantanés de Microsoft SQL Server
        url: "/br-use-manage-snapshots.html"
      - title: Créer des rapports Microsoft SQL Server
        url: "/br-use-reports.html"
    - title: Protéger les charges de travail des machines virtuelles
      entries:
      - title: Présentation de la protection des charges de travail des machines virtuelles
        url: "/prev-vmware-protect-overview.html"
      - title: Conditions préalables à la protection des charges de travail des machines
          virtuelles
        url: "/prev-vmware-prereqs.html"
      - title: Enregistrez le plug-in SnapCenter pour l'hôte VMware vSphere
        url: "/prev-vmware-register-snapcenter.html"
      - title: Créer une politique de sauvegarde des banques de données VMware
        url: "/prev-vmware-policy-create.html"
      - title: Sauvegarde des datastores dans Amazon Web Services
        url: "/prev-vmware-backup-aws.html"
      - title: Sauvegarde des datastores dans Microsoft Azure
        url: "/prev-vmware-backup-azure.html"
      - title: Sauvegarde des datastores dans Google Cloud Platform
        url: "/prev-vmware-backup-gcp.html"
      - title: Sauvegarde des datastores sur StorageGRID
        url: "/prev-vmware-backup-storagegrid.html"
      - title: Gestion de la protection des données des datastores et des machines
          virtuelles
        url: "/prev-vmware-manage.html"
      - title: Restaurer les banques de données VMware
        url: "/prev-vmware-restore.html"
    - title: Surveiller les tâches
      url: "/br-use-monitor-tasks.html"
    - title: Redémarrez la sauvegarde et la restauration BlueXP
      url: "/reference-restart-backup.html"
  - title: Automatisez avec l'API REST
    url: "/br-api-backup-restore.html"
  - title: Référence
    entries:
    - title: Stratégies dans SnapCenter comparées à la BlueXP backup and recovery
      url: "/reference-policy-differences-snapcenter.html"
    - title: Rôles et privilèges de BlueXP backup and recovery
      url: "/reference-roles.html"
    - title: Tiers de stockage d'archivage AWS pris en charge
      url: "/prev-reference-aws-archive-storage-tiers.html"
    - title: Niveaux de stockage d'archives Azure pris en charge
      url: "/prev-reference-azure-archive-storage-tiers.html"
    - title: Niveaux de stockage d'archives Google Cloud pris en charge
      url: "/prev-reference-gcp-archive-storage-tiers.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
