---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Ou du fournisseur cloud
    default: Tous les fournisseurs cloud
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation sur la sauvegarde et la restauration BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez la sauvegarde et la restauration BlueXP
      url: "/concept-backup-to-cloud.html"
    - title: Configuration des licences
      url: "/task-licensing-cloud-backup.html"
  - title: Surveillez la protection des données
    entries:
    - title: Reporting sur la couverture de la protection des données
      url: "/task-report-inventory.html"
    - title: Surveiller l'état des tâches de sauvegarde et de restauration
      url: "/task-monitor-backup-jobs.html"
  - title: Sauvegarde et restauration des données ONTAP
    entries:
    - title: Protégez les données de vos volumes ONTAP
      url: "/concept-ontap-backup-to-cloud.html"
    - title: Sauvegarde d'Cloud Volumes ONTAP dans Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: Sauvegarde d'Cloud Volumes ONTAP dans Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: Sauvegarde de Cloud Volumes ONTAP dans Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: Sauvegarde d'ONTAP sur site dans Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: Sauvegarde d'ONTAP sur site dans Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: Sauvegarde d'un système ONTAP sur site dans Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: Sauvegarde du système ONTAP sur site dans StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: Gérer les sauvegardes ONTAP
      url: "/task-manage-backups-ontap.html"
    - title: Gérez les paramètres de sauvegarde au niveau du cluster
      url: "/task-manage-backup-settings-ontap.html"
    - title: Restaurez vos données à partir de sauvegardes ONTAP
      url: "/task-restore-backups-ontap.html"
  - title: Sauvegarde et restauration des données des applications sur site
    entries:
    - title: Protection des données applicatives sur site
      url: "/concept-protect-app-data-to-cloud.html"
    - title: Enregistrez SnapCenter Server
      url: "/task-register-snapcenter-server.html"
    - title: Créez une règle pour sauvegarder les applications
      url: "/task-create-policies-apps.html"
    - title: Sauvegardez les données des applications sur site dans Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: Sauvegardez les données applicatives sur site dans Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: Sauvegardez les données des applications sur site dans Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: Sauvegardez les données applicatives sur site dans StorageGRID
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: Gérer la protection des applications
      url: "/task-manage-app-backups.html"
    - title: Restaurez les données des applications sur site
      entries:
      - title: Restaurez la base de données Oracle
        url: "/task-restore-oracle-data.html"
      - title: Restaurez la base de données SQL Server
        url: "/task-restore-sql-data.html"
    - title: Montage des sauvegardes d'applications
      url: "/task-mount-app-backup.html"
  - title: Sauvegarde et restauration des données applicatives cloud
    entries:
    - title: Protégez vos données d'applications cloud natives
      url: "/concept-protect-cloud-app-data-to-cloud.html"
    - title: Sauvegarde des bases de données Oracle cloud natives
      entries:
      - title: Démarrage rapide
        url: "/task-quick-start-oracle.html"
      - title: Configurer FSX pour ONTAP
        url: "/reference-configure-fsx-for-ontap.html"
      - title: Configurez Cloud Volumes ONTAP
        url: "/reference-configure-cloud-volumes-ontap.html"
      - title: Configurez Azure NetApp Files
        flavor: azure
        url: "/reference-configure-azure-netapp-files.html"
      - title: Installez le plug-in SnapCenter pour Oracle et ajoutez des hôtes de
          base de données
        url: "/task-add-host-discover-oracle-databases.html"
      - title: Sauvegarde des bases de données Oracle
        url: "/task-backup-cloud-native-oracle-data.html"
    - title: Sauvegarde des bases de données SAP HANA cloud natives
      entries:
      - title: Démarrage rapide
        flavor: azure
        url: "/task-quick-start-hana.html"
      - title: Configurez Azure NetApp Files
        flavor: azure
        url: "/reference-configure-azure-netapp-files.html"
      - title: Installez le plug-in SnapCenter pour SAP HANA et ajoutez des hôtes
          de base de données
        flavor: azure
        url: "/task-deploy-snapcenter-plugin-for-sap-hana.html"
      - title: Sauvegarde des bases de données SAP HANA
        flavor: azure
        url: "/task-backup-cloud-native-sap-hana-data.html"
    - title: Restaurez des bases de données Oracle cloud natives
      url: "/task-restore-cloud-native-oracle-data.html"
    - title: Restaurez des bases de données SAP HANA cloud natives
      flavor: azure
      url: "/task-restore-cloud-native-sap-hana-data.html"
    - title: Actualisez le système cible SAP HANA
      flavor: azure
      url: "/task-refresh-sap-hana-target-system.html"
    - title: Clonez des bases de données Oracle cloud natives
      entries:
      - title: Concepts et conditions de clonage
        url: "/concept-clone-cloud-native-oracle-concepts.html"
      - title: Clonez des bases de données Oracle cloud natives
        url: "/task-clone-cloud-native-oracle-data.html"
    - title: Gérez la protection des données applicatives cloud
      url: "/task-manage-cloud-native-app-data.html"
  - title: Sauvegarde et restauration des données des machines virtuelles
    entries:
    - title: Protection des données des machines virtuelles
      url: "/concept-protect-vm-data.html"
    - title: Enregistrez le plug-in SnapCenter pour l'hôte VMware vSphere
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: Créer une stratégie pour sauvegarder les datastores
      url: "/task-create-policies-vms.html"
    - title: Sauvegarde des datastores dans Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: Sauvegarde des datastores dans Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: Sauvegarde des datastores dans Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: Sauvegarde des datastores sur StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: Gestion de la protection des données des datastores et des machines virtuelles
      url: "/task-manage-vm-data-in-cloud.html"
    - title: Restaurer les données des machines virtuelles
      url: "/task-restore-vm-data.html"
  - title: Sauvegarde et restauration des données Kubernetes
    entries:
    - title: Protéger vos données Kubernetes
      url: "/concept-kubernetes-backup-to-cloud.html"
    - title: Sauvegarde dans Amazon S3
      flavor: aws
      url: "/task-backup-kubernetes-to-s3.html"
    - title: Sauvegarde dans Azure Blob
      flavor: azure
      url: "/task-backup-kubernetes-to-azure.html"
    - title: Sauvegarde dans Google Cloud
      flavor: gcp
      url: "/task-backup-kubernetes-to-gcp.html"
    - title: Gérer les sauvegardes Kubernetes
      url: "/task-manage-backups-kubernetes.html"
    - title: Restaurez vos données à partir de sauvegardes Kubernetes
      url: "/task-restore-backups-kubernetes.html"
  - title: Automatisez avec l'API REST
    url: "/api-backup-restore.html"
  - title: Référence
    entries:
    - title: Paramètres de stratégie de sauvegarde
      url: "/concept-cloud-backup-policies.html"
    - title: Tiers de stockage d'archivage AWS pris en charge
      url: "/reference-aws-backup-tiers.html"
    - title: Tiers d'accès d'archivage Azure pris en charge
      url: "/reference-azure-backup-tiers.html"
    - title: Tiers de stockage d'archivage Google pris en charge
      url: "/reference-google-backup-tiers.html"
    - title: Configurer la sauvegarde pour l'accès à plusieurs comptes dans Azure
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: Restaurez la base de données de sauvegarde et de restauration BlueXP
        sur un site invisible
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: Redémarrez la sauvegarde et la restauration BlueXP
      url: "/reference-restart-backup.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrez la sauvegarde et la restauration BlueXP
      url: concept-backup-to-cloud.html
    - title: Quoi de neuf
      url: whats-new.html
    - title: Configuration des licences
      url: task-licensing-cloud-backup.html
    - title: Surveiller l'état des tâches de sauvegarde et de restauration
      url: task-monitor-backup-jobs.html
  - title: Sauvegardez les données ONTAP dans le cloud
    links:
    - title: Cloud Volumes ONTAP vers Amazon S3
      url: task-backup-to-s3.html
      flavor: aws
    - title: De Cloud Volumes ONTAP vers Azure Blob
      url: task-backup-to-azure.html
      flavor: azure
    - title: De Cloud Volumes ONTAP à Google Cloud
      url: task-backup-to-gcp.html
      flavor: gcp
    - title: ONTAP sur site vers Amazon S3
      url: task-backup-onprem-to-aws.html
      flavor: aws
    - title: ONTAP sur site vers Azure Blob
      url: task-backup-onprem-to-azure.html
      flavor: azure
    - title: ONTAP sur site vers Google Cloud
      url: task-backup-onprem-to-gcp.html
      flavor: gcp
    - title: Du ONTAP au StorageGRID sur site
      url: task-backup-onprem-private-cloud.html
  - title: Gérer les fichiers de sauvegarde ONTAP
    links:
    - title: Activer et désactiver les sauvegardes de volume
      url: task-manage-backups-ontap.html#enabling-and-disabling-backups-of-volumes
    - title: Modifiez une stratégie de sauvegarde existante
      url: task-manage-backups-ontap.html#editing-an-existing-backup-policy
    - title: Ajoutez une nouvelle stratégie de sauvegarde
      url: task-manage-backups-ontap.html#adding-a-new-backup-policy
    - title: Modifier la stratégie attribuée aux volumes existants
      url: task-manage-backups-ontap.html#changing-the-policy-assigned-to-existing-volumes
    - title: Créer une sauvegarde de volume manuelle
      url: task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time
    - title: Afficher la liste des sauvegardes pour chaque volume
      url: task-manage-backups-ontap.html#viewing-the-list-of-backups-for-each-volume
    - title: Supprimer les sauvegardes
      url: task-manage-backups-ontap.html#deleting-backups
  - title: Sauvegardez les données d'applications dans le cloud
    links:
    - title: Sauvegardez les données des applications sur site dans Amazon Web Services
      flavor: aws
      url: task-backup-app-data-to-aws.html
    - title: Sauvegardez les données applicatives sur site dans Microsoft Azure
      flavor: azure
      url: task-backup-app-data-to-azure.html
    - title: Sauvegardez les données des applications sur site dans Google Cloud
      flavor: gcp
      url: task-backup-app-data-to-gcp.html
    - title: Sauvegardez les données applicatives sur site dans StorageGRID
      url: task-backup-app-data-to-storagegrid.html
    - title: Sauvegardez une base de données Oracle cloud native
      url: task-backup-cloud-native-oracle-data.html
    - title: Sauvegarde de la base de données SAP HANA cloud native
      flavor: azure
      url: task-backup-cloud-native-sap-hana-data.html
  - title: Sauvegardez les datastores dans le cloud
    links:
    - title: Sauvegarde des datastores dans Amazon Web Services
      flavor: aws
      url: task-backup-vm-data-to-aws.html
    - title: Sauvegarde des datastores dans Microsoft Azure
      flavor: azure
      url: task-backup-vm-data-to-azure.html
    - title: Sauvegarde des datastores dans Google Cloud Platform
      flavor: gcp
      url: task-backup-vm-data-to-gcp.html
    - title: Sauvegarde des datastores sur StorageGRID
      url: task-backup-vm-data-to-storagegrid.html
  - title: Restaurez les données depuis le cloud
    links:
    - title: Restaurez les données du volume ONTAP
      url: task-restore-backups-ontap.html
    - title: Restaurez les données des applications Oracle sur site
      url: task-restore-oracle-data.html
    - title: Restaurez les données d'applications SQL Server sur site
      url: task-restore-sql-data.html
    - title: Restaurez les données des applications Oracle cloud natives
      url: task-restore-cloud-native-oracle-data.html
    - title: Restaurez les données des applications SAP HANA cloud natives
      flavor: azure
      url: task-restore-cloud-native-sap-hana-data.html
    - title: Restaurer les données des machines virtuelles
      url: task-restore-vm-data.html
    - title: Restaurez les données de volume Kubernetes
      url: task-restore-backups-kubernetes.html
  - title: Sauvegardez les données Kubernetes dans le cloud
    links:
    - title: Cluster Kubernetes vers Amazon S3
      url: task-backup-kubernetes-to-s3.html
      flavor: aws
    - title: Cluster Kubernetes vers Azure Blob
      url: task-backup-kubernetes-to-azure.html
      flavor: azure
    - title: Cluster Kubernetes vers Google Cloud
      url: task-backup-kubernetes-to-gcp.html
      flavor: gcp
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Public-Cloud-Services/ct-p/CDS
    - title: Blogs sur la sauvegarde et la restauration BlueXP
      url: https://bluexp.netapp.com/blog/topic/cloud-backup
    - title: Utilisations de la sauvegarde et de la restauration BlueXP
      url: https://bluexp.netapp.com/cloud-backup
    - title: Webinaires BlueXP
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Toute la documentation BlueXP
