---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: 'Créer l"environnement de travail Azure NetApp Files et le connecteur' 
---
= Configurez Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez créer l'environnement de travail Azure NetApp Files et le connecteur.



== Créer un environnement de travail Azure NetApp Files

Vous devez créer des environnements de travail Azure NetApp Files dans lesquels vos bases de données sont hébergées. Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["Découvrez Azure NetApp Files"] et link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["Créer un environnement de travail Azure NetApp Files"].



== Créer un connecteur

Un administrateur de compte doit déployer un connecteur dans Azure NetApp Files qui permet à BlueXP de gérer les ressources et les processus dans votre environnement de cloud public.


NOTE: Vous ne pouvez pas mettre à jour le nouvel ID_connecteur à partir de l'interface utilisateur.

Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["Créez un connecteur dans Azure à partir de BlueXP"].
