---
sidebar: sidebar 
permalink: reference-configure-cloud-volumes-ontap.html 
keywords: Cloud Manager, Cloud Volumes ONTAP, working environment, Connector, BlueXP 
summary: 'Créer l"environnement de travail Cloud Volumes ONTAP et le connecteur' 
---
= Configurez Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avec BlueXP, vous devez créer un environnement de travail Cloud Volumes ONTAP pour ajouter et gérer des volumes et des services de données supplémentaires. Vous devez également créer un connecteur pour votre environnement cloud permettant à BlueXP de gérer les ressources et les processus au sein de votre environnement de cloud public.



== Créer un environnement de travail Cloud Volumes ONTAP

Vous pouvez découvrir et ajouter des systèmes Cloud Volumes ONTAP existants à BlueXP. Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["Ajout de systèmes Cloud Volumes ONTAP existants à BlueXP"].



== Créer un connecteur

Vous pouvez commencer à utiliser Cloud Volumes ONTAP pour votre environnement cloud en quelques étapes. Pour plus d'informations, reportez-vous à l'une des sections suivantes :

* link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-aws.html["Démarrage rapide de Cloud Volumes ONTAP dans AWS"]
* link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-azure.html["Démarrage rapide de Cloud Volumes ONTAP dans Azure"]
* link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-gcp.html["Démarrage rapide pour Cloud Volumes ONTAP dans Google Cloud"]


Vous devez utiliser le même connecteur pour gérer à la fois l'environnement de travail Cloud Volumes ONTAP et les bases de données.

* Si votre environnement de travail Cloud Volumes ONTAP et vos bases de données se trouvent dans le même cloud privé virtuel (VPC) ou vnet, vous pouvez déployer le connecteur sur le même VPC ou vnet.
* Si vous disposez de l'environnement de travail Cloud Volumes ONTAP et des bases de données dans différents VPC ou réseaux virtuels, assurez-vous que les VPC ou les réseaux sont associés.

