---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database 
summary: 'Lors de l"utilisation de la sauvegarde et de la restauration BlueXP sur un site sans accès à Internet, connu sous le nom de « mode privé », les données de configuration de sauvegarde et de restauration BlueXP sont sauvegardées dans le compartiment StorageGRID où vos sauvegardes sont stockées. En cas de problème avec le système hôte du connecteur BlueXP, vous pouvez déployer un nouveau connecteur et restaurer les données de sauvegarde et de restauration BlueXP stratégiques.' 
---
= Restaurez les données de sauvegarde et de restauration BlueXP dans un site invisible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de l'utilisation de la sauvegarde et de la restauration BlueXP sur un site sans accès Internet, connu sous le nom de « mode privé » ou de « site invisible », les données de configuration de sauvegarde et de restauration BlueXP sont sauvegardées dans le compartiment StorageGRID où vos sauvegardes sont stockées. En cas de problème avec le système hôte du connecteur BlueXP, vous pouvez déployer un nouveau connecteur et restaurer les données de sauvegarde et de restauration BlueXP stratégiques.

Notez que lorsque vous utilisez la sauvegarde et la restauration BlueXP dans un environnement SaaS où le connecteur BlueXP est déployé dans votre fournisseur cloud ou sur votre propre système hôte disposant d'un accès Internet, toutes les données importantes de configuration de la sauvegarde et de la restauration BlueXP sont sauvegardées et protégées dans le cloud. Si vous rencontrez un problème avec le connecteur, il vous suffit de créer un nouveau connecteur et d'ajouter vos environnements de travail. Les détails de la sauvegarde sont automatiquement restaurés.

Il existe 2 types de données sauvegardées :

* Base de données de sauvegarde et de restauration BlueXP : contient la liste de tous les volumes, fichiers de sauvegarde, règles de sauvegarde et informations de configuration.
* Fichiers de catalogue indexés : contient des index détaillés qui sont utilisés pour la fonctionnalité de recherche et de restauration qui rendent vos recherches très rapides et efficaces lors de la recherche de données de volume que vous souhaitez restaurer.


Ces données sont sauvegardées une fois par jour à minuit, et un maximum de 7 copies de chaque fichier sont conservées. Si le connecteur gère plusieurs environnements de travail ONTAP sur site, les fichiers de sauvegarde et de restauration BlueXP seront situés dans le compartiment de l'environnement de travail qui a été activé en premier.


TIP: Aucune donnée de volume n'est jamais incluse dans la base de données de sauvegarde et de restauration BlueXP ou dans les fichiers de catalogue indexés.



== Restaurez les données de sauvegarde et de restauration BlueXP sur un nouveau connecteur

Si votre connecteur sur site présente une défaillance majeure, vous devrez installer un nouveau connecteur, puis restaurer les données de sauvegarde et de restauration BlueXP sur le nouveau connecteur.

Pour rétablir votre système de sauvegarde et de restauration BlueXP opérationnel, vous devez effectuer 4 tâches :

* Installez un nouveau connecteur BlueXP
* Restaurez la base de données de sauvegarde et de restauration BlueXP
* Restaurez les fichiers de catalogue indexés
* Redécouvrez tous vos systèmes ONTAP et StorageGRID sur site dans l'interface utilisateur BlueXP


Une fois que vous avez vérifié que votre système est de nouveau en bon état de fonctionnement, nous vous recommandons de créer de nouveaux fichiers de sauvegarde.

.Ce dont vous avez besoin
Vous devez accéder aux sauvegardes de base de données et d'index les plus récentes à partir du compartiment StorageGRID où vos fichiers de sauvegarde sont stockés :

* Sauvegarde et restauration BlueXP fichier de base de données MySQL
+
Ce fichier se trouve à l'emplacement suivant dans le compartiment `netapp-backup-<GUID>/mysql_backup/`, et il est nommé `CBS_DB_Backup_<day>_<month>_<year>.sql`.

* Fichier zip de sauvegarde du catalogue indexé
+
Ce fichier se trouve à l'emplacement suivant dans le compartiment `netapp-backup-<GUID>/catalog_backup/`, et il est nommé `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip`.





=== Installez un nouveau connecteur sur un nouvel hôte Linux sur site

Lors de l'installation d'un nouveau connecteur BlueXP, assurez-vous de télécharger la même version de logiciel que celle installée sur le connecteur d'origine. Les modifications périodiques de la structure de la base de données de sauvegarde et de restauration BlueXP peuvent rendre incompatibles les nouvelles versions logicielles avec les sauvegardes de base de données d'origine. C'est possible https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html#upgrade-the-connector-on-prem-without-internet-access["Mettez à niveau le logiciel du connecteur vers la version la plus récente après avoir restauré la base de données de sauvegarde"^].

. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Installez le connecteur BlueXP sur un nouvel hôte Linux sur site"^]
. Connectez-vous à BlueXP à l'aide des informations d'identification utilisateur administrateur que vous venez de créer.




=== Restaurez la base de données de sauvegarde et de restauration BlueXP

. Copiez la sauvegarde MySQL de l'emplacement de sauvegarde vers le nouvel hôte de connecteur. Nous utiliserons le nom de fichier exemple « CBS_DB_Backup_23_05_2023.sql » ci-dessous.
. Copiez la sauvegarde dans le conteneur MySQL docker à l'aide de la commande suivante :
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. Entrez le shell du conteneur MySQL à l'aide de la commande suivante :
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. Dans le conteneur, déployez l'« env ».
. Vous aurez besoin du mot de passe MySQL DB, donc copiez la valeur de la clé "MYSQL_ROOT_PASSWORD".
. Restaurez la base de données MySQL de sauvegarde et de restauration BlueXP à l'aide de la commande suivante :
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. Vérifiez que la base de données MySQL de sauvegarde et de restauration BlueXP a été correctement restaurée à l'aide des commandes SQL suivantes :
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
Saisissez le mot de passe.

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
Vérifiez si les volumes affichés sont identiques à ceux qui existaient dans votre environnement d'origine.





=== Restaurez les fichiers de catalogue indexés

. Copiez le fichier zip de sauvegarde du catalogue indexé (nous utiliserons l'exemple de nom de fichier « Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip ») de l'emplacement de sauvegarde vers le nouvel hôte du connecteur dans le dossier « /opt/application/netapp/cbs ».
. Décompressez le fichier « Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip » à l'aide de la commande suivante :
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. Exécutez la commande *ls* pour vous assurer que le dossier "catalog 1" a été créé avec les sous-dossiers "modifications" et "instantanés" ci-dessous.




=== Découvrir les clusters ONTAP et les systèmes StorageGRID

. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["Découvrez tous les environnements de travail ONTAP sur site"^] qui étaient disponibles dans votre environnement précédent.
. https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Découvrir vos systèmes StorageGRID"^].




=== Configurer les détails de l'environnement StorageGRID

Ajoutez les détails du système StorageGRID associé à vos environnements de travail ONTAP tels qu'ils ont été configurés dans la configuration du connecteur d'origine à l'aide du https://docs.netapp.com/us-en/bluexp-automation/index.html["API BlueXP"^].

Ces étapes sont nécessaires pour chaque système ONTAP qui sauvegarde des données sur StorageGRID.

. Extrayez le jeton d'autorisation à l'aide de l'API oauth/token suivante.
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100101 Firefox/108.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":admin@netapp.com,"password":"Netapp@123","grant_type":"password"}
> '
----
+
Cette API renvoie une réponse comme suit. Vous pouvez récupérer le jeton d'autorisation comme indiqué ci-dessous.

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. Extrayez l'ID de l'environnement de travail et l'ID-agent-X à l'aide de l'API location/externe/ressource.
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
Cette API renvoie une réponse comme suit. La valeur sous "resourceIdentifier" désigne l'ID _WorkingEnvironment_ et la valeur sous "agentID" indique _x-agent-ID_.

. Mettez à jour la base de données de sauvegarde et de restauration BlueXP avec les détails du système StorageGRID associé aux environnements de travail. Veillez à saisir le nom de domaine complet du StorageGRID, ainsi que la clé d'accès et la clé de stockage, comme indiqué ci-dessous :
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== Vérifiez les paramètres de sauvegarde et de restauration BlueXP

. Sélectionnez chaque environnement de travail ONTAP et cliquez sur *Afficher les sauvegardes* en regard du service de sauvegarde et de restauration dans le panneau de droite.
+
Vous devriez pouvoir voir toutes les sauvegardes qui ont été créées pour vos volumes.

. Dans le Tableau de bord de restauration, sous la section Rechercher et restaurer, cliquez sur *Paramètres d'indexation*.
+
Assurez-vous que les environnements de travail où le catalogage indexé est activé précédemment restent activés.

. À partir de la page Rechercher et restaurer, exécutez quelques recherches de catalogue pour confirmer que la restauration du catalogue indexé a bien été effectuée.

