---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: 'Créer l"environnement de travail Azure NetApp Files et le connecteur' 
---
= Configurez Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avec BlueXP, vous devez créer un environnement de travail Azure NetApp Files pour ajouter et gérer des volumes et des services de données supplémentaires. Vous devez également créer un connecteur dans Azure permettant à BlueXP de gérer les ressources et les processus dans votre environnement de cloud public.



== Créer un environnement de travail Azure NetApp Files

Vous devez créer des environnements de travail Azure NetApp Files dans lesquels vos bases de données sont hébergées. Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["Découvrez Azure NetApp Files"] et link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["Créer un environnement de travail Azure NetApp Files"].



== Créer un connecteur

Un administrateur de compte BlueXP doit déployer un connecteur dans Azure qui permet à BlueXP de gérer les ressources et les processus dans votre environnement de cloud public.


NOTE: Vous ne pouvez pas mettre à jour le nouvel ID_connecteur à partir de l'interface utilisateur.

Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["Créez un connecteur dans Azure à partir de BlueXP"].

* Vous devez utiliser le même connecteur pour gérer à la fois l'environnement de travail Azure NetApp Files et les bases de données.
* Si votre environnement de travail Azure NetApp Files et vos bases de données se trouvent dans le même cloud privé virtuel (VPC), vous pouvez déployer le connecteur dans le même VPC.
* Si l'environnement de travail Azure NetApp Files et les bases de données se trouvent dans différents VPC et que les charges de travail NAS (NFS) sont configurées sur Azure NetApp Files, vous pouvez créer le connecteur sur l'un des VPC.


Après avoir créé le connecteur, procédez comme suit :

* Ajoutez l'environnement de travail en cliquant sur *Storage* > *Canvas* > *My Working Environments* > *Add Working Environment*.
+
Vérifiez que le connecteur est connecté aux hôtes de base de données et à l'environnement de travail Azure NetApp Files. Le connecteur doit se connecter à l'environnement de travail Azure NetApp Files.

* Copiez l'ID du connecteur en cliquant sur *connecteur > gérer les connecteurs* et en sélectionnant le nom du connecteur.

