---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: 'Créer l"environnement de travail Azure NetApp Files et le connecteur' 
---
= Configurez Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avec BlueXP, vous devez créer un environnement de travail Azure NetApp Files pour ajouter et gérer des volumes et des services de données supplémentaires. Vous devez également créer un connecteur dans Azure permettant à BlueXP de gérer les ressources et les processus dans votre environnement de cloud public.



== Créer un environnement de travail Azure NetApp Files

Vous devez créer des environnements de travail Azure NetApp Files dans lesquels vos bases de données sont hébergées. Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["Découvrez Azure NetApp Files"] et link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["Créer un environnement de travail Azure NetApp Files"].



== Créer un connecteur

Un administrateur de compte BlueXP doit déployer un connecteur dans Azure qui permet à BlueXP de gérer les ressources et les processus dans votre environnement de cloud public.

Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["Créez un connecteur dans Azure à partir de BlueXP"].

* Assurez-vous qu'il y a une connectivité entre le connecteur et les hôtes de la base de données.
* Si vous disposez de l'environnement de travail Azure NetApp Files et des bases de données sur le même réseau virtuel (vnet), vous pouvez déployer le connecteur dans le même vnet.
* Si l'environnement de travail Azure NetApp Files et les bases de données se trouvent dans différents réseaux virtuels et que les charges de travail NAS (NFS) sont configurées sur Azure NetApp Files, vous pouvez créer le connecteur sur l'un des réseaux virtuels.


Après avoir créé le connecteur, ajoutez l'environnement de travail en cliquant sur *Storage* > *Canvas* > *Mes environnements de travail* > *Ajouter un environnement de travail*.
