---
sidebar: sidebar 
permalink: task-backup-cloud-native-sql-data.html 
keywords: BlueXP, scheduled backups, on-demand backups, create policy, SQL database 
summary: Créez une règle, attribuez-la, puis créez des sauvegardes à la demande de la base de données SQL. 
---
= Sauvegarde des bases de données Microsoft SQL Server cloud natives
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer des sauvegardes planifiées ou à la demande en attribuant les stratégies que vous avez créées.



== Création d'une règle de sauvegarde

Vous pouvez exécuter cette API pour créer la règle de sauvegarde.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backup/policies'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backup%20Policies/MSSQLBackupPolicyService_CreateMSSQLBackupPolicy[]

Cette API crée un travail qui peut être suivi à partir de l'onglet *Job Monitor* de l'interface utilisateur BlueXP.



=== Paramètres

|===
| Nom | Type | Obligatoire 


 a| 
nom
 a| 
chaîne
 a| 
Vrai



 a| 
type_sauvegarde
 a| 
chaîne
 a| 
Vrai



 a| 
copie_seule_sauvegarde
 a| 
chaîne
 a| 
Faux



 a| 
est_système_défini
 a| 
chaîne
 a| 
Faux



 a| 
backup_name_format
 a| 
chaîne
 a| 
Vrai



 a| 
type_programme
 a| 
chaîne
 a| 
Vrai



 a| 
heure_de_début
 a| 
numéro
 a| 
Vrai



 a| 
heures_intervalle
 a| 
numéro
 a| 
Vrai



 a| 
intervalle_minutes
 a| 
numéro
 a| 
Vrai



 a| 
retention_type
 a| 
chaîne
 a| 
Vrai



 a| 
retention_count
 a| 
numéro
 a| 
Vrai



 a| 
heure_de_fin
 a| 
numéro
 a| 
Vrai

|===


=== Réponse

Si l'API est exécutée avec succès, le code de réponse 201 s'affiche.

Exemple :

[listing]
----
{
    "_links": {
    "self": {
        "href": "/api/resourcelink"
      }
    }
}
----


== Attribuez une règle à une instance de base de données SQL

Vous pouvez exécuter cette API pour affecter une règle à une instance de base de données SQL.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances/{id}/policy-assignment'

Où, _ID_ est l'ID d'instance MSSQL obtenu en exécutant l'API d'instance de la base de données de découverte. Pour plus d'informations, reportez-vous à la section link:task-add-sqlhost-install-plugin-sql.html#discover-the-database-instances["Découvrir les instances de base de données"].

Le tableau d'ID est la saisie ici. Par exemple :

[listing]
----
[
  "c9f3e68d-1f9c-44dc-b9af-72a9dfc54320"
]
----
Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Policy%20Assignment/PostMSSQLInstanceAssignPolicyRequest[]

Cette API crée un travail qui peut être suivi à partir de l'onglet *Job Monitor* de l'interface utilisateur BlueXP.



=== Réponse

Si l'API est exécutée avec succès, le code de réponse 202 s'affiche.

Exemple :

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== Créez une sauvegarde à la demande

Vous pouvez exécuter cette API pour créer une sauvegarde à la demande.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backups/CreateMSSQLBackupRequest[]

Cette API crée un travail qui peut être suivi à partir de l'onglet *Job Monitor* de l'interface utilisateur BlueXP.



=== Paramètres

|===
| Nom | Type | Obligatoire 


 a| 
id


NOTE: Il s'agit de l'ID de l'instance de base de données MSSQL.
 a| 
chaîne
 a| 
Vrai



 a| 
type_ressource
 a| 
chaîne
 a| 
Vrai



 a| 
id_règle
 a| 
chaîne
 a| 
Vrai



 a| 
type_programme
 a| 
chaîne
 a| 
Vrai

|===


=== Réponse

Si l'API est exécutée avec succès, le code de réponse 202 s'affiche.

Exemple :

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== Afficher les sauvegardes

Vous pouvez exécuter ces API pour afficher la liste de toutes les sauvegardes et les détails d'une sauvegarde spécifique.

'OBTENEZ snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups'

'OBTENEZ snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups/{id}'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backups/MSSQLGetBackupsRequest[]



=== Réponse

Si l'API est exécutée avec succès, le code de réponse 200 s'affiche.

Exemple :

[listing]
----
{
    "total_records": 1,
    "num_records": 1,
    "records": [
        {
            "backup_id": "602d7796-8074-43fc-a178-eee8c78566ac",
            "resource_id": "a779578d-cf78-46f3-923d-b9223255938c",
            "backup_name": "Hourly_policy2_scspa2722211001_NAMEDINSTANCE1_2023_08_08_07_02_01_81269_0",
            "policy_name": "policy2",
            "schedule_type": "Hourly",
            "start_time": "2023-08-08T07:02:10.203Z",
            "end_time": "0001-01-01T00:00:00Z",
            "backup_status": "success",
            "backup_type": "FullBackup"
        }
    ],
    "_links": {
        "next": {}
    }
}
----