---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: 'Enregistrez le plug-in SnapCenter pour l"hôte VMware vSphere dans BlueXP.' 
---
= Enregistrez le plug-in SnapCenter pour l'hôte VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez enregistrer le plug-in SnapCenter pour l'hôte VMware vSphere dans BlueXP pour afficher les datastores et les machines virtuelles. Seul un utilisateur disposant d'un accès administrateur peut enregistrer le plug-in SnapCenter pour l'hôte VMware vSphere.

.Étapes
. Dans l'interface utilisateur BlueXP, cliquez sur *protection* > *sauvegarde et récupération* > *machines virtuelles*.
. Dans la liste déroulante *Paramètres*, cliquez sur *Plug-in SnapCenter pour VMware vSphere*.
. Cliquez sur *Enregistrer le plug-in SnapCenter pour VMware vSphere*.
. Spécifiez les informations suivantes :
+
.. Dans le champ plug-in SnapCenter pour VMware vSphere, spécifiez le nom de domaine complet ou l'adresse IP du plug-in SnapCenter pour l'hôte VMware vSphere.
.. Dans le champ Port, spécifiez le numéro de port sur lequel le plug-in SnapCenter pour l'hôte VMware vSphere est exécuté.
+
Vous devez vous assurer que la communication est ouverte entre le plug-in SnapCenter sur site pour l'hôte VMware vSphere qui s'exécute sur le port 8144 par défaut et l'instance de connecteur BlueXP qui peut être exécutée sur n'importe quel fournisseur cloud (Amazon Web Services, Microsoft Azure, Google Cloud Platform) ou sur site.

.. Dans le champ Nom d'utilisateur et Mot de passe, spécifiez les informations d'identification de l'utilisateur vCenter avec le rôle d'administrateur.


. Cliquez sur *Enregistrer*.


*Après la fin*

Cliquez sur *sauvegarde et restauration* > *machines virtuelles* pour afficher tous les datastores et machines virtuelles protégés à l'aide du plug-in SnapCenter pour l'hôte VMware vSphere enregistré.
