---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: Vous pouvez restaurer la base de données SQL Server depuis le cloud vers le serveur SnapCenter sur site. 
---
= Restaurez la base de données SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez restaurer la base de données SQL Server à l'emplacement d'origine ou à l'autre emplacement.


NOTE: La restauration de fichiers uniques (SFR), la récupération des sauvegardes de journaux et la réamorçage des groupes de disponibilité ne sont pas pris en charge.

.Étapes
. Dans l'interface utilisateur BlueXP, cliquez sur *protection* > *sauvegarde et récupération* > *applications*.
. Dans le champ *Filtrer par*, sélectionnez le filtre *Type* et sélectionnez *SQL* dans la liste déroulante.
. Cliquez sur *Afficher les détails* pour afficher toutes les sauvegardes disponibles.
. Sélectionnez la sauvegarde et cliquez sur *Restaurer*.
. Dans la page Options de restauration, spécifiez l'emplacement où vous souhaitez restaurer les fichiers de base de données.
+
|===
| Si... | Procédez comme ça... 


 a| 
Vous souhaitez restaurer l'emplacement d'origine
 a| 
.. Sélectionnez *Restaurer à l'emplacement d'origine*.
.. Si le snapshot est en stockage d'archives, sélectionnez la priorité de restauration de vos données à partir du stockage d'archives.
.. Cliquez sur *Suivant*.




 a| 
Vous souhaitez effectuer une restauration temporaire dans un autre espace de stockage, puis copier les fichiers restaurés à leur emplacement d'origine
 a| 
.. Sélectionnez *Restaurer à l'emplacement d'origine*.
.. Si le snapshot est en stockage d'archives, sélectionnez la priorité de restauration de vos données à partir du stockage d'archives.
.. Sélectionnez *Modifier l'emplacement de stockage*.
+
Si vous sélectionnez *Modifier l'emplacement de stockage*, vous pouvez ajouter un suffixe au volume de destination. Si vous n'avez pas coché la case, *_restore* est ajouté par défaut au volume de destination.

.. Cliquez sur *Suivant*.
.. Dans la page mappage du stockage, spécifiez les détails de l'emplacement de stockage secondaire où les données restaurées à partir du magasin d'objets seront stockées temporairement.
.. Cliquez sur *Suivant*.




 a| 
Restauration dans un autre emplacement
 a| 
.. Sélectionnez *Restaurer à un autre emplacement*.
.. Si le snapshot est en stockage d'archives, sélectionnez la priorité de restauration de vos données à partir du stockage d'archives.
.. Cliquez sur *Suivant*.
.. Sur la page hôte de destination, sélectionnez un nom d'hôte, indiquez un nom de base de données (facultatif), sélectionnez une instance et spécifiez les chemins de restauration.
+

NOTE: L'extension de fichier fournie dans le chemin alternatif doit être identique à celle du fichier de base de données d'origine.

.. Cliquez sur *Suivant*.




 a| 
Vous souhaitez effectuer une restauration temporaire sur un autre stockage, puis copier les fichiers restaurés à l'autre emplacement
 a| 
.. Sélectionnez *Restaurer à un autre emplacement*.
.. Si le snapshot est en stockage d'archives, sélectionnez la priorité de restauration de vos données à partir du stockage d'archives.
.. Sélectionnez *Modifier l'emplacement de stockage*.
+
Si vous sélectionnez *Modifier l'emplacement de stockage*, vous pouvez ajouter un suffixe au volume de destination. Si vous n'avez pas coché la case, *_restore* est ajouté par défaut au volume de destination.

.. Cliquez sur *Suivant*.
.. Dans la page mappage du stockage, spécifiez les détails de l'emplacement de stockage secondaire où les données restaurées à partir du magasin d'objets seront stockées temporairement.
.. Cliquez sur *Suivant*.
.. Sur la page hôte de destination, sélectionnez un nom d'hôte, indiquez un nom de base de données (facultatif), sélectionnez une instance et spécifiez les chemins de restauration.
+

NOTE: L'extension de fichier fournie dans le chemin alternatif doit être identique à celle du fichier de base de données d'origine.

.. Cliquez sur *Suivant*.


|===
. Dans la case *pré-opérations*, sélectionnez l'une des options suivantes :
+
** Sélectionnez *Ecraser la base de données du même nom pendant la restauration* pour restaurer la base de données du même nom.
** Sélectionnez *conserver les paramètres de réplication de base de données SQL* pour restaurer la base de données et conserver les paramètres de réplication existants.


. Dans la section *Post-Operations*, pour spécifier l'état de la base de données pour la restauration de journaux transactionnels supplémentaires, sélectionnez l'une des options suivantes :
+
** Sélectionnez *opérationnel, mais indisponible* si vous restaurez maintenant toutes les sauvegardes nécessaires.
+
Il s'agit du comportement par défaut, qui laisse la base de données prête à l'emploi en revenant les transactions non validées. Vous ne pouvez pas restaurer d'autres journaux de transactions tant que vous n'avez pas créé de sauvegarde.

** Sélectionnez *non opérationnel, mais disponible* pour laisser la base de données non opérationnelle sans reprise des transactions non validées.
+
Des journaux de transactions supplémentaires peuvent être restaurés. Vous ne pouvez pas utiliser la base de données tant qu'elle n'a pas été restaurée.

** Sélectionnez *mode lecture seule et disponible* pour quitter la base de données en mode lecture seule.
+
Cette option annule les transactions non validées, mais enregistre les actions annulées dans un fichier de secours afin que les effets de récupération puissent être restaurés.

+
Si l'option Annuler le répertoire est activée, davantage de journaux de transactions sont restaurés. Si l'opération de restauration du journal de transactions échoue, les modifications peuvent être annulées. La documentation de SQL Server contient des informations supplémentaires.



. Cliquez sur *Suivant*.
. Vérifiez les détails et cliquez sur *Restaurer*.



NOTE: Si l'opération de restauration ne se termine pas, ne tentez pas de nouveau le processus de restauration tant que le moniteur de tâches n'indique pas que l'opération de restauration a échoué. Si vous essayez à nouveau le processus de restauration avant que le moniteur de tâches indique que l'opération de restauration a échoué, l'opération de restauration échouera à nouveau. Lorsque l'état du moniteur de tâches est « échec », vous pouvez réessayer le processus de restauration.
