---
sidebar: sidebar 
permalink: task-restore-hana-backup.html 
keywords: restore, mount application backups, SAP HANA database 
summary: Vous pouvez restaurer la base de données SAP HANA du cloud vers le serveur SnapCenter sur site. 
---
= Restaurez la base de données SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez restaurer la base de données SAP HANA sur n'importe quel hôte.

*Étapes*

. Dans l'interface utilisateur BlueXP, cliquez sur *protection* > *sauvegarde et récupération* > *applications*.
. Dans le champ *Filtrer par*, sélectionnez le filtre *Type* et dans la liste déroulante, sélectionnez *HANA*.
. Cliquez sur *View Details* correspondant à la base de données à restaurer et cliquez sur *Restore*.
. Dans la page Options de restauration, spécifiez l'une des options suivantes :
+
.. Pour l'environnement NAS, spécifiez le nom de domaine complet ou l'adresse IP de l'hôte vers lequel les volumes restaurés à partir du magasin d'objets doivent être exportés.
.. Pour l'environnement SAN, spécifiez les initiateurs de l'hôte sur lesquels les LUN des volumes restaurés à partir du magasin d'objets doivent être mappées.


. Si le snapshot est en stockage d'archives, sélectionnez la priorité de restauration de vos données à partir du stockage d'archives.
. S'il n'y a pas assez d'espace sur le stockage source ou si le stockage source est en panne, sélectionnez *Modifier l'emplacement de stockage*.
+
Si vous sélectionnez *Modifier l'emplacement de stockage*, vous pouvez ajouter un suffixe au volume de destination. Si vous n'avez pas coché la case, *_restore* est ajouté par défaut au volume de destination.

. Cliquez sur *Suivant*.
. Dans la page mappage du stockage, spécifiez les détails de l'emplacement de stockage secondaire dans lequel les données restaurées à partir du magasin d'objets seront stockées.
. Cliquez sur *Suivant*.
. Vérifiez les détails et cliquez sur *Restaurer*.


Cette opération n'effectue que l'exportation du stockage de la sauvegarde sélectionnée sur l'hôte donné. Vous devez monter manuellement le système de fichiers et faire apparaître la base de données. Après avoir utilisé le volume, l'administrateur du stockage peut le supprimer du cluster ONTAP.

Pour plus d'informations sur l'affichage de la base de données SAP HANA, reportez-vous à la section https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["Tr-4667 : automatisation des opérations de copie système et de clonage SAP HANA avec SnapCenter"^].
