---
sidebar: sidebar 
permalink: task-register-snapcenter-server.html 
keywords: SnapCenter Server, register 
summary: Procédez comme suit pour enregistrer le serveur SnapCenter. 
---
= Enregistrer SnapCenter Server pour la sauvegarde et la récupération BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Seul un utilisateur doté du rôle SnapCenterAdmin peut enregistrer l'hôte sur lequel SnapCenter Server 4.6 ou version ultérieure est exécuté. Vous pouvez enregistrer plusieurs hôtes SnapCenter Server dans la sauvegarde et la récupération BlueXP.

.Étapes
. Dans l'interface utilisateur BlueXP, cliquez sur *protection* > *sauvegarde et récupération* > *applications*.
. Dans la liste déroulante *Paramètres*, cliquez sur *serveurs SnapCenter*.
. Cliquez sur *Enregistrer le serveur SnapCenter*.
. Spécifiez les informations suivantes :
+
.. Dans le champ serveur SnapCenter, spécifiez le FQDN ou l'adresse IP de l'hôte du serveur SnapCenter.
.. Dans le champ Port, spécifiez le numéro de port sur lequel l'hôte du serveur SnapCenter est en cours d'exécution.
+
Assurez-vous que le port est ouvert pour que la communication ait lieu entre le serveur SnapCenter et BlueXP.

.. Dans le champ balises, spécifiez un nom de site, un nom de ville ou tout nom personnalisé avec lequel vous souhaitez marquer le serveur SnapCenter.
+
Les balises sont séparées par une virgule.

.. Dans le champ Nom d'utilisateur et Mot de passe, spécifiez les informations d'identification de l'utilisateur avec le rôle SnapCenterAdmin.


. Sélectionnez le connecteur dans la liste déroulante *Connector*.
. Cliquez sur *Enregistrer*.


.Une fois que vous avez terminé
Cliquez sur *Backup & Restore* > *applications* pour afficher toutes les applications protégées à l'aide de l'hôte serveur SnapCenter enregistré. Par défaut, les applications sont automatiquement découvertes tous les jours à minuit.

Les applications prises en charge et leurs configurations sont les suivantes :

* Base de données Oracle :
+
** Sauvegardes complètes (données + journal) créées avec au moins une planification quotidienne, hebdomadaire ou mensuelle
** SAN, NFS, VMDK-SAN, VMDK-NFS ET RDM


* Base de données Microsoft SQL Server :
+
** Autonome, basculement d'instances de cluster et groupes de disponibilité
** Sauvegardes complètes créées avec au moins un planning quotidien, hebdomadaire ou mensuel
** SAN, VMDK-SAN, VMDK-NFS ET RDM


* Base de données SAP HANA :
+
** Conteneur unique 1.x
** Conteneur de bases de données multiples 2.x
** Réplication système HANA (HSR)
+
Vous devez sauvegarder au moins une sauvegarde sur le site principal et sur les sites secondaires. Vous pouvez décider d'effectuer une défaillance pro-active ou un basculement différé vers le secondaire.

** Les ressources non-data volumes (NDV), telles que les binaires HANA, le volume des journaux d'archives HANA, le volume partagé HANA, etc


* MongoDB
* MySQL
* PostgreSQL


Les bases de données suivantes ne sont pas affichées :

* Bases de données qui n'ont pas de sauvegarde
* Les bases de données avec des règles à la demande ou à l'heure
* Bases de données Oracle résidant sur NVMe

