---
sidebar: sidebar 
permalink: task-add-sqlhost-install-plugin-sql.html 
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for SQL, SQL, database, host, install, add host, discover 
summary: Installez le plug-in SnapCenter pour SQL sur chacun des hôtes de base de données SQL. 
---
= Installez le plug-in SnapCenter pour SQL Server et ajoutez des hôtes de base de données
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez installer le plug-in SnapCenter pour SQL Server sur chacun des hôtes de base de données SQL, ajouter les hôtes de base de données, découvrir les instances de base de données et configurer les informations d'identification pour les instances de base de données.



== Installez le plug-in SnapCenter pour SQL Server

Vous devez télécharger le plug-in *snapcenter_service_Windows_host_plugin.exe*, puis exécuter la commande Silent installer pour installer le plug-in sur l'hôte de base de données.

.Avant de commencer
* Vous devez vous assurer que les conditions préalables suivantes sont remplies.
+
** .Net 4.7.2 est installé
** PowerShell 4.0 est installé
** Un espace disque minimum de 5 Go est disponible
** La taille minimale de la mémoire RAM est de 4 Go


* Vous devez exécuter l'API pour terminer l'intégration du client. Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Tenant%20Registration/createTenant[]


.Étapes
. Téléchargez le plug-in en exécutant l'API à partir de l'hôte du connecteur.
`docker exec -it cloudmanager_scs_cloud curl 'http://127.0.0.1/api/v2/pluginpackage/windows'`
+
L'emplacement du fichier est _/var/lib/docker/volumes/service-Manager-2_cloudmanager_scs_cloud_volume/_data/<agent_version>/sc-Windows-host-plugin/snapcenter_service_Windows_host_plugin.exe_.

. Copiez _snapcenter_service_Windows_host_plugin.exe_ depuis le connecteur vers chacun des hôtes de base de données du serveur MSSQL à l'aide de scp ou d'autres méthodes alternatives.
. Installez le plug-in.
'"C://<install_folder>/snapcenter_service_Windows_host_plugin.exe"/silent/debuglog "C://<install_folder>/HA_Suite_Silent_Install_SCSQL_FRESH.log" /log"C://install_folder/" BI_SNAPCENTER_PORT=8145 ISFeatureInstall=SCSQL'
. Copiez le certificat auto-signé depuis _/var/lib/docker/volumes/service-Manager-2_cloudmanager_scs_cloud_volume/_data/client/certificat/certificate.pem_ vers les hôtes de base de données du serveur MSSQL.
+
Vous pouvez également générer un certificat auto-signé ou un certificat signé par une autorité de certification si vous n'utilisez pas le certificat par défaut.

. Convertissez le certificat du format .pem au format .crt dans l'hôte du connecteur.
'openssl x509 -outform der -in certificate.pem -out certificate.crt'
. Double-cliquez sur le certificat pour l'ajouter au magasin *personnel* et *autorités de certification racines de confiance*.




== Ajoutez l'hôte de base de données SQL Server

Vous devez ajouter l'hôte de la base de données MSSQL à l'aide du nom de domaine complet de l'hôte.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/v1/hosts'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Host%20Management/AddHosts[]

Cette API crée un travail qui peut être suivi à partir de l'onglet *Job Monitor* de l'interface utilisateur BlueXP.



=== Paramètres

|===
| Nom | Type | Obligatoire 


 a| 
adr
 a| 
chaîne
 a| 
Vrai



 a| 
id_connecteur
 a| 
chaîne
 a| 
Vrai



 a| 
type_plugin
 a| 
chaîne
 a| 
Vrai



 a| 
méthode_installation
 a| 
chaîne
 a| 
Vrai



 a| 
plugin_port
 a| 
numéro
 a| 
Vrai



 a| 
nom d'utilisateur
 a| 
chaîne
 a| 
Vrai

|===


=== Réponse

Si l'API est exécutée avec succès, le code de réponse 202 s'affiche.

Exemple :

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== Afficher les hôtes de base de données SQL Server ajoutés

Vous pouvez exécuter cette API pour afficher tous les hôtes de base de données SQL Server ajoutés.

'OBTENEZ snapcenter.cloudmanager.cloud.netapp.com/api/v1/hosts'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Host%20Management/GetHosts[]



=== Réponse

Si l'API est exécutée avec succès, le code de réponse 200 s'affiche.

Exemple :

[listing]
----
{
  "num_records": 1,
    "total_records": 1,
    "records": [
        {
            "id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "addr": "scspa2722211001.rtp.openenglab.netapp.com",
            "status": "Running",
            "connector_id": "fBf8Iwbp4BscBfD02qBwWm6I03gGAesRclients",
            "plugin_port": 8145,
            "plugins": [
                {
                    "type": "mssql"
                }
            ],
            "os_type": "windows",
            "platform": "onprem",
            "username": "administrator",
            "operating_mode": "production"
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== Découvrir les instances de base de données

Vous pouvez exécuter cette API et entrer l'ID d'hôte pour découvrir toutes les instances MSSQL.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances/discovery'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/MSSQLInstancesDiscoveryRequest[]

Cette API crée un travail qui peut être suivi à partir de l'onglet *Job Monitor* de l'interface utilisateur BlueXP.



=== Paramètre

|===
| Nom | Type | Obligatoire 


 a| 
id_hôte
 a| 
chaîne
 a| 
Vrai

|===


=== Réponse

Si l'API est exécutée avec succès, le code de réponse 202 s'affiche.

Exemple :

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== Afficher les instances de base de données découvertes

Vous pouvez exécuter cette API pour afficher toutes les instances de base de données découvertes.

'OBTENEZ snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/GetMSSQLInstancesRequest[]



=== Réponse

Si l'API est exécutée avec succès, le code de réponse 200 s'affiche.

Exemple :

[listing]
----
{
    "num_records": 2,
    "total_records": 2,
    "records": [
        {
            "id": "953e66de-10d9-4fd9-bdf2-bf4b0eaabfd7",
            "name": "scspa2722211001\\NAMEDINSTANCE1",
            "host_id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "status": "Running",
            "auth_mode": 0,
            "version": "",
            "is_clustered": false,
            "is_credentials_configured": false,
            "protection_mode": ""
        },
        {
            "id": "18e1b586-4c89-45bd-99c8-26268def787c",
            "name": "scspa2722211001",
            "host_id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "status": "Stopped",
            "auth_mode": 0,
            "version": "",
            "is_clustered": false,
            "is_credentials_configured": false,
            "protection_mode": ""
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== Configurez les informations d'identification de l'instance de base de données

Vous pouvez exécuter cette API pour valider et définir les informations d'identification des instances de base de données.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql//api/mssql/credentials-configuration'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/ConfigureCredentialRequest[]

Cette API crée un travail qui peut être suivi à partir de l'onglet *Job Monitor* de l'interface utilisateur BlueXP.



=== Paramètre

|===
| Nom | Type | Obligatoire 


 a| 
id_hôte
 a| 
chaîne
 a| 
Vrai



 a| 
id_instance
 a| 
chaîne
 a| 
Vrai



 a| 
nom d'utilisateur
 a| 
chaîne
 a| 
Vrai



 a| 
mot de passe
 a| 
chaîne
 a| 
Vrai



 a| 
auth_mode
 a| 
chaîne
 a| 
Vrai

|===


=== Réponse

Si l'API est exécutée avec succès, le code de réponse 202 s'affiche.

Exemple :

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----