---
sidebar: sidebar 
permalink: task-create-policies-apps.html 
keywords: policy, create, pre-canned polices, custom policies, protection policies 
summary: 'Créez vos propres règles pour protéger l"application.' 
---
= Créez une politique de sauvegarde des applications avec la sauvegarde et la récupération BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez créer une politique pour sauvegarder les données de l’application dans le cloud avec la sauvegarde et la récupération BlueXP.

.Avant de commencer
* Si vous souhaitez transférer les sauvegardes du magasin d'objets vers le stockage d'archivage, vérifiez que vous utilisez la version ONTAP requise.
+
** Si vous utilisez Amazon Web Services, vous devez utiliser ONTAP 9.10.1 ou une version ultérieure
** Si vous utilisez Microsoft Azure, vous devez utiliser ONTAP 9.10.1 ou une version ultérieure
** Si vous utilisez Google Cloud, vous devez utiliser ONTAP 9.12.1 ou une version ultérieure
** Si vous utilisez StorageGRID, vous devez utiliser ONTAP 9.12.1 ou une version ultérieure


* Vous devez configurer le niveau d'accès d'archivage pour chaque fournisseur de cloud.


.Étapes
. Dans l'interface utilisateur BlueXP, cliquez sur *protection* > *sauvegarde et récupération* > *applications*.
. Dans la liste déroulante Paramètres, cliquez sur *stratégies* > *Créer une stratégie*.
. Dans la section Détails de la stratégie, spécifiez le nom de la stratégie.
. Dans la section Retention, sélectionnez l'un des types de rétention et indiquez le nombre de sauvegardes à conserver.
. Sélectionnez primaire ou secondaire comme source de stockage de sauvegarde.
. (Facultatif) si vous souhaitez transférer des sauvegardes du magasin d'objets vers le stockage d'archives après un certain nombre de jours pour l'optimisation des coûts, cochez la case *Tier backups to Archival*.
. Cliquez sur *Créer*.
+

NOTE: Vous ne pouvez pas modifier ou supprimer une stratégie associée à une application.


