---
sidebar: sidebar 
permalink: task-licensing-cloud-backup.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual 
summary: 'Vous pouvez acquérir une licence de sauvegarde et de restauration BlueXP via un abonnement au Marketplace annuel ou à l"utilisation auprès de votre fournisseur cloud ou en achetant une licence personnalisée auprès de NetApp. Une licence valide est requise pour activer la sauvegarde et la restauration BlueXP dans un environnement de travail, créer des sauvegardes de vos données de production et restaurer les données de sauvegarde sur un système de production.' 
---
= Configurez les licences pour la sauvegarde et la restauration BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez acheter une licence pour la sauvegarde et la restauration BlueXP via un abonnement de paiement à l'utilisation (PAYGO) ou un abonnement annuel à un marché auprès de votre fournisseur cloud, ou en achetant une licence BYOL (Bring Your Own License) de NetApp. Une licence valide est requise pour activer la sauvegarde et la restauration BlueXP dans un environnement de travail, créer des sauvegardes de vos données de production et restaurer les données de sauvegarde sur un système de production.

Quelques remarques avant de lire plus loin :

* Si vous avez déjà souscrit à l'abonnement PAYGO (paiement basé sur l'utilisation) dans le marché de votre fournisseur de cloud pour un système Cloud Volumes ONTAP, vous êtes également automatiquement abonné à la sauvegarde et à la restauration BlueXP. Vous n'aurez pas besoin de vous abonner à nouveau.
* BYOL (Bring Your Own License) est une licence flottante qui vous permet d'utiliser sur tous les systèmes associés à votre entreprise ou à votre compte BlueXP  BlueXP . Par conséquent, si vous disposez de suffisamment de capacité de sauvegarde sur une licence BYOL, vous n'avez pas besoin d'acheter une autre licence BYOL.
* Si vous utilisez une licence BYOL, il est également recommandé d'souscrire à un abonnement PAYGO. Si vous sauvegardez un nombre de données supérieur à celui autorisé par votre licence BYOL ou si la durée de votre licence expire, la sauvegarde se poursuit avec votre abonnement avec paiement basé sur l'utilisation - aucune interruption de service n'est constatée.
* La sauvegarde de données ONTAP sur site vers StorageGRID nécessite une licence BYOL, mais les besoins en espace de stockage du fournisseur cloud sont réduits.


link:concept-ontap-backup-to-cloud.html#cost["En savoir plus sur les coûts liés à l'utilisation de la sauvegarde et de la restauration BlueXP."]



== essai gratuit de 30 jours

Un essai gratuit de 30 jours de sauvegarde et de restauration BlueXP est disponible si vous vous inscrivez à un abonnement avec paiement à l'utilisation sur le marché de votre fournisseur cloud. L'essai gratuit commence au moment où vous vous abonnez à la liste Marketplace. Notez que si vous payez l'abonnement Marketplace lors du déploiement d'un système Cloud Volumes ONTAP, puis que vous démarrez votre essai gratuit de sauvegarde et de restauration BlueXP 10 jours plus tard, vous disposez de 20 jours pour utiliser l'essai gratuit.

À la fin de l'essai gratuit, vous serez automatiquement basculé vers l'abonnement PAYGO sans interruption. Si vous décidez de ne pas continuer à utiliser la sauvegarde et la restauration BlueXP, juste link:task-manage-backups-ontap.html#unregister-bluexp-backup-and-recovery-for-a-working-environment["Annulez l'enregistrement de la sauvegarde et de la restauration BlueXP depuis l'environnement de travail"] avant la fin de l'essai, vous ne serez pas facturé.



== Utilisez un abonnement PAYGO pour la sauvegarde et la restauration de BlueXP

Avec le paiement à l'utilisation, vous payez le coût du stockage objet pour votre fournisseur cloud et les coûts des licences de sauvegarde NetApp à l'heure sur un seul abonnement. Vous devez vous abonner même si vous disposez d'une période d'essai gratuite ou si vous apportez votre propre licence (BYOL) :

* L'abonnement garantit l'absence de perturbation du service après la fin de votre essai gratuit. À la fin de l'essai, vous serez facturé toutes les heures en fonction de la quantité de données que vous sauvegardez.
* Si vous sauvegardez plus de données que ce que votre licence BYOL ne le permet, les opérations de sauvegarde et de restauration des données se poursuivent sur votre abonnement avec paiement basé sur l'utilisation. Par exemple, si vous disposez d'une licence BYOL 10 Tio, toute la capacité au-delà de l'année 10 Tio est facturée via l'abonnement PAYGO.


Vous ne serez pas facturé à l'utilisation de votre abonnement au cours de l'essai gratuit ou si vous n'avez pas dépassé votre licence BYOL.

PAYGO propose plusieurs plans pour la sauvegarde et la restauration BlueXP :

* Un pack « Cloud Backup » vous permet de sauvegarder les données Cloud Volumes ONTAP et ONTAP sur site.
* Pack « CVO Professional » pour regrouper les fonctionnalités de sauvegarde et de restauration Cloud Volumes ONTAP et BlueXP. Cela inclut un nombre illimité de sauvegardes pour le système Cloud Volumes ONTAP utilisant la licence (la capacité de sauvegarde n'est pas comptée par rapport à la capacité sous licence). Cette option ne vous permet pas de sauvegarder les données ONTAP sur site.
+
Notez que cette option nécessite également un abonnement PAYGO pour la sauvegarde et la restauration, mais aucun frais n'est facturé pour les systèmes Cloud Volumes ONTAP éligibles.



https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["En savoir plus sur ces packs de licence basés sur la capacité"].

Utilisez les liens suivants pour vous abonner à la sauvegarde et à la restauration BlueXP depuis le Marketplace de votre fournisseur cloud :

ifdef::aws[]

* AWS : https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["Consultez l'offre BlueXP Marketplace pour obtenir des informations sur les tarifs"^].


endif::aws[]

ifdef::azure[]

* Azure : https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["Consultez l'offre BlueXP Marketplace pour obtenir des informations sur les tarifs"^].


endif::azure[]

ifdef::gcp[]

* Google Cloud : https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["Consultez l'offre BlueXP Marketplace pour obtenir des informations sur les tarifs"^].


endif::gcp[]



== Utilisez un contrat annuel

Payez chaque année pour la sauvegarde et la restauration BlueXP via un contrat annuel. Ils sont disponibles sur 1, 2 ou 3 ans.

Si vous avez un contrat annuel depuis un marché, toute la consommation de sauvegarde et de restauration BlueXP est facturée sur ce contrat. Vous ne pouvez pas combiner un contrat annuel de vente avec un contrat BYOL.

ifdef::aws[]

Lors de l'utilisation d'AWS, deux contrats annuels sont disponibles auprès du https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["Page AWS Marketplace"^] Pour les systèmes Cloud Volumes ONTAP et ONTAP sur site :

* Un plan de « sauvegarde dans le cloud » vous permet de sauvegarder les données Cloud Volumes ONTAP et les données ONTAP sur site.
+
Si vous souhaitez utiliser cette option, configurez votre abonnement à partir de la page Marketplace, puis https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["Associez l'abonnement à vos identifiants AWS"^]. Notez que vous devrez également payer pour vos systèmes Cloud Volumes ONTAP via cet abonnement annuel au contrat puisque vous ne pouvez attribuer qu'un seul abonnement actif à vos identifiants AWS dans BlueXP.

* Un plan « CVO Professional » qui vous permet de regrouper les fonctionnalités de sauvegarde et de restauration Cloud Volumes ONTAP et BlueXP. Cela inclut un nombre illimité de sauvegardes pour le système Cloud Volumes ONTAP utilisant la licence (la capacité de sauvegarde n'est pas comptée par rapport à la capacité sous licence). Cette option ne vous permet pas de sauvegarder les données ONTAP sur site.
+
Voir la https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Rubrique sur les licences Cloud Volumes ONTAP"^] pour en savoir plus sur cette option de licence.

+
Si vous souhaitez utiliser cette option, vous pouvez configurer le contrat annuel lorsque vous créez un environnement de travail Cloud Volumes ONTAP et BlueXP vous invite à vous abonner à AWS Marketplace.



endif::aws[]

ifdef::azure[]

Lors de l'utilisation d'Azure, deux contrats annuels sont disponibles sur le https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-bluexp["Page Azure Marketplace"^] Pour les systèmes Cloud Volumes ONTAP et ONTAP sur site :

* Un plan de « sauvegarde dans le cloud » vous permet de sauvegarder les données Cloud Volumes ONTAP et les données ONTAP sur site.
+
Si vous souhaitez utiliser cette option, configurez votre abonnement à partir de la page Marketplace, puis https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-azure-accounts.html#subscribe["Associez l'abonnement à vos identifiants Azure"^]. Notez que vous devrez également payer pour vos systèmes Cloud Volumes ONTAP à l'aide de cet abonnement annuel au contrat puisque vous ne pouvez attribuer qu'un seul abonnement actif à vos identifiants Azure dans BlueXP.

* Un plan « CVO Professional » qui vous permet de regrouper les fonctionnalités de sauvegarde et de restauration Cloud Volumes ONTAP et BlueXP. Cela inclut un nombre illimité de sauvegardes pour le système Cloud Volumes ONTAP utilisant la licence (la capacité de sauvegarde n'est pas comptée par rapport à la capacité sous licence). Cette option ne vous permet pas de sauvegarder les données ONTAP sur site.
+
Voir la https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Rubrique sur les licences Cloud Volumes ONTAP"^] pour en savoir plus sur cette option de licence.

+
Si vous souhaitez utiliser cette option, vous pouvez configurer le contrat annuel lorsque vous créez un environnement de travail Cloud Volumes ONTAP et BlueXP vous invite à vous abonner à Azure Marketplace.



endif::azure[]

ifdef::gcp[]

Si vous utilisez GCP, contactez votre ingénieur commercial NetApp pour acheter un contrat annuel. Le contrat est disponible en tant qu'offre privée dans Google Cloud Marketplace.

Une fois que NetApp a partagé l'offre privée avec vous, vous pouvez sélectionner le plan annuel lorsque vous vous abonnez à partir de Google Cloud Marketplace lors de l'activation de la sauvegarde et de la restauration BlueXP.

endif::gcp[]



== Utilisez une licence BYOL pour la sauvegarde et la restauration BlueXP

Modèle BYOL de 1, 2 ou 3 ans avec les licences Bring Your Own. Vous ne payez que les données que vous protégez, calculées par la capacité logique utilisée (_avant_ toutes les efficacités) des volumes ONTAP source qui sont sauvegardés. Cette capacité est également connue sous le nom de téraoctets frontaux (FETB).

La licence de sauvegarde et de restauration BYOL BlueXP  est une licence flottante qui permet de partager la capacité totale sur tous les systèmes associés à votre entreprise ou compte BlueXP . Pour les systèmes ONTAP, vous pouvez obtenir une estimation approximative de la capacité nécessaire en exécutant la commande CLI des `volume show -fields logical-used-by-afs` volumes à sauvegarder.

Si vous ne disposez pas d'une licence BYOL pour la sauvegarde et la restauration BlueXP, cliquez sur l'icône de chat dans le coin inférieur droit de BlueXP pour en acheter une.

Si vous ne souhaitez pas utiliser de licence basée sur des nœuds non attribuée à Cloud Volumes ONTAP, vous pouvez la convertir en licence de sauvegarde et de restauration BlueXP avec la même équivalence en dollar et la même date d'expiration. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["Cliquez ici pour plus d'informations"^].

Vous utilisez le portefeuille digital BlueXP pour gérer les licences BYOL. Vous pouvez ajouter de nouvelles licences, mettre à jour les licences existantes et afficher l'état des licences depuis le portefeuille digital BlueXP.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Découvrez comment ajouter des licences avec le portefeuille digital"^].
