---
sidebar: sidebar 
permalink: task-restore-cloud-native-sql-data.html 
keywords: restore, SQL database, BlueXP 
summary: Vous pouvez restaurer une base de données SQL du cloud vers le même hôte. 
---
= Restaurez la base de données Microsoft SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez restaurer la base de données Microsoft SQL Server sur le même hôte. Vous devez d'abord obtenir la liste des bases de données, puis restaurer la base de données.



== Afficher la liste des bases de données

Vous pouvez exécuter cette API pour afficher la liste des bases de données.

'OBTENEZ snapcenter.cloudmanager.cloud.netapp.com/api/mssql/databases'

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Databases/GetMSSQLDatabasesRequest[]



=== Réponse

Si l'API est exécutée avec succès, le code de réponse 200 s'affiche.

Exemple :

[listing]
----
{
    "num_records": 3,
    "total_records": 3,
    "records": [
        {
            "id": "348901e5-aeaa-419f-88b1-80240de3b1fe",
            "name": "DB4",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.078125,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "User",
            "recovery_mode": "Full"
        },
        {
            "id": "c79d33ab-7322-4ed6-92f5-51ad7a6944e0",
            "name": "DB5",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.078125,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "User",
            "recovery_mode": "Full"
        },
        {
            "id": "40d6f35a-f4fb-48bc-8e0a-0ac93ddf0888",
            "name": "model",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.015625,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "System",
            "recovery_mode": "Full"
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== Restaurez et restaurez la base de données MSSQL

Vous pouvez exécuter cette API pour restaurer la base de données MSSQL.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/databases/{id}/restore'

Où, _ID_ est l'ID de base de données MSSQL obtenu en exécutant l'API de base de données View. Pour plus d'informations, reportez-vous à la section <<Afficher la liste des bases de données>>.

Pour plus d'informations, se reporter à : https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Database%20Restore/RestoreMSSQLDatabaseRequest[]

Cette API crée un travail qui peut être suivi à partir de l'onglet *Job Monitor* de l'interface utilisateur BlueXP.



=== Paramètres

|===
| Nom | Type | Obligatoire 


 a| 
id_sauvegarde
 a| 
chaîne
 a| 
Vrai



 a| 
ecraser_database
 a| 
bool
 a| 
Vrai



 a| 
paramètres_de_réplication_de_conservation
 a| 
bool
 a| 
Faux



 a| 
recovery_mode
 a| 
chaîne

Les 3 chaînes prises en charge sont _Operational_, _nonoperationnel_ et _ReadOnly_.
 a| 
Vrai



 a| 
dossier_fichier_d'annulation
 a| 
chaîne
 a| 
Vrai



 a| 
restore_type
 a| 
chaîne
 a| 
Vrai

|===


=== Réponse

Si l'API est exécutée avec succès, le code de réponse 202 s'affiche.

Exemple :

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----