---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection' 
summary: Découvrez les nouveautés de la sauvegarde et de la restauration BlueXP. 
---
= Nouveautés de la sauvegarde et de la restauration BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de la sauvegarde et de la restauration BlueXP.



== 16 avril 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



=== Tableau de bord de volume amélioré (aperçu)

Le tableau de bord de volume se charge désormais en moins de 10 secondes, offrant ainsi une interface beaucoup plus rapide et efficace. Cette version préliminaire est disponible pour certains clients, leur offrant un aperçu de ces améliorations.



=== Améliorations de l'interface utilisateur

Cette version améliore votre expérience en simplifiant l'interface :

* La suppression de la colonne Aggregate des tables volumes, ainsi que des colonnes Snapshot Policy, Backup Policy et Replication Policy de la table Volume du tableau de bord V2, entraîne une mise en page plus rationalisée.
* L'exclusion des environnements de travail non activés dans la liste déroulante rend l'interface moins encombrée, la navigation plus efficace et le chargement plus rapide.
* Lorsque le tri dans la colonne balises est désactivé, vous pouvez toujours afficher les balises, en vous assurant que les informations importantes restent facilement accessibles.
* Le retrait des étiquettes sur les icônes de protection contribue à un aspect plus propre et réduit le temps de chargement.
* Pendant le processus d'activation de l'environnement de travail, une boîte de dialogue affiche une icône de chargement pour fournir des informations jusqu'à ce que le processus de découverte soit terminé, ce qui améliore la transparence et la confiance dans les opérations du système.




=== Prise en charge d'un magasin d'objets Wasabi tiers (aperçu)

La sauvegarde et la restauration BlueXP  étendent désormais sa prise en charge aux magasins d'objets tiers, en mettant l'accent sur Wasabi. Cette nouvelle fonctionnalité de préversion vous permet d'exploiter un magasin d'objets compatible S3 pour vos besoins de sauvegarde et de restauration.



==== Mise en route de Wasabi

Pour commencer à utiliser cette fonctionnalité, vous devez activer un indicateur dans l'interface utilisateur de BlueXP . Vous pouvez ensuite saisir les informations de connexion de votre magasin d'objets tiers et l'intégrer à vos workflows de sauvegarde et de restauration.



==== Limites du mode d'aperçu

Lorsque cette fonction est en aperçu, tenez compte des limitations suivantes :

* Le modèle BYOB (Bring Your Own Bucket) n'est pas pris en charge.
* L'activation de DataLock dans une stratégie n'est pas prise en charge.
* L'activation du mode archivage dans une règle n'est pas prise en charge.
* Seuls les environnements ONTAP sur site sont pris en charge.
* MetroCluster n'est pas pris en charge.
* Les options d'activation du chiffrement au niveau du compartiment ne sont pas prises en charge.


Au cours de cette présentation, nous vous encourageons à explorer cette nouvelle fonctionnalité et à nous faire part de vos commentaires sur l'intégration à des magasins d'objets tiers avant le déploiement complet des fonctionnalités.



== 17 mars 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



=== Exploration des snapshots SMB

Cette mise à jour de sauvegarde et de restauration BlueXP  a résolu un problème qui empêchait les clients de parcourir les snapshots locaux dans un environnement SMB.



=== Mise à jour de l'environnement AWS GovCloud

Cette mise à jour de sauvegarde et de restauration BlueXP  a résolu un problème qui empêchait l'interface utilisateur de se connecter à un environnement AWS GovCloud en raison d'erreurs de certificat TLS. Le problème a été résolu en utilisant le nom d'hôte du connecteur BlueXP  au lieu de l'adresse IP.



=== Limites de conservation des règles de sauvegarde

Jusqu'à présent, l'interface de sauvegarde et de restauration de BlueXP  limitait les sauvegardes à 999 copies, tandis que l'interface de ligne de commandes permettait d'en effectuer davantage. Vous pouvez désormais relier jusqu'à 4,000 volumes à une règle de sauvegarde et inclure 1,018 volumes non rattachés à une règle de sauvegarde. Cette mise à jour inclut des validations supplémentaires qui empêchent de dépasser ces limites.



=== Resynchronisation du cloud SnapMirror

Cette mise à jour garantit que la resynchronisation du cloud SnapMirror ne peut pas être démarrée à partir de la sauvegarde et de la restauration BlueXP  pour les versions ONTAP non prises en charge après la suppression d'une relation SnapMirror.



== 21 février 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



=== Indexation haute performance

La sauvegarde et la restauration BlueXP  proposent une fonction d'indexation mise à jour qui optimise l'indexation des données dans l'environnement de travail source. La nouvelle fonction d'indexation inclut des mises à jour de l'interface utilisateur, des performances améliorées de la méthode de recherche et de restauration des données, des mises à niveau vers des fonctionnalités de recherche globale et une meilleure évolutivité.

Voici une description des améliorations :

* *Consolidation des dossiers* : la version mise à jour regroupe les dossiers en utilisant des noms qui incluent des identificateurs spécifiques, rendant le processus d'indexation plus fluide.
* *Compactage du fichier parquet* : la version mise à jour réduit le nombre de fichiers utilisés pour indexer chaque volume, ce qui simplifie le processus et élimine le besoin d'une base de données supplémentaire.
* *Scale-out avec plus de sessions*: La nouvelle version ajoute plus de sessions pour gérer les tâches d'indexation, ce qui accélère le processus.
* *Prise en charge de plusieurs conteneurs d'index* : la nouvelle version utilise plusieurs conteneurs pour mieux gérer et distribuer les tâches d'indexation.
* *Flux de travail d'index partagé* : la nouvelle version divise le processus d'indexation en deux parties, améliorant ainsi l'efficacité.
* *Concurrence améliorée* : la nouvelle version permet de supprimer ou de déplacer des répertoires en même temps, accélérant ainsi le processus d'indexation.


.Qui bénéficie de cette fonctionnalité ?
La nouvelle fonction d'indexation est disponible pour tous les nouveaux clients.

.Comment activer l'indexation ?
Avant de pouvoir utiliser la méthode Search & Restore de restauration des données, vous devez activer l'« indexation » sur chaque environnement de travail source à partir duquel vous prévoyez de restaurer des volumes ou des fichiers. Cela permet au catalogue indexé de suivre chaque volume et chaque fichier de sauvegarde, ce qui accélère et optimise vos recherches.

Activez l'indexation sur l'environnement de travail source en sélectionnant l'option « Activer l'indexation » lorsque vous effectuez une recherche et une restauration.

Pour plus d'informations, reportez-vous à la documentation https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Comment restaurer des données ONTAP à l'aide de la fonction recherche et ampli ; Restaurer"].

.Échelle prise en charge
La nouvelle fonction d'indexation prend en charge les éléments suivants :

* Recherche globale efficace en moins de 3 minutes
* Jusqu'à 5 milliards de fichiers
* Jusqu'à 5000 volumes par cluster
* Jusqu'à 100 000 snapshots par volume
* La durée maximale pour l'indexation de la ligne de base est inférieure à 7 jours. La durée réelle varie en fonction de votre environnement.




=== Amélioration des performances de recherche globale

Cette version comprend également des améliorations des performances de recherche globale. Vous verrez maintenant des indicateurs de progression et des résultats de recherche plus détaillés, y compris le nombre de fichiers et le temps nécessaire à la recherche. Des conteneurs dédiés à la recherche et à l'indexation garantissent que les recherches globales sont effectuées en moins de cinq minutes.

Notez les considérations suivantes relatives à la recherche globale :

* Le nouvel index n'est pas effectué sur les instantanés libellés horaire.
* La nouvelle fonctionnalité d'indexation ne fonctionne que sur les copies Snapshot sur FlexVols et non sur les copies Snapshot sur FlexGroups.




== 22 novembre 2024

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



=== Modes de protection SnapLock Compliance et SnapLock Enterprise

La sauvegarde et la restauration BlueXP  peuvent désormais sauvegarder des volumes FlexVol et FlexGroup sur site configurés en mode de protection SnapLock Compliance ou SnapLock Enterprise. Pour cette prise en charge, vos clusters doivent exécuter ONTAP 9.14 ou une version ultérieure. La sauvegarde de volumes FlexVol à l'aide de SnapLock Enterprise mode est prise en charge depuis ONTAP version 9.11.1. Les versions antérieures de ONTAP ne prennent pas en charge la sauvegarde des volumes de protection SnapLock.

Consultez la liste complète des volumes pris en charge dans le https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Découvrez la sauvegarde et la restauration BlueXP"].



=== Indexation pour le processus de recherche et de restauration sur la page volumes

Avant de pouvoir utiliser la fonction de recherche et de restauration, vous devez activer « indexation » sur chaque environnement de travail source à partir duquel vous souhaitez restaurer les données du volume. Cela permet au catalogue indexé de suivre les fichiers de sauvegarde de chaque volume. La page volumes affiche désormais l'état de l'indexation :

* Indexé : les volumes ont été indexés.
* En cours
* Non indexé
* Indexation suspendue
* Erreur
* Non activé




== 27 septembre 2024

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



=== Prise en charge de Podman sur RHEL 8 ou 9 avec Browse and Restore

La sauvegarde et la restauration BlueXP  prennent désormais en charge les restaurations de fichiers et de dossiers sur Red Hat Enterprise Linux (RHEL) versions 8 et 9 à l'aide du moteur Podman. Ceci s'applique à la méthode de sauvegarde et de restauration BlueXP .

BlueXP  Connector version 3.9.40 prend en charge certaines versions de Red Hat Enterprise Linux versions 8 et 9 pour toute installation manuelle du logiciel Connector sur un hôte RHEL 8 ou 9, quel que soit l'emplacement en plus des systèmes d'exploitation mentionnés dans le https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["configuration requise pour l'hôte"^]. Ces nouvelles versions de RHEL nécessitent le moteur Podman au lieu du moteur Docker. Auparavant, la sauvegarde et la restauration BlueXP  présentaient deux limitations lors de l'utilisation du moteur Podman. Ces limitations ont été supprimées.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["En savoir plus sur la restauration des données ONTAP à partir de fichiers de sauvegarde"].



=== Une indexation plus rapide du catalogue améliore la recherche et la restauration

Cette version inclut un index de catalogue amélioré qui termine l'indexation de base beaucoup plus rapidement. L'indexation plus rapide vous permet d'utiliser la fonction de recherche et de restauration plus rapidement.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["En savoir plus sur la restauration des données ONTAP à partir de fichiers de sauvegarde"].



== 22 juillet 2024



=== Restaurez des volumes inférieurs à 1 Go

Avec cette version, vous pouvez désormais restaurer des volumes créés dans ONTAP de moins de 1 Go. La taille minimale du volume que vous pouvez créer à l'aide de ONTAP est de 20 Mo.



=== Conseils pour réduire les coûts liés à DataLock

La fonction DataLock protège vos fichiers de sauvegarde contre toute modification ou suppression pendant une période de temps spécifiée. Ceci est utile pour protéger vos fichiers contre les attaques par ransomware.

Pour plus de détails sur DataLock et des conseils sur la manière de réduire les coûts associés, reportez-vous https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["Paramètres de la règle de sauvegarde sur objet"] à la section .



=== Intégration AWS IAM Roles Anywhere

Le service Amazon Web Services (AWS) Identity and Access Management (IAM) Roles Anywhere vous permet d'utiliser des rôles IAM et des identifiants à court terme pour vos workloads _hors_ d'AWS pour accéder aux API AWS en toute sécurité, de la même manière que vous utilisez les rôles IAM pour les workloads _sur_ AWS. Lorsque vous utilisez l'infrastructure de clés privées IAM Roles Anywhere et les jetons AWS, vous n'avez pas besoin de clés d'accès AWS à long terme et de clés secrètes. Cela vous permet de faire pivoter les informations d'identification plus fréquemment, ce qui améliore la sécurité.

Avec cette version, la prise en charge du service AWS IAM Roles Anywhere est un aperçu technologique.

Reportez-vous à la https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Sauvegarde et restauration BlueXP, blog sur la version de juillet 2024"].



=== Restauration de dossier ou de répertoire FlexGroup maintenant disponible

Auparavant, les volumes FlexVol pouvaient être restaurés, mais vous ne pouviez pas restaurer les dossiers ou les répertoires FlexGroup. Avec ONTAP 9.15.1 p2, vous pouvez restaurer des dossiers FlexGroup à l'aide de l'option Parcourir et restaurer.

Avec cette version, la prise en charge de la restauration de dossiers FlexGroup est un aperçu technologique.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-browse-restore["Restaurez les dossiers et les fichiers à l'aide de Browse  Restore"] .

Pour plus de détails sur l'activation manuelle, reportez-vous https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Sauvegarde et restauration BlueXP, blog sur la version de juillet 2024"]à la section .



== 17 mai 2024



=== Limitations lors de l'utilisation de RHEL 8 et RHEL 9 pour votre connecteur sur site

BlueXP Connector version 3.9.40 prend en charge certaines versions de Red Hat Enterprise Linux versions 8 et 9 pour toute installation manuelle du logiciel Connector sur un hôte RHEL 8 ou 9, quel que soit l'emplacement en plus des systèmes d'exploitation mentionnés dans le https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["configuration requise pour l'hôte"^]. Ces nouvelles versions de RHEL nécessitent le moteur Podman au lieu du moteur Docker. À l'heure actuelle, la sauvegarde et la restauration BlueXP n'ont que deux limites lors de l'utilisation du moteur Podman.

Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html["Limites de la sauvegarde et de la restauration"] pour plus d'informations.

Les procédures suivantes incluent de nouvelles instructions Podman :

* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html["Redémarrez la sauvegarde et la restauration BlueXP"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["Restaurez les données de sauvegarde et de restauration BlueXP dans un site invisible"]




== 30 avril 2024



=== Activation ou désactivation des analyses de ransomware planifiées

Auparavant, vous pouviez activer ou désactiver les analyses par ransomware, mais pas les analyses planifiées.

Avec cette version, vous pouvez désormais activer ou désactiver les analyses par ransomware planifiées sur la dernière copie Snapshot en utilisant l'option de la page Paramètres avancés. Si vous l'activez, les analyses sont effectuées chaque semaine par défaut. Vous pouvez modifier ce planning en jours ou en semaines ou le désactiver, ce qui vous permet d'économiser des coûts.

Pour plus de détails, reportez-vous aux informations suivantes :

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Gérer les paramètres de sauvegarde"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Gérez les règles des volumes ONTAP"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["Paramètres de la règle de sauvegarde sur objet"]




== 04 avril 2024



=== Activation ou désactivation des analyses par ransomware

Auparavant, lorsque vous avez activé la détection des ransomwares dans une règle de sauvegarde, les analyses se sont automatiquement produites lors de la création de la première sauvegarde et de la restauration d'une sauvegarde. Dans les versions antérieures, le service a analysé toutes les copies Snapshot et vous ne pouviez pas désactiver les analyses.

Avec cette version, vous pouvez désormais activer ou désactiver les analyses anti-ransomware sur la dernière copie Snapshot à l'aide de l'option de la page Paramètres avancés. Si vous l'activez, les analyses sont effectuées chaque semaine par défaut.

Pour plus de détails, reportez-vous aux informations suivantes :

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Gérer les paramètres de sauvegarde"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Gérez les règles des volumes ONTAP"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["Paramètres de la règle de sauvegarde sur objet"]


ifdef::aws[]

Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Sauvegarde des données Cloud Volumes ONTAP dans Amazon S3"] et https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Sauvegarde des données Cloud Volumes ONTAP dans Azure Blob"].

endif::aws[]



== 12 mars 2024



=== Possibilité d'effectuer des restaurations rapides depuis les sauvegardes cloud vers des volumes ONTAP sur site

Vous pouvez désormais effectuer une _restauration rapide_ d'un volume depuis le stockage cloud vers un volume de destination ONTAP sur site. Auparavant, vous pouviez effectuer une restauration rapide uniquement sur un système Cloud Volumes ONTAP. La restauration rapide est idéale pour les reprises après incident où vous devez fournir un accès à un volume dès que possible. Une restauration rapide est bien plus rapide que la restauration d'un volume complet. Elle restaure les métadonnées depuis une copie Snapshot cloud vers un volume de destination ONTAP. La source peut provenir d'AWS S3, d'Azure Blob, de Google Cloud Services ou d'NetApp StorageGRID.

Le système de destination ONTAP sur site doit exécuter ONTAP version 9.14.1 ou ultérieure.

Pour ce faire, vous pouvez utiliser le processus Parcourir et restaurer, et non le processus Rechercher et restaurer.

Pour plus de détails, voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Restaurez les données ONTAP à partir de fichiers de sauvegarde"].



=== Possibilité de restaurer des fichiers et des dossiers à partir de copies Snapshot et de réplication

Auparavant, vous pouviez restaurer des fichiers et des dossiers uniquement à partir de copies de sauvegarde dans AWS, Azure et Google Cloud Services. Désormais, vous pouvez restaurer des fichiers et des dossiers à partir de copies Snapshot locales et de copies de réplication.

Vous pouvez exécuter cette fonction en utilisant le processus de recherche et de restauration, et non en utilisant le processus de navigation et de restauration.



== 01 février 2024



=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les machines virtuelles

* Prise en charge de la restauration de machines virtuelles vers un autre emplacement
* Prise en charge de l'annulation de la protection des datastores




== 15 décembre 2023



=== Rapports disponibles pour les copies Snapshot locales et les copies Snapshot de réplication

Auparavant, vous pouviez générer des rapports sur les copies de sauvegarde uniquement. Désormais, vous pouvez également créer des rapports sur les copies Snapshot locales et de réplication.

Avec ces rapports, vous pouvez effectuer les opérations suivantes :

* Assurez-vous que les données stratégiques sont protégées conformément à la politique de votre entreprise.
* Assurez-vous que les sauvegardes s'exécutaient correctement pour un groupe de volumes.
* Protégez vos données de production.


Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["Reporting sur la couverture de la protection des données"].



=== Balisage personnalisé disponible sur les volumes pour le tri et le filtrage

Vous pouvez désormais ajouter des balises personnalisées à des volumes à partir de ONTAP 9.13.1, afin de regrouper des volumes dans et entre des environnements de travail. Vous pouvez ainsi trier les volumes dans les pages de l'interface de sauvegarde et de restauration BlueXP et filtrer les rapports.



=== Sauvegardes du catalogue conservées pendant 30 jours

Auparavant, Catalog.zip sauvegardes étaient conservées pendant 7 jours. Maintenant, ils sont conservés pendant 30 jours.

Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["Restaurez les données de sauvegarde et de restauration BlueXP dans des sites invisibles"].



== 23 octobre 2023



=== 3-2-1 création de la stratégie de sauvegarde lors de l'activation de la sauvegarde

Auparavant, des règles personnalisées devaient être créées avant de lancer une copie Snapshot, une réplication ou une sauvegarde. Vous pouvez désormais créer une règle pendant le processus d'activation de la sauvegarde à l'aide de l'interface de sauvegarde et de restauration de BlueXP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["En savoir plus sur les stratégies"].



=== Prise en charge de la restauration rapide à la demande des volumes ONTAP

La sauvegarde et la restauration BlueXP permettent désormais d'effectuer une « restauration rapide » d'un volume depuis le stockage cloud vers un système Cloud Volumes ONTAP. La restauration rapide est idéale pour les reprises après incident où vous devez fournir un accès à un volume dès que possible. Une restauration rapide restaure les métadonnées du fichier de sauvegarde sur un volume au lieu de restaurer l'intégralité du fichier de sauvegarde.

Le système de destination Cloud Volumes ONTAP doit exécuter ONTAP version 9.13.0 ou ultérieure. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["En savoir plus sur la restauration des données"].

Le moniteur des tâches de sauvegarde et de restauration BlueXP affiche également des informations sur la progression des tâches de restauration rapide.



=== Prise en charge des tâches planifiées dans le moniteur des tâches

Le moniteur de tâches de sauvegarde et de restauration BlueXP a précédemment surveillé les tâches planifiées de sauvegarde et de restauration volume à magasin d'objets, mais pas les tâches Snapshot, de réplication, de sauvegarde et de restauration locales qui ont été planifiées via l'interface utilisateur ou l'API.

Le moniteur des tâches de sauvegarde et de restauration BlueXP inclut désormais des tâches planifiées pour les snapshots locaux, les réplications et les sauvegardes vers le stockage objet.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["En savoir plus sur le moniteur de tâches mis à jour"].



== 13 octobre 2023



=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (cloud natif)

* Base de données Microsoft SQL Server
+
** Prend en charge la sauvegarde, la restauration et la restauration des bases de données Microsoft SQL Server résidant sur Amazon FSX pour NetApp ONTAP
** Toutes les opérations ne sont prises en charge que par le biais des API REST.


* Systèmes SAP HANA
+
** Lors de l'actualisation du système, le montage et le démontage automatiques des volumes sont effectués à l'aide de workflows au lieu de scripts
** Prend en charge l'ajout, la suppression, la modification, la suppression, la maintenance, et mise à niveau de l'hôte du plug-in à l'aide de l'interface utilisateur






=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (hybride)

* Prend en charge le verrouillage des données et la protection contre les ransomware
* Prise en charge du déplacement des sauvegardes de StorageGRID vers le niveau d'archivage
* Prise en charge de la sauvegarde des données d'applications MongoDB, MySQL et PostgreSQL à partir des systèmes ONTAP sur site vers Amazon Web Services, Microsoft Azure, Google Cloud Platform et StorageGRID. Vous pouvez restaurer les données si nécessaire.




=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les machines virtuelles

* Prise en charge du modèle de déploiement de proxy de connecteur




== 11 septembre 2023



=== Gestion des nouvelles règles pour les données ONTAP

Cette version inclut la possibilité de créer des règles Snapshot personnalisées, des règles de réplication et des règles pour les sauvegardes vers un stockage objet pour les données ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["En savoir plus sur les stratégies"].



=== Prise en charge de la restauration de fichiers et de dossiers à partir de volumes dans le stockage objet ONTAP S3

Auparavant, vous ne pouviez pas restaurer de fichiers et de dossiers à l'aide de la fonction « Parcourir et restaurer » lorsque des volumes étaient sauvegardés sur le stockage objet ONTAP S3. Cette version supprime cette restriction.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["En savoir plus sur la restauration des données"].



=== Possibilité d'archiver immédiatement les données de sauvegarde au lieu d'effectuer une première écriture sur le stockage standard

Vous pouvez désormais envoyer immédiatement vos fichiers de sauvegarde dans le système de stockage d'archives au lieu d'écrire les données dans le stockage cloud standard. Cette fonctionnalité est particulièrement utile pour les utilisateurs qui ont rarement besoin d'accéder aux données issues de sauvegardes cloud ou qui remplacent un environnement de sauvegarde sur bande.



=== Prise en charge supplémentaire de la sauvegarde et de la restauration des volumes SnapLock

La sauvegarde et la restauration peuvent désormais sauvegarder des volumes FlexVol et FlexGroup configurés à l'aide du mode de protection SnapLock Enterprise. Pour cette prise en charge, vos clusters doivent exécuter ONTAP 9.14 ou une version ultérieure. La sauvegarde de volumes FlexVol à l'aide de SnapLock Enterprise mode est prise en charge depuis ONTAP version 9.11.1. Les versions antérieures de ONTAP ne prennent pas en charge la sauvegarde des volumes de protection SnapLock.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["En savoir plus sur la protection des données ONTAP"].



== 1er août 2023

[IMPORTANT]
====
* En raison d'une amélioration importante de la sécurité, votre connecteur nécessite désormais un accès Internet sortant vers un terminal supplémentaire afin de gérer les ressources de sauvegarde et de restauration au sein de votre environnement de cloud public. Si ce point final n'a pas été ajouté à la liste « autorisé » de votre pare-feu, une erreur s'affiche dans l'interface utilisateur à propos de « Service indisponible » ou de « Echec de la détermination de l'état du service » :
+
\https://netapp-cloud-account.auth0.com

* Vous devez désormais souscrire un abonnement PAYGO pour la sauvegarde et la restauration lorsque vous utilisez le pack « CVO Professional » qui vous permet de regrouper les fonctionnalités de sauvegarde et de restauration de Cloud Volumes ONTAP et BlueXP. Cela n'était pas nécessaire par le passé. Aucun frais n'est facturé sur l'abonnement à la sauvegarde et à la récupération pour les systèmes Cloud Volumes ONTAP éligibles, mais il est requis lors de la configuration de la sauvegarde sur les nouveaux volumes.


====


=== La prise en charge a été ajoutée à la sauvegarde des volumes dans des compartiments sur les systèmes ONTAP configurés avec S3

Vous pouvez désormais utiliser un système ONTAP configuré pour simple Storage Service (S3) pour sauvegarder des volumes dans le stockage objet. Ceci est pris en charge à la fois pour les systèmes ONTAP sur site et les systèmes Cloud Volumes ONTAP. Cette configuration est prise en charge dans les déploiements cloud et sur des sites sans accès à Internet (déploiement en mode « privé »).

ifdef::aws[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["En savoir plus >>"].

endif::aws[]



=== Vous pouvez désormais inclure les snapshots existants d'un volume protégé dans vos fichiers de sauvegarde

Auparavant, vous aviez la possibilité d'inclure des copies Snapshot existantes à partir de volumes de lecture-écriture dans votre fichier de sauvegarde initial vers le stockage objet (au lieu de commencer avec la copie Snapshot la plus récente). Les copies Snapshot existantes de volumes en lecture seule (volumes de protection des données) n'ont pas été incluses dans le fichier de sauvegarde. Vous pouvez désormais choisir d'inclure d'anciennes copies Snapshot dans le fichier de sauvegarde des volumes « DP ».

L'assistant de sauvegarde affiche une invite à la fin des étapes de sauvegarde, dans laquelle vous pouvez sélectionner ces « instantanés existants ».



=== La sauvegarde et la restauration BlueXP ne prennent plus en charge la sauvegarde automatique des volumes ajoutés à l'avenir

Vous pouviez auparavant cocher une case dans l'assistant de sauvegarde pour appliquer la règle de sauvegarde sélectionnée à tous les futurs volumes ajoutés au cluster. Cette fonction a été supprimée en fonction des commentaires de l'utilisateur et du manque d'utilisation de cette fonction. Vous devez activer manuellement les sauvegardes de tout nouveau volume ajouté au cluster.



=== La page surveillance des travaux a été mise à jour avec de nouvelles fonctionnalités

La page surveillance des tâches fournit maintenant plus d'informations sur la stratégie de sauvegarde 3-2-1. Le service fournit également des notifications d'alerte supplémentaires relatives à la stratégie de sauvegarde.

Le filtre Type « cycle de vie de sauvegarde » a été renommé « conservation ». Utilisez ce filtre pour suivre le cycle de vie des sauvegardes et identifier l'expiration de toutes les copies de sauvegarde. Le type de tâche « conservation » capture toutes les tâches de suppression de Snapshot initiées sur un volume protégé par la sauvegarde et la restauration BlueXP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["En savoir plus sur le moniteur de tâches mis à jour"].



== 6 juillet 2023



=== La sauvegarde et la restauration BlueXP permettent désormais de planifier et de créer des copies Snapshot et des volumes répliqués

La sauvegarde et la restauration BlueXP vous permettent désormais d'implémenter une stratégie 3-2-1 où vous pouvez disposer de 3 copies de vos données source sur 2 systèmes de stockage différents avec une copie dans le cloud. Après l'activation, vous aurez :

* Copie Snapshot du volume sur le système source
* Volume répliqué sur un autre système de stockage
* Sauvegarde du volume dans le stockage objet


https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html["En savoir plus sur les nouvelles fonctionnalités complètes de sauvegarde et de restauration"].

Cette nouvelle fonctionnalité s'applique également aux opérations de restauration. Vous pouvez effectuer des opérations de restauration à partir d'une copie Snapshot, d'un volume répliqué ou d'un fichier de sauvegarde dans le cloud. Cela vous donne la flexibilité de choisir le fichier de sauvegarde qui répond à vos besoins en restauration, notamment le coût et la vitesse de restauration.

Notez que cette nouvelle fonctionnalité et interface utilisateur ne sont prises en charge que pour les clusters exécutant ONTAP 9.8 ou version ultérieure. Si votre cluster dispose d'une version antérieure du logiciel, vous pouvez continuer à utiliser la version précédente de BlueXP Backup and Recovery. Toutefois, nous vous recommandons de passer à une version prise en charge de ONTAP afin d'obtenir les dernières fonctionnalités. Pour continuer à utiliser l'ancienne version du logiciel, procédez comme suit :

. Dans l'onglet *volumes*, sélectionnez *Paramètres de sauvegarde*.
. Sur la page _Backup Settings_, cliquez sur le bouton radio *Afficher la version précédente de sauvegarde et de restauration BlueXP*.
+
Vous pouvez ensuite gérer vos anciens clusters à l'aide de la version précédente du logiciel.





=== Possibilité de créer votre conteneur de stockage pour la sauvegarde vers un stockage objet

Lorsque vous créez des fichiers de sauvegarde dans un stockage objet, par défaut, le service de sauvegarde et de restauration crée les compartiments dans le stockage objet pour vous. Vous pouvez créer les compartiments vous-même si vous souhaitez utiliser un certain nom ou attribuer des propriétés spéciales. Si vous souhaitez créer votre propre compartiment, vous devez le créer avant de lancer l'assistant d'activation. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["Découvrez comment créer vos compartiments de stockage objet"].

Cette fonctionnalité n'est actuellement pas prise en charge lors de la création de fichiers de sauvegarde sur des systèmes StorageGRID.



== 04 juillet 2023



=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (cloud natif)

* Systèmes SAP HANA
+
** Prend en charge la connexion et la restauration des copies de volumes non-données et de volumes globaux non-données disposant d'une protection secondaire Azure NetApp Files


* Les bases de données Oracle
+
** Prend en charge la restauration des bases de données Oracle sur Azure NetApp Files vers un autre emplacement
** Prise en charge du catalogage Oracle Recovery Manager (RMAN) des sauvegardes de bases de données Oracle sur Azure NetApp Files
** Permet de placer l'hôte de base de données en mode de maintenance pour effectuer des tâches de maintenance






=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (hybride)

* Prend en charge la restauration dans un autre emplacement
* Vous permet de monter des sauvegardes de bases de données Oracle
* Prise en charge du déplacement des sauvegardes de GCP vers le Tier d'archivage




=== Améliorations de la sauvegarde et de la restauration BlueXP pour les machines virtuelles (hybride)

* Prend en charge la protection des types de datastores NFS et VMFS
* Vous permet d'annuler l'enregistrement du plug-in SnapCenter pour l'hôte VMware vSphere
* Prend en charge l'actualisation et la découverte des derniers datastores et sauvegardes




== 5 juin 2023



=== Les volumes FlexGroup peuvent être sauvegardés et protégés à l'aide de DataLock et de la protection contre les ransomware

Les règles de sauvegarde pour les volumes FlexGroup peuvent désormais utiliser DataLock et la protection contre les ransomware lorsque le cluster exécute ONTAP 9.13.1 ou une version ultérieure.



=== Nouvelles fonctionnalités de reporting

Un onglet Reports permet désormais de générer un rapport Backup Inventory, qui inclut toutes les sauvegardes d'un compte, d'un environnement de travail ou d'un inventaire SVM spécifique. Vous pouvez également créer un rapport sur l'activité des tâches de protection des données, qui fournit des informations sur les opérations Snapshot, de sauvegarde, de clonage et de restauration, afin de vous aider à contrôler les contrats de niveau de service. Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["Reporting sur la couverture de la protection des données"].



=== Améliorations du moniteur de tâches

Vous pouvez maintenant passer en revue _backup Lifecycle_ en tant que Type de tâche sur la page Job Monitor, ce qui vous permet de suivre l'intégralité du cycle de vie de la sauvegarde. Vous pouvez également afficher les détails de toutes les opérations sur la chronologie BlueXP. Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Surveiller l'état des tâches de sauvegarde et de restauration"].



=== Alerte de notification supplémentaire pour les étiquettes de stratégie non concordants

Une nouvelle alerte de sauvegarde a été ajoutée : « les fichiers de sauvegarde n'ont pas été créés, car les étiquettes des règles Snapshot ne correspondent pas ». Si le _label_ défini dans une règle de sauvegarde n'a pas de _label_ correspondant dans la stratégie Snapshot, aucun fichier de sauvegarde n'est créé. Vous devez utiliser System Manager ou l'interface de ligne de commandes de ONTAP pour ajouter l'étiquette manquante à la règle de copie Snapshot du volume.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["Examinez toutes les alertes que les solutions de sauvegarde et de restauration BlueXP peuvent envoyer"].



=== Sauvegarde automatique des fichiers de sauvegarde et de restauration BlueXP stratégiques dans les sites invisibles

Lorsque vous utilisez la sauvegarde et la restauration BlueXP dans un site sans accès à Internet, connu sous le nom de déploiement en « mode privé », les informations de sauvegarde et de restauration BlueXP sont stockées uniquement sur le système de connecteurs local. Cette nouvelle fonctionnalité sauvegarde automatiquement les données stratégiques de sauvegarde et de restauration BlueXP dans un compartiment du système StorageGRID connecté. Vous pouvez ainsi restaurer ces données sur un nouveau connecteur, si nécessaire. https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["En savoir plus >>"]



== 8 mai 2023



=== Les opérations de restauration au niveau des dossiers sont désormais prises en charge à partir du stockage d'archives et des sauvegardes verrouillées

Si un fichier de sauvegarde a été configuré avec la protection DataLock & ransomware, ou si le fichier de sauvegarde réside dans un stockage d'archivage, les opérations de restauration au niveau des dossiers sont prises en charge si le cluster exécute ONTAP 9.13.1 ou une version ultérieure.



=== Les clés gérées par le client entre régions et projets sont prises en charge lors de la sauvegarde de volumes dans Google Cloud

Vous pouvez désormais choisir un compartiment qui se trouve dans un projet différent de celui des clés de chiffrement gérées par le client (CMEK).

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["En savoir plus sur la configuration de vos propres clés de chiffrement gérées par le client"].

endif::gcp[]



=== Les régions AWS Chine sont désormais prises en charge pour les fichiers de sauvegarde

Les régions AWS China Beijing (cn-North-1) et Ningxia (cn-Northwest-1) sont désormais prises en charge en tant que destinations pour vos fichiers de sauvegarde si le cluster exécute ONTAP 9.12.1 ou une version ultérieure.

Notez que les règles IAM attribuées à BlueXP Connector doivent modifier le nom de ressource AWS « arn » sous toutes les sections _Resource_ de « aws » à « aws-cn », par exemple « arn:aws-cn:s3:::netapp-backup-* ».

ifdef::aws[]

Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Sauvegarde des données Cloud Volumes ONTAP dans Amazon S3"] et https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["Sauvegarde des données ONTAP sur site dans Amazon S3"] pour plus de détails.

endif::aws[]



=== Améliorations apportées au moniteur de tâches

Les tâches lancées par le système, telles que les opérations de sauvegarde en cours, sont désormais disponibles dans l'onglet *surveillance des tâches* pour les systèmes ONTAP sur site exécutant ONTAP 9.13.1 ou version ultérieure. Les versions précédentes de ONTAP affichent uniquement les travaux initiés par l'utilisateur.



== 14 avril 2023



=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (cloud natif)

* Les bases de données SAP HANA
+
** Prend en charge l'actualisation du système basée sur des scripts
** Prend en charge la restauration de fichiers uniques Snapshot si la sauvegarde Azure NetApp Files est configurée
** Prend en charge la mise à niveau du plug-in


* Les bases de données Oracle
+
** Améliorations apportées au déploiement des plug-ins en simplifiant la configuration utilisateur sudo non-root
** Prend en charge la mise à niveau du plug-in
** Prend en charge la détection automatique et la protection pilotée par des règles des bases de données Oracle sur Azure NetApp Files
** Prend en charge la restauration de la base de données Oracle à l'emplacement d'origine avec récupération granulaire






=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (hybride)

* La sauvegarde et la restauration BlueXP pour les applications (hybrides) sont pilotées par le plan de contrôle SaaS
* API REST hybrides modifiées pour l'alignement avec les API cloud natives - effectué.
* Prend en charge la notification par e-mail




== 4 avril 2023



=== Possibilité de sauvegarder des données dans le cloud à partir des systèmes Cloud Volumes ONTAP en mode « restreint »

Vous pouvez désormais sauvegarder les données à partir de systèmes Cloud Volumes ONTAP installés dans les régions commerciales AWS, Azure et GCP en « mode restreint ». Pour cela, vous devez d'abord installer le connecteur dans la région commerciale « restreinte ». https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["En savoir plus sur les modes de déploiement BlueXP"^].

ifdef::aws[]

Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Sauvegarde des données Cloud Volumes ONTAP dans Amazon S3"]

endif::aws[]

ifdef::azure[]

Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Sauvegarde des données Cloud Volumes ONTAP dans Azure Blob"].

endif::azure[]



=== Possibilité de sauvegarder vos volumes ONTAP sur site vers ONTAP S3 à l'aide de l'API

Les nouvelles fonctionnalités des API vous permettent de sauvegarder vos copies Snapshot de volume vers ONTAP S3 à l'aide de la sauvegarde et de la restauration BlueXP. Cette fonctionnalité est disponible uniquement pour les systèmes ONTAP sur site à l'heure actuelle. Pour obtenir des instructions détaillées, consultez le blog https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["Intégration avec ONTAP S3 en tant que destination"^].



=== Possibilité de modifier l'aspect redondance de zone de votre compte de stockage Azure de LRS à ZRS

Lors de la création de sauvegardes à partir de systèmes Cloud Volumes ONTAP vers du stockage Azure, par défaut, la sauvegarde et la restauration BlueXP provisionne le conteneur Blob avec une redondance locale (LRS) pour l'optimisation des coûts. Vous pouvez définir ce paramètre sur redondance de zone (ZRS) si vous souhaitez que vos données soient répliquées entre différentes zones. Consultez les instructions Microsoft pour https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["modification de la façon dont votre compte de stockage est répliqué"^].



=== Améliorations apportées au moniteur de tâches

* Les opérations de sauvegarde et de restauration initiées par l'utilisateur à partir de l'interface utilisateur et de l'API de sauvegarde et de restauration BlueXP, ainsi que les tâches initiées par le système, telles que les opérations de sauvegarde en continu, sont désormais disponibles dans l'onglet *surveillance des tâches* pour les systèmes Cloud Volumes ONTAP exécutant ONTAP 9.13.0 ou version ultérieure. Les versions précédentes de ONTAP affichent uniquement les travaux initiés par l'utilisateur.
* En plus de pouvoir télécharger un fichier CSV pour créer des rapports sur tous les travaux, vous pouvez désormais télécharger un fichier JSON pour un seul travail et voir ses détails. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["En savoir plus >>"].
* Deux nouvelles alertes de tâche de sauvegarde ont été ajoutées : « échec de tâche planifiée » et « la tâche de restauration est terminée mais avec des avertissements ». https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["Examinez toutes les alertes que les solutions de sauvegarde et de restauration BlueXP peuvent envoyer"].




== 9 mars 2023



=== Les opérations de restauration au niveau des dossiers incluent désormais tous les sous-dossiers et fichiers

Dans le passé, lorsque vous avez restauré un dossier, seuls les fichiers de ce dossier ont été restaurés : aucun sous-dossier, ni fichier dans des sous-dossiers, n'a été restauré. Maintenant, si vous utilisez ONTAP 9.13.0 ou une version ultérieure, tous les sous-dossiers et fichiers du dossier sélectionné sont restaurés. Cela permet d'économiser beaucoup de temps et d'argent dans les cas où vous avez plusieurs dossiers imbriqués dans un dossier de premier niveau.



=== Possibilité de sauvegarder les données des systèmes Cloud Volumes ONTAP sur des sites avec une connectivité sortante limitée

Vous pouvez désormais sauvegarder les données à partir de systèmes Cloud Volumes ONTAP installés dans les régions commerciales AWS et Azure vers Amazon S3 ou Azure Blob. Pour ce faire, vous devez installer le connecteur en « mode restreint » sur un hôte Linux de la région commerciale, et déployer le système Cloud Volumes ONTAP là aussi.

ifdef::aws[]

Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Sauvegarde des données Cloud Volumes ONTAP dans Amazon S3"].

endif::aws[]

ifdef::azure[]

Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Sauvegarde des données Cloud Volumes ONTAP dans Azure Blob"].

endif::azure[]



=== Plusieurs améliorations apportées au moniteur de tâches

* La page surveillance des tâches a ajouté un filtrage avancé qui vous permet de rechercher des tâches de sauvegarde et de restauration par heure, charge de travail (volumes, applications ou machines virtuelles), type de tâche, état, environnement de travail et machine virtuelle de stockage. Vous pouvez également entrer du texte libre pour rechercher n'importe quelle ressource, par exemple, "application_3".  https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["Voir comment utiliser les filtres avancés"].
* Les opérations de sauvegarde et de restauration initiées par l'utilisateur à partir de l'interface utilisateur et de l'API de sauvegarde et de restauration BlueXP, ainsi que les tâches initiées par le système, telles que les opérations de sauvegarde en continu, sont désormais disponibles dans l'onglet *surveillance des tâches* pour les systèmes Cloud Volumes ONTAP exécutant ONTAP 9.13.0 ou version ultérieure. Les versions antérieures des systèmes Cloud Volumes ONTAP et les systèmes ONTAP sur site n'affichent actuellement que les tâches initiées par l'utilisateur.




== 6 février 2023



=== La possibilité de déplacer d'anciens fichiers de sauvegarde vers le stockage d'archivage Azure à partir des systèmes StorageGRID

Vous pouvez désormais transférer les anciens fichiers de sauvegarde des systèmes StorageGRID vers le stockage d'archivage dans Azure. Cela vous permet de libérer de l'espace sur vos systèmes StorageGRID et de réaliser des économies en utilisant une solution de stockage bon marché pour les anciens fichiers de sauvegarde.

Cette fonctionnalité est disponible si votre cluster sur site utilise ONTAP 9.12.1 ou version ultérieure et que votre système StorageGRID utilise 11.4 ou version ultérieure. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["En savoir plus"^].



=== Il est possible de configurer le verrouillage des données et la protection contre les attaques par ransomware pour les fichiers de sauvegarde dans Azure Blob

DataLock et ransomware protection sont désormais pris en charge pour les fichiers de sauvegarde stockés dans Azure Blob. Si votre système Cloud Volumes ONTAP ou ONTAP sur site exécute ONTAP 9.12.1 ou une version ultérieure, vous pouvez maintenant verrouiller vos fichiers de sauvegarde et les analyser pour détecter un éventuel ransomware. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Découvrez comment protéger vos sauvegardes avec DataLock et protection contre les attaques par ransomware"^].



=== Amélioration de la sauvegarde et de la restauration d'un volume FlexGroup

* Vous pouvez désormais choisir plusieurs agrégats lors de la restauration d'un volume FlexGroup. Dans la dernière version, vous ne pouvez sélectionner qu'un seul agrégat.
* La restauration de volume FlexGroup est désormais prise en charge sur les systèmes Cloud Volumes ONTAP. Dans la dernière version, vous pouviez uniquement restaurer vos données vers des systèmes ONTAP sur site.




=== Les systèmes Cloud Volumes ONTAP peuvent transférer d'anciennes sauvegardes vers le stockage d'archivage Google

Les fichiers de sauvegarde sont initialement créés dans la classe de stockage Google Standard. Vous pouvez désormais utiliser la sauvegarde et la restauration BlueXP pour hiérarchiser les sauvegardes plus anciennes sur le stockage Google Archive afin de mieux optimiser les coûts. La dernière version ne prend en charge que cette fonctionnalité avec des clusters ONTAP sur site. Désormais, les systèmes Cloud Volumes ONTAP déployés dans Google Cloud sont pris en charge.



=== Les opérations de restauration de volume permettent désormais de sélectionner la SVM où vous souhaitez restaurer les données de volume

Désormais, vous restaurez des données de volume sur d'autres machines virtuelles de stockage dans vos clusters ONTAP. Auparavant, il n'était pas possible de choisir la machine virtuelle de stockage.



=== Prise en charge améliorée des volumes dans les configurations MetroCluster

Avec ONTAP 9.12.1 GA ou supérieur, la sauvegarde est désormais prise en charge lorsqu'elle est connectée au système primaire dans une configuration MetroCluster. L'intégralité de la configuration de sauvegarde est transférée vers le système secondaire pour que les sauvegardes vers le cloud puissent se poursuivre automatiquement après le basculement.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["Voir limites de sauvegarde pour plus d'informations"].



== 9 janvier 2023



=== La possibilité de déplacer d'anciens fichiers de sauvegarde vers le stockage d'archivage AWS S3 à partir des systèmes StorageGRID

Vous pouvez désormais transférer d'anciens fichiers de sauvegarde des systèmes StorageGRID vers le stockage d'archivage dans AWS S3. Cela vous permet de libérer de l'espace sur vos systèmes StorageGRID et de réaliser des économies en utilisant une solution de stockage bon marché pour les anciens fichiers de sauvegarde. Vous pouvez choisir de transférer les sauvegardes vers un stockage AWS S3 Glacier ou S3 Glacier Deep Archive.

Cette fonctionnalité est disponible si votre cluster sur site utilise ONTAP 9.12.1 ou version ultérieure et que votre système StorageGRID utilise 11.3 ou version ultérieure. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["En savoir plus"].



=== Possibilité de sélectionner vos propres clés gérées par le client pour le chiffrement des données sur Google Cloud

Lorsque vous sauvegardez les données de vos systèmes ONTAP dans Google Cloud Storage, vous pouvez maintenant sélectionner vos propres clés gérées par le client pour le chiffrement des données dans l'assistant d'activation au lieu d'utiliser les clés de chiffrement gérées par Google par défaut. Il vous suffit de configurer d'abord vos clés de chiffrement gérées par le client dans Google, puis de saisir les informations lorsque vous activez la sauvegarde et la restauration BlueXP.



=== Le rôle d'administrateur du stockage n'est plus nécessaire pour créer des sauvegardes dans Google Cloud Storage

Dans les versions précédentes, le rôle d'administrateur du stockage était requis pour le compte de service permettant à la sauvegarde et à la restauration BlueXP d'accéder aux compartiments de stockage Google Cloud. Vous pouvez désormais créer un rôle personnalisé avec un ensemble réduit d'autorisations à attribuer au compte de service.

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["Découvrez comment préparer votre Google Cloud Storage pour les sauvegardes"].

endif::gcp[]



=== L'assistance a été ajoutée pour restaurer des données à l'aide de la fonction de recherche et de restauration sur des sites sans accès à Internet

Si vous sauvegardez des données à partir d'un cluster ONTAP sur site vers StorageGRID sur un site sans accès Internet, également connu sous le nom de site sombre ou hors ligne, vous pouvez maintenant utiliser l'option de recherche et de restauration pour restaurer les données si nécessaire. Cette fonctionnalité requiert le déploiement du connecteur BlueXP (version 3.9.25 ou ultérieure) sur le site hors ligne.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["Voir comment restaurer les données ONTAP à l'aide de la fonction Rechercher et AMP ; Restaurer"].
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Découvrez comment installer le connecteur dans votre site hors ligne"].



=== Possibilité de télécharger la page des résultats de la surveillance des travaux sous forme de rapport .csv

Après avoir filtré la page surveillance des travaux pour afficher les travaux et les actions qui vous intéressent, vous pouvez maintenant générer et télécharger un fichier .csv de ces données. Vous pouvez ensuite analyser les informations ou envoyer le rapport à d'autres personnes de votre organisation. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["Découvrez comment générer un rapport de surveillance des travaux"].



== 19 décembre 2022



=== Améliorations de Cloud Backup pour les applications

* Les bases de données SAP HANA
+
** Prise en charge de la sauvegarde et de la restauration basées sur des règles des bases de données SAP HANA résidant sur Azure NetApp Files
** Prend en charge les règles personnalisées


* Les bases de données Oracle
+
** Ajoutez des hôtes et déployez automatiquement le plug-in
** Prend en charge les règles personnalisées
** Prise en charge de la sauvegarde, de la restauration et du clonage des bases de données Oracle résidant sur Cloud Volumes ONTAP basés sur des règles
** Prend en charge la sauvegarde et la restauration basées sur des règles des bases de données Oracle résidant sur Amazon FSX pour NetApp ONTAP
** Prend en charge la restauration des bases de données Oracle à l'aide de la méthode de connexion et de copie
** Prend en charge Oracle 21c
** Prend en charge le clonage d'une base de données Oracle cloud native






=== Améliorations de Cloud Backup pour les machines virtuelles

* Ordinateurs virtuels
+
** Sauvegarder des machines virtuelles à partir d'un stockage secondaire sur site
** Prend en charge les règles personnalisées
** Prise en charge de Google Cloud Platform (GCP) pour sauvegarder un ou plusieurs datastores
** Prise en charge d'un stockage cloud à faible coût comme Glacier, Deep Glacier et Azure Archive






== 6 décembre 2022



=== Modifications du point de terminaison d'accès Internet sortant du connecteur requises

Du fait d'un changement dans Cloud Backup, vous devez modifier les terminaux de connecteur suivants pour assurer la réussite des opérations de sauvegarde dans le cloud :

[cols="50,50"]
|===
| Ancien terminal | Nouveau terminal 


| \https://cloudmanager.cloud.netapp.com | \https://api.bluexp.netapp.com 


| \https://*.cloudmanager.cloud.netapp.com | \https://*.api.bluexp.netapp.com 
|===
Consultez la liste complète des terminaux de votre https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^], ou https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] de cloud hybride.



=== Prise en charge de la sélection de la classe de stockage d'archivage Google dans l'interface utilisateur

Les fichiers de sauvegarde sont initialement créés dans la classe de stockage Google Standard. Vous pouvez désormais utiliser l'interface utilisateur de Cloud Backup pour transférer les anciennes sauvegardes vers le stockage Google Archive après un certain nombre de jours afin d'optimiser les coûts.

Cette fonctionnalité est actuellement prise en charge par les clusters ONTAP sur site avec ONTAP 9.12.1 (ou version ultérieure). Elle n'est pas actuellement disponible pour les systèmes Cloud Volumes ONTAP.



=== Prise en charge des volumes FlexGroup

Cloud Backup prend désormais en charge la sauvegarde et la restauration des volumes FlexGroup. Avec ONTAP 9.12.1 ou version supérieure, vous pouvez sauvegarder des volumes FlexGroup sur un stockage de cloud public et privé. Si vous disposez d'environnements de travail intégrant des FlexVol et des volumes FlexGroup, vous pouvez sauvegarder tous les volumes FlexGroup sur ces systèmes une fois la mise à jour du logiciel ONTAP effectuée.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["Consultez la liste complète des types de volumes pris en charge"].



=== Possibilité de restaurer les données à partir de sauvegardes vers un agrégat spécifique sur les systèmes Cloud Volumes ONTAP

Dans les versions précédentes, vous pouviez sélectionner l'agrégat uniquement lors de la restauration des données sur des systèmes ONTAP sur site. Cette fonctionnalité fonctionne désormais lors de la restauration des données sur des systèmes Cloud Volumes ONTAP.



== 2 novembre 2022



=== Possibilité d'exporter d'anciennes copies Snapshot dans vos fichiers de sauvegarde de base

Si des copies Snapshot locales des volumes de votre environnement de travail correspondent aux étiquettes de votre planning de sauvegarde (par exemple, quotidienne, hebdomadaire, etc.), vous pouvez exporter ces snapshots historiques vers le stockage objet sous forme de fichiers de sauvegarde. Cela vous permet d'initialiser vos sauvegardes dans le cloud en déplaçant d'anciennes copies Snapshot vers la copie de sauvegarde de base.

Cette option est disponible lors de l'activation de Cloud Backup pour vos environnements de travail. Vous pouvez également modifier ce paramètre ultérieurement dans https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Page Paramètres avancés"].



=== Cloud Backup peut désormais être utilisé pour l'archivage des volumes dont vous n'avez plus besoin sur le système source

Vous pouvez maintenant supprimer la relation de sauvegarde d'un volume. Vous disposez ainsi d'un mécanisme d'archivage pour arrêter la création de nouveaux fichiers de sauvegarde et supprimer le volume source, mais conserver tous les fichiers de sauvegarde existants. Cela vous permet de restaurer ultérieurement le volume à partir du fichier de sauvegarde, si nécessaire, tout en libérant de l'espace du système de stockage source. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["Découvrez comment"].



=== Le service de support a été ajouté pour recevoir les alertes Cloud Backup par e-mail et dans le centre de notification

Cloud Backup a été intégré au service BlueXP notification. Vous pouvez afficher les notifications Cloud Backup en cliquant sur la cloche de notification dans la barre de menus BlueXP. Vous pouvez également configurer BlueXP pour envoyer des notifications par e-mail en tant qu'alertes afin de vous informer de l'activité système importante, même lorsque vous n'êtes pas connecté au système. Cet e-mail peut être envoyé aux destinataires qui doivent connaître les activités de sauvegarde et de restauration. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["Découvrez comment"].



=== La nouvelle page Paramètres avancés vous permet de modifier les paramètres de sauvegarde au niveau du cluster

Cette nouvelle page vous permet de modifier de nombreux paramètres de sauvegarde au niveau du cluster que vous avez définis lors de l'activation de Cloud Backup pour chaque système ONTAP. Vous pouvez également modifier certains paramètres appliqués comme paramètres de sauvegarde par défaut. L'ensemble des paramètres de sauvegarde que vous pouvez modifier comprend :

* Les clés de stockage qui donnent à votre système ONTAP l'autorisation d'accéder au stockage objet
* Bande passante réseau allouée pour télécharger les sauvegardes dans le stockage objet
* Paramètre de sauvegarde automatique (et règle) pour les volumes futurs
* Classe de stockage d'archivage (AWS uniquement)
* Indique si des copies Snapshot historiques sont incluses dans les fichiers de sauvegarde de base initiaux
* Si les snapshots « annuels » sont supprimés du système source
* L'IPspace ONTAP connecté au stockage objet (en cas de sélection incorrecte lors de l'activation)


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["En savoir plus sur la gestion des paramètres de sauvegarde au niveau du cluster"].



=== Vous pouvez désormais restaurer des fichiers de sauvegarde à l'aide de la fonction de recherche et de restauration lors de l'utilisation d'un connecteur sur site

Dans la version précédente, la prise en charge a été ajoutée pour créer des fichiers de sauvegarde dans le cloud public lorsque le connecteur est déployé sur site. Dans cette version, le service de support a continué d'être utilisé pour restaurer des sauvegardes à partir d'Amazon S3 ou d'Azure Blob lorsque le connecteur est déployé sur site. La fonction de recherche et restauration prend également en charge la restauration des sauvegardes depuis les systèmes StorageGRID vers les systèmes ONTAP sur site.

À l'heure actuelle, le connecteur doit être déployé dans Google Cloud Platform lorsque vous utilisez les fonctions de recherche et de restauration pour restaurer des sauvegardes à partir de Google Cloud Storage.



=== La page surveillance des travaux a été mise à jour

Les mises à jour suivantes ont été effectuées sur le https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Surveillance des travaux"]:

* Une colonne pour « charge de travail » est disponible. Vous pouvez donc filtrer la page pour afficher les travaux des services de sauvegarde suivants : volumes, applications et machines virtuelles.
* Vous pouvez ajouter de nouvelles colonnes pour « Nom d'utilisateur » et « Type de travail » si vous souhaitez afficher ces détails pour une tâche de sauvegarde spécifique.
* La page Détails du travail affiche tous les sous-travaux en cours d'exécution pour terminer le travail principal.
* La page est automatiquement actualisée toutes les 15 minutes pour que vous puissiez toujours voir les résultats de l'état des travaux les plus récents. Et vous pouvez cliquer sur le bouton *Actualiser* pour mettre la page à jour immédiatement.




=== Améliorations de la sauvegarde entre plusieurs comptes AWS

Si vous souhaitez utiliser un autre compte AWS pour vos sauvegardes Cloud Volumes ONTAP que celui que vous utilisez pour les volumes source, vous devez ajouter les identifiants de compte AWS de destination dans BlueXP. Vous devez également ajouter les autorisations « s3:PutBuckePolicy » et « s3:PutketOwnershipControls » au rôle qui fournit BlueXP avec les autorisations. Auparavant, il fallait configurer de nombreux paramètres sur la console AWS. Plus besoin de le faire.



== 28 septembre 2022



=== Améliorations de Cloud Backup pour les applications

* Prise en charge de Google Cloud Platform (GCP) et de StorageGRID pour sauvegarder des copies Snapshot cohérentes au niveau des applications
* Création de règles personnalisées
* Prend en charge le stockage d'archivage
* Sauvegarde des applications SAP HANA
* Sauvegardez les applications Oracle et SQL qui se trouvent sur l'environnement VMware
* Sauvegarder les applications à partir d'un système de stockage secondaire sur site
* Désactiver les sauvegardes
* Annuler l'enregistrement du serveur SnapCenter




=== Améliorations de Cloud Backup pour les machines virtuelles

* Prend en charge StorageGRID pour sauvegarder un ou plusieurs datastores
* Création de règles personnalisées




== 19 septembre 2022



=== Vous pouvez configurer le verrouillage des données et les attaques par ransomware pour les fichiers de sauvegarde dans les systèmes StorageGRID

La dernière version a introduit _DataLock et ransomware protection_ pour les sauvegardes stockées dans des compartiments Amazon S3. Cette version étend la prise en charge des fichiers de sauvegarde stockés dans les systèmes StorageGRID. Si votre cluster utilise ONTAP 9.11.1 ou version ultérieure et que votre système StorageGRID exécute la version 11.6.0.3 ou ultérieure, cette nouvelle option de règles de sauvegarde est disponible. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Découvrez comment protéger vos sauvegardes avec DataLock et des attaques par ransomware"^].

Notez que vous devrez exécuter un connecteur avec la version 3.9.22 ou une version ultérieure du logiciel. Le connecteur doit être installé dans vos locaux et peut être installé sur un site avec ou sans accès à Internet.



=== La restauration au niveau des dossiers est désormais disponible à partir de vos fichiers de sauvegarde

Vous pouvez maintenant restaurer un dossier à partir d'un fichier de sauvegarde si vous avez besoin d'accéder à tous les fichiers de ce dossier (répertoire ou partage). La restauration d'un dossier est bien plus efficace que la restauration d'un volume entier. Cette fonctionnalité est disponible pour les opérations de restauration à l'aide de la méthode Parcourir et restaurer et de la méthode Rechercher et restaurer lors de l'utilisation de ONTAP 9.11.1 ou version ultérieure. Pour le moment, vous ne pouvez sélectionner et restaurer qu'un seul dossier, et seuls les fichiers de ce dossier sont restaurés - aucun sous-dossier, ni fichier dans des sous-dossiers, n'est restauré.



=== La restauration au niveau des fichiers est désormais disponible à partir des sauvegardes qui ont été transférées vers le stockage d'archivage

Auparavant, il était possible de restaurer uniquement les volumes à partir des fichiers de sauvegarde déplacés vers un stockage d'archivage (AWS et Azure uniquement). Vous pouvez désormais restaurer des fichiers individuels à partir de ces fichiers de sauvegarde archivés. Cette fonctionnalité est disponible pour les opérations de restauration à l'aide de la méthode Parcourir et restaurer et de la méthode Rechercher et restaurer lors de l'utilisation de ONTAP 9.11.1 ou version ultérieure.



=== La restauration au niveau des fichiers offre désormais la possibilité d'écraser le fichier source d'origine

Par le passé, un fichier restauré sur le volume d'origine a toujours été restauré en tant que nouveau fichier avec le préfixe « Restore_<nom_fichier> ». Vous pouvez maintenant choisir d'écraser le fichier source d'origine lors de la restauration du fichier à l'emplacement d'origine du volume. Cette fonctionnalité est disponible pour les opérations de restauration à l'aide de la méthode Browse & Restore et de la méthode Search & Restore.



=== Effectuez un glisser-déposer pour activer la sauvegarde dans le cloud sur les systèmes StorageGRID

Si le https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] Destination de vos sauvegardes existe en tant qu'environnement de travail sur la toile. Vous pouvez faire glisser votre environnement de travail ONTAP sur site vers la destination pour lancer l'assistant de configuration de Cloud Backup.
