---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore' 
summary: Découvrez les nouveautés de la sauvegarde et de la restauration BlueXP. 
---
= Nouveautés de la sauvegarde et de la restauration BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de la sauvegarde et de la restauration BlueXP.



== 1er août 2023

[IMPORTANT]
====
En raison d'une amélioration importante de la sécurité, votre connecteur nécessite désormais un accès Internet sortant vers deux terminaux supplémentaires afin de gérer les ressources de sauvegarde et de restauration dans votre environnement de cloud public. Si ces points finaux n'ont pas été ajoutés à la liste « autorisé » de votre pare-feu, une erreur s'affiche dans l'interface utilisateur à propos de « Service indisponible » ou de « Echec de la détermination de l'état du service » :

\https://api.cloud.netapp.com
\https://netapp-cloud-account.auth0.com/userinfo

====


=== La prise en charge a été ajoutée à la sauvegarde des volumes dans des compartiments sur les systèmes ONTAP configurés avec S3

Vous pouvez désormais utiliser un système ONTAP configuré pour simple Storage Service (S3) pour sauvegarder des volumes dans le stockage objet. Ceci est pris en charge à la fois pour les systèmes ONTAP sur site et les systèmes Cloud Volumes ONTAP. Cette configuration est prise en charge dans les déploiements cloud et sur des sites sans accès à Internet (déploiement en mode « privé »).

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["En savoir plus >>"].



=== Vous pouvez désormais inclure les snapshots existants d'un volume protégé dans vos fichiers de sauvegarde

Auparavant, vous aviez la possibilité d'inclure des copies Snapshot existantes à partir de volumes de lecture-écriture dans votre fichier de sauvegarde initial vers le stockage objet (au lieu de commencer avec la copie Snapshot la plus récente). Les copies Snapshot existantes de volumes en lecture seule (volumes de protection des données) n'ont pas été incluses dans le fichier de sauvegarde. Vous pouvez désormais choisir d'inclure d'anciennes copies Snapshot dans le fichier de sauvegarde des volumes « DP ».

L'assistant de sauvegarde affiche une invite à la fin des étapes de sauvegarde, dans laquelle vous pouvez sélectionner ces « instantanés existants ».



=== La sauvegarde et la restauration BlueXP ne prennent plus en charge la sauvegarde automatique des volumes ajoutés à l'avenir

Vous pouviez auparavant cocher une case dans l'assistant de sauvegarde pour appliquer la règle de sauvegarde sélectionnée à tous les futurs volumes ajoutés au cluster. Cette fonction a été supprimée en fonction des commentaires de l'utilisateur et du manque d'utilisation de cette fonction. Vous devez activer manuellement les sauvegardes de tout nouveau volume ajouté au cluster.



=== La page surveillance des travaux a été mise à jour avec de nouvelles fonctionnalités

La page surveillance des tâches fournit maintenant plus d'informations sur la stratégie de sauvegarde 3-2-1. Le service fournit également des notifications d'alerte supplémentaires relatives à la stratégie de sauvegarde.

Le filtre Type « cycle de vie de sauvegarde » a été renommé « conservation ». Utilisez ce filtre pour suivre le cycle de vie des sauvegardes et identifier l'expiration de toutes les copies de sauvegarde. Le type de tâche « conservation » capture toutes les tâches de suppression de Snapshot initiées sur un volume protégé par la sauvegarde et la restauration BlueXP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["En savoir plus sur le moniteur de tâches mis à jour"].



== 6 juillet 2023



=== La sauvegarde et la restauration BlueXP permettent désormais de planifier et de créer des copies Snapshot et des volumes répliqués

La sauvegarde et la restauration BlueXP vous permettent désormais d'implémenter une stratégie 3-2-1 où vous pouvez disposer de 3 copies de vos données source sur 2 systèmes de stockage différents avec une copie dans le cloud. Après l'activation, vous aurez :

* Copie Snapshot du volume sur le système source
* Volume répliqué sur un autre système de stockage
* Sauvegarde du volume dans le stockage objet


https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html["En savoir plus sur les nouvelles fonctionnalités complètes de sauvegarde et de restauration"].

Cette nouvelle fonctionnalité s'applique également aux opérations de restauration. Vous pouvez effectuer des opérations de restauration à partir d'une copie Snapshot, d'un volume répliqué ou d'un fichier de sauvegarde dans le cloud. Cela vous donne la flexibilité de choisir le fichier de sauvegarde qui répond à vos besoins en restauration, notamment le coût et la vitesse de restauration.

Notez que cette nouvelle fonctionnalité et interface utilisateur ne sont prises en charge que pour les clusters exécutant ONTAP 9.8 ou version ultérieure. Si votre cluster dispose d'une version antérieure du logiciel, vous pouvez continuer à utiliser la version précédente de BlueXP Backup and Recovery. Toutefois, nous vous recommandons de passer à une version prise en charge de ONTAP afin d'obtenir les dernières fonctionnalités. Pour continuer à utiliser l'ancienne version du logiciel, procédez comme suit :

. Dans l'onglet *volumes*, sélectionnez *Paramètres de sauvegarde*.
. Sur la page _Backup Settings_, cliquez sur le bouton radio *Afficher la version précédente de sauvegarde et de restauration BlueXP*.
+
Vous pouvez ensuite gérer vos anciens clusters à l'aide de la version précédente du logiciel.





=== Possibilité de créer votre conteneur de stockage pour la sauvegarde vers un stockage objet

Lorsque vous créez des fichiers de sauvegarde dans un stockage objet, par défaut, le service de sauvegarde et de restauration crée les compartiments dans le stockage objet pour vous. Vous pouvez créer les compartiments vous-même si vous souhaitez utiliser un certain nom ou attribuer des propriétés spéciales. Si vous souhaitez créer votre propre compartiment, vous devez le créer avant de lancer l'assistant d'activation. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["Découvrez comment créer vos compartiments de stockage objet"].

Cette fonctionnalité n'est actuellement pas prise en charge lors de la création de fichiers de sauvegarde sur des systèmes StorageGRID.



== 04 juillet 2023



=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (cloud natif)

* Systèmes SAP HANA
+
** Prend en charge la connexion et la restauration des copies de volumes non-données et de volumes globaux non-données disposant d'une protection secondaire Azure NetApp Files


* Les bases de données Oracle
+
** Prend en charge la restauration des bases de données Oracle sur Azure NetApp Files vers un autre emplacement
** Prise en charge du catalogage Oracle Recovery Manager (RMAN) des sauvegardes de bases de données Oracle sur Azure NetApp Files
** Permet de placer l'hôte de base de données en mode de maintenance pour effectuer des tâches de maintenance






=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (hybride)

* Prend en charge la restauration dans un autre emplacement
* Vous permet de monter des sauvegardes de bases de données Oracle
* Prise en charge du déplacement des sauvegardes de GCP vers le Tier d'archivage




=== Améliorations de la sauvegarde et de la restauration BlueXP pour les machines virtuelles (hybride)

* Prend en charge la protection des types de datastores NFS et VMFS
* Vous permet d'annuler l'enregistrement du plug-in SnapCenter pour l'hôte VMware vSphere
* Prend en charge l'actualisation et la découverte des derniers datastores et sauvegardes




== 5 juin 2023



=== Les volumes FlexGroup peuvent être sauvegardés et protégés à l'aide de DataLock et de la protection contre les ransomware

Les règles de sauvegarde pour les volumes FlexGroup peuvent désormais utiliser DataLock et la protection contre les ransomware lorsque le cluster exécute ONTAP 9.13.1 ou une version ultérieure.



=== Nouvelles fonctionnalités de reporting

Un onglet Reports permet désormais de générer un rapport Backup Inventory, qui inclut toutes les sauvegardes d'un compte, d'un environnement de travail ou d'un inventaire SVM spécifique. Vous pouvez également créer un rapport sur l'activité des tâches de protection des données, qui fournit des informations sur les opérations Snapshot, de sauvegarde, de clonage et de restauration, afin de vous aider à contrôler les contrats de niveau de service. Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["Reporting sur la couverture de la protection des données"].



=== Améliorations du moniteur de tâches

Vous pouvez maintenant passer en revue _backup Lifecycle_ en tant que Type de tâche sur la page Job Monitor, ce qui vous permet de suivre l'intégralité du cycle de vie de la sauvegarde. Vous pouvez également afficher les détails de toutes les opérations sur la chronologie BlueXP. Reportez-vous à la section https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Surveiller l'état des tâches de sauvegarde et de restauration"].



=== Alerte de notification supplémentaire pour les étiquettes de stratégie non concordants

Une nouvelle alerte de sauvegarde a été ajoutée : « les fichiers de sauvegarde n'ont pas été créés, car les étiquettes des règles Snapshot ne correspondent pas ». Si le _label_ défini dans une règle de sauvegarde n'a pas de _label_ correspondant dans la stratégie Snapshot, aucun fichier de sauvegarde n'est créé. Vous devez utiliser System Manager ou l'interface de ligne de commandes de ONTAP pour ajouter l'étiquette manquante à la règle de copie Snapshot du volume.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["Examinez toutes les alertes que les solutions de sauvegarde et de restauration BlueXP peuvent envoyer"].



=== Sauvegarde automatique des fichiers de sauvegarde et de restauration BlueXP stratégiques dans les sites invisibles

Lorsque vous utilisez la sauvegarde et la restauration BlueXP dans un site sans accès à Internet, connu sous le nom de déploiement en « mode privé », les informations de sauvegarde et de restauration BlueXP sont stockées uniquement sur le système de connecteurs local. Cette nouvelle fonctionnalité sauvegarde automatiquement les données stratégiques de sauvegarde et de restauration BlueXP dans un compartiment du système StorageGRID connecté. Vous pouvez ainsi restaurer ces données sur un nouveau connecteur, si nécessaire. https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["En savoir plus >>"]



== 8 mai 2023



=== Les opérations de restauration au niveau des dossiers sont désormais prises en charge à partir du stockage d'archives et des sauvegardes verrouillées

Si un fichier de sauvegarde a été configuré avec la protection DataLock & ransomware, ou si le fichier de sauvegarde réside dans un stockage d'archivage, les opérations de restauration au niveau des dossiers sont prises en charge si le cluster exécute ONTAP 9.13.1 ou une version ultérieure.



=== Les clés gérées par le client entre régions et projets sont prises en charge lors de la sauvegarde de volumes dans Google Cloud

Vous pouvez désormais choisir un compartiment qui se trouve dans un projet différent de celui des clés de chiffrement gérées par le client (CMEK). https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["En savoir plus sur la configuration de vos propres clés de chiffrement gérées par le client"].



=== Les régions AWS Chine sont désormais prises en charge pour les fichiers de sauvegarde

Les régions AWS China Beijing (cn-North-1) et Ningxia (cn-Northwest-1) sont désormais prises en charge en tant que destinations pour vos fichiers de sauvegarde si le cluster exécute ONTAP 9.12.1 ou une version ultérieure.

Notez que les règles IAM attribuées à BlueXP Connector doivent modifier le nom de ressource AWS « arn » sous toutes les sections _Resource_ de « aws » à « aws-cn », par exemple « arn:aws-cn:s3:::netapp-backup-* ». Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Sauvegarde des données Cloud Volumes ONTAP dans Amazon S3"] et https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["Sauvegarde des données ONTAP sur site dans Amazon S3"] pour plus d'informations.



=== Améliorations apportées au moniteur de tâches

Les tâches lancées par le système, telles que les opérations de sauvegarde en cours, sont désormais disponibles dans l'onglet *surveillance des tâches* pour les systèmes ONTAP sur site exécutant ONTAP 9.13.1 ou version ultérieure. Les versions précédentes de ONTAP affichent uniquement les travaux initiés par l'utilisateur.



== 14 avril 2023



=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (cloud natif)

* Les bases de données SAP HANA
+
** Prend en charge l'actualisation du système basée sur des scripts
** Prend en charge la restauration de fichiers uniques Snapshot si la sauvegarde Azure NetApp Files est configurée
** Prend en charge la mise à niveau du plug-in


* Les bases de données Oracle
+
** Améliorations apportées au déploiement des plug-ins en simplifiant la configuration utilisateur sudo non-root
** Prend en charge la mise à niveau du plug-in
** Prend en charge la détection automatique et la protection pilotée par des règles des bases de données Oracle sur Azure NetApp Files
** Prend en charge la restauration de la base de données Oracle à l'emplacement d'origine avec récupération granulaire






=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (hybride)

* La sauvegarde et la restauration BlueXP pour les applications (hybrides) sont pilotées par le plan de contrôle SaaS
* API REST hybrides modifiées pour l'alignement avec les API cloud natives - effectué.
* Prend en charge la notification par e-mail




== 4 avril 2023



=== Possibilité de sauvegarder des données dans le cloud à partir des systèmes Cloud Volumes ONTAP en mode « restreint »

Vous pouvez désormais sauvegarder les données à partir de systèmes Cloud Volumes ONTAP installés dans les régions commerciales AWS, Azure et GCP en « mode restreint ». Pour cela, vous devez d'abord installer le connecteur dans la région commerciale « restreinte ». https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["En savoir plus sur les modes de déploiement BlueXP"^]. Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Sauvegarde des données Cloud Volumes ONTAP dans Amazon S3"] et https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Sauvegarde des données Cloud Volumes ONTAP dans Azure Blob"].



=== Possibilité de sauvegarder vos volumes ONTAP sur site vers ONTAP S3 à l'aide de l'API

Les nouvelles fonctionnalités des API vous permettent de sauvegarder vos copies Snapshot de volume vers ONTAP S3 à l'aide de la sauvegarde et de la restauration BlueXP. Cette fonctionnalité est disponible uniquement pour les systèmes ONTAP sur site à l'heure actuelle. Pour obtenir des instructions détaillées, consultez le blog https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["Intégration avec ONTAP S3 en tant que destination"^].



=== Possibilité de modifier l'aspect redondance de zone de votre compte de stockage Azure de LRS à ZRS

Lors de la création de sauvegardes à partir de systèmes Cloud Volumes ONTAP vers du stockage Azure, par défaut, la sauvegarde et la restauration BlueXP provisionne le conteneur Blob avec une redondance locale (LRS) pour l'optimisation des coûts. Vous pouvez définir ce paramètre sur redondance de zone (ZRS) si vous souhaitez que vos données soient répliquées entre différentes zones. Consultez les instructions Microsoft pour https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["modification de la façon dont votre compte de stockage est répliqué"^].



=== Améliorations apportées au moniteur de tâches

* Les opérations de sauvegarde et de restauration initiées par l'utilisateur à partir de l'interface utilisateur et de l'API de sauvegarde et de restauration BlueXP, ainsi que les tâches initiées par le système, telles que les opérations de sauvegarde en continu, sont désormais disponibles dans l'onglet *surveillance des tâches* pour les systèmes Cloud Volumes ONTAP exécutant ONTAP 9.13.0 ou version ultérieure. Les versions précédentes de ONTAP affichent uniquement les travaux initiés par l'utilisateur.
* En plus de pouvoir télécharger un fichier CSV pour créer des rapports sur tous les travaux, vous pouvez désormais télécharger un fichier JSON pour un seul travail et voir ses détails. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["En savoir plus >>"].
* Deux nouvelles alertes de tâche de sauvegarde ont été ajoutées : « échec de tâche planifiée » et « la tâche de restauration est terminée mais avec des avertissements ». https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["Examinez toutes les alertes que les solutions de sauvegarde et de restauration BlueXP peuvent envoyer"].




== 9 mars 2023



=== Les opérations de restauration au niveau des dossiers incluent désormais tous les sous-dossiers et fichiers

Dans le passé, lorsque vous avez restauré un dossier, seuls les fichiers de ce dossier ont été restaurés : aucun sous-dossier, ni fichier dans des sous-dossiers, n'a été restauré. Maintenant, si vous utilisez ONTAP 9.13.0 ou une version ultérieure, tous les sous-dossiers et fichiers du dossier sélectionné sont restaurés. Cela permet d'économiser beaucoup de temps et d'argent dans les cas où vous avez plusieurs dossiers imbriqués dans un dossier de premier niveau.



=== Possibilité de sauvegarder des données à partir de systèmes Cloud Volumes ONTAP dans des sites invisibles

Vous pouvez désormais sauvegarder les données à partir de systèmes Cloud Volumes ONTAP installés dans les régions commerciales AWS et Azure vers Amazon S3 ou Azure Blob. Pour ce faire, vous devez installer le connecteur sur un hôte Linux de la région commerciale et déployer le système Cloud Volumes ONTAP là aussi. Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Sauvegarde des données Cloud Volumes ONTAP dans Amazon S3"] et https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Sauvegarde des données Cloud Volumes ONTAP dans Azure Blob"].



=== Plusieurs améliorations apportées au moniteur de tâches

* La page surveillance des tâches a ajouté un filtrage avancé pour vous permettre de rechercher des tâches de sauvegarde et de restauration par temps, workload (volumes, applications, machines virtuelles ou Kubernetes), Type de tâche, état, environnement de travail et machine virtuelle de stockage. Vous pouvez également entrer du texte libre pour rechercher n'importe quelle ressource, par exemple, "application_3".  https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["Voir comment utiliser les filtres avancés"].
* Les opérations de sauvegarde et de restauration initiées par l'utilisateur à partir de l'interface utilisateur et de l'API de sauvegarde et de restauration BlueXP, ainsi que les tâches initiées par le système, telles que les opérations de sauvegarde en continu, sont désormais disponibles dans l'onglet *surveillance des tâches* pour les systèmes Cloud Volumes ONTAP exécutant ONTAP 9.13.0 ou version ultérieure. Les versions antérieures des systèmes Cloud Volumes ONTAP et les systèmes ONTAP sur site n'affichent actuellement que les tâches initiées par l'utilisateur.




== 6 février 2023



=== La possibilité de déplacer d'anciens fichiers de sauvegarde vers le stockage d'archivage Azure à partir des systèmes StorageGRID

Vous pouvez désormais transférer les anciens fichiers de sauvegarde des systèmes StorageGRID vers le stockage d'archivage dans Azure. Cela vous permet de libérer de l'espace sur vos systèmes StorageGRID et de réaliser des économies en utilisant une solution de stockage bon marché pour les anciens fichiers de sauvegarde.

Cette fonctionnalité est disponible si votre cluster sur site utilise ONTAP 9.12.1 ou version ultérieure et que votre système StorageGRID utilise 11.4 ou version ultérieure. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["En savoir plus"^].



=== Il est possible de configurer le verrouillage des données et la protection contre les attaques par ransomware pour les fichiers de sauvegarde dans Azure Blob

DataLock et ransomware protection sont désormais pris en charge pour les fichiers de sauvegarde stockés dans Azure Blob. Si votre système Cloud Volumes ONTAP ou ONTAP sur site exécute ONTAP 9.12.1 ou une version ultérieure, vous pouvez maintenant verrouiller vos fichiers de sauvegarde et les analyser pour détecter un éventuel ransomware. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Découvrez comment protéger vos sauvegardes avec DataLock et protection contre les attaques par ransomware"^].



=== Amélioration de la sauvegarde et de la restauration d'un volume FlexGroup

* Vous pouvez désormais choisir plusieurs agrégats lors de la restauration d'un volume FlexGroup. Dans la dernière version, vous ne pouvez sélectionner qu'un seul agrégat.
* La restauration de volume FlexGroup est désormais prise en charge sur les systèmes Cloud Volumes ONTAP. Dans la dernière version, vous pouviez uniquement restaurer vos données vers des systèmes ONTAP sur site.




=== Les systèmes Cloud Volumes ONTAP peuvent transférer d'anciennes sauvegardes vers le stockage d'archivage Google

Les fichiers de sauvegarde sont initialement créés dans la classe de stockage Google Standard. Vous pouvez désormais utiliser la sauvegarde et la restauration BlueXP pour hiérarchiser les sauvegardes plus anciennes sur le stockage Google Archive afin de mieux optimiser les coûts. La dernière version ne prend en charge que cette fonctionnalité avec des clusters ONTAP sur site. Désormais, les systèmes Cloud Volumes ONTAP déployés dans Google Cloud sont pris en charge.



=== Les opérations de restauration de volume permettent désormais de sélectionner la SVM où vous souhaitez restaurer les données de volume

Désormais, vous restaurez des données de volume sur d'autres machines virtuelles de stockage dans vos clusters ONTAP. Auparavant, il n'était pas possible de choisir la machine virtuelle de stockage.



=== Prise en charge améliorée des volumes dans les configurations MetroCluster

Avec ONTAP 9.12.1 GA ou supérieur, la sauvegarde est désormais prise en charge lorsqu'elle est connectée au système primaire dans une configuration MetroCluster. L'intégralité de la configuration de sauvegarde est transférée vers le système secondaire pour que les sauvegardes vers le cloud puissent se poursuivre automatiquement après le basculement.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["Voir limites de sauvegarde pour plus d'informations"].



== 9 janvier 2023



=== La possibilité de déplacer d'anciens fichiers de sauvegarde vers le stockage d'archivage AWS S3 à partir des systèmes StorageGRID

Vous pouvez désormais transférer d'anciens fichiers de sauvegarde des systèmes StorageGRID vers le stockage d'archivage dans AWS S3. Cela vous permet de libérer de l'espace sur vos systèmes StorageGRID et de réaliser des économies en utilisant une solution de stockage bon marché pour les anciens fichiers de sauvegarde. Vous pouvez choisir de transférer les sauvegardes vers un stockage AWS S3 Glacier ou S3 Glacier Deep Archive.

Cette fonctionnalité est disponible si votre cluster sur site utilise ONTAP 9.12.1 ou version ultérieure et que votre système StorageGRID utilise 11.3 ou version ultérieure. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["En savoir plus"].



=== Possibilité de sélectionner vos propres clés gérées par le client pour le chiffrement des données sur Google Cloud

Lorsque vous sauvegardez les données de vos systèmes ONTAP dans Google Cloud Storage, vous pouvez maintenant sélectionner vos propres clés gérées par le client pour le chiffrement des données dans l'assistant d'activation au lieu d'utiliser les clés de chiffrement gérées par Google par défaut. Il vous suffit de configurer d'abord vos clés de chiffrement gérées par le client dans Google, puis de saisir les informations lorsque vous activez la sauvegarde et la restauration BlueXP.



=== Le rôle d'administrateur du stockage n'est plus nécessaire pour créer des sauvegardes dans Google Cloud Storage

Dans les versions précédentes, le rôle d'administrateur du stockage était requis pour le compte de service permettant à la sauvegarde et à la restauration BlueXP d'accéder aux compartiments de stockage Google Cloud. Vous pouvez désormais créer un rôle personnalisé avec un ensemble réduit d'autorisations à attribuer au compte de service. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["Découvrez comment préparer votre Google Cloud Storage pour les sauvegardes"].



=== L'assistance a été ajoutée pour restaurer des données à l'aide de la fonction de recherche et de restauration sur des sites sans accès à Internet

Si vous sauvegardez des données à partir d'un cluster ONTAP sur site vers StorageGRID sur un site sans accès Internet, également connu sous le nom de site sombre ou hors ligne, vous pouvez maintenant utiliser l'option de recherche et de restauration pour restaurer les données si nécessaire. Cette fonctionnalité requiert le déploiement du connecteur BlueXP (version 3.9.25 ou ultérieure) sur le site hors ligne.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["Voir comment restaurer les données ONTAP à l'aide de la fonction Rechercher et AMP ; Restaurer"].
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Découvrez comment installer le connecteur dans votre site hors ligne"].



=== Possibilité de télécharger la page des résultats de la surveillance des travaux sous forme de rapport .csv

Après avoir filtré la page surveillance des travaux pour afficher les travaux et les actions qui vous intéressent, vous pouvez maintenant générer et télécharger un fichier .csv de ces données. Vous pouvez ensuite analyser les informations ou envoyer le rapport à d'autres personnes de votre organisation. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["Découvrez comment générer un rapport de surveillance des travaux"].



== 19 décembre 2022



=== Améliorations de Cloud Backup pour les applications

* Les bases de données SAP HANA
+
** Prise en charge de la sauvegarde et de la restauration basées sur des règles des bases de données SAP HANA résidant sur Azure NetApp Files
** Prend en charge les règles personnalisées


* Les bases de données Oracle
+
** Ajoutez des hôtes et déployez automatiquement le plug-in
** Prend en charge les règles personnalisées
** Prise en charge de la sauvegarde, de la restauration et du clonage des bases de données Oracle résidant sur Cloud Volumes ONTAP basés sur des règles
** Prend en charge la sauvegarde et la restauration basées sur des règles des bases de données Oracle résidant sur Amazon FSX pour NetApp ONTAP
** Prend en charge la restauration des bases de données Oracle à l'aide de la méthode de connexion et de copie
** Prend en charge Oracle 21c
** Prend en charge le clonage d'une base de données Oracle cloud native






=== Améliorations de Cloud Backup pour les machines virtuelles

* Ordinateurs virtuels
+
** Sauvegarder des machines virtuelles à partir d'un stockage secondaire sur site
** Prend en charge les règles personnalisées
** Prise en charge de Google Cloud Platform (GCP) pour sauvegarder un ou plusieurs datastores
** Prise en charge d'un stockage cloud à faible coût comme Glacier, Deep Glacier et Azure Archive






== 6 décembre 2022



=== Modifications du point de terminaison d'accès Internet sortant du connecteur requises

Du fait d'un changement dans Cloud Backup, vous devez modifier les terminaux de connecteur suivants pour assurer la réussite des opérations de sauvegarde dans le cloud :

[cols="50,50"]
|===
| Ancien terminal | Nouveau terminal 


| \https://cloudmanager.cloud.netapp.com | \https://api.bluexp.netapp.com 


| \https://*.cloudmanager.cloud.netapp.com | \https://*.api.bluexp.netapp.com 
|===
Consultez la liste complète des terminaux de votre https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^], ou https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] de cloud hybride.



=== Prise en charge de la sélection de la classe de stockage d'archivage Google dans l'interface utilisateur

Les fichiers de sauvegarde sont initialement créés dans la classe de stockage Google Standard. Vous pouvez désormais utiliser l'interface utilisateur de Cloud Backup pour transférer les anciennes sauvegardes vers le stockage Google Archive après un certain nombre de jours afin d'optimiser les coûts.

Cette fonctionnalité est actuellement prise en charge par les clusters ONTAP sur site avec ONTAP 9.12.1 (ou version ultérieure). Elle n'est pas actuellement disponible pour les systèmes Cloud Volumes ONTAP.



=== Prise en charge des volumes FlexGroup

Cloud Backup prend désormais en charge la sauvegarde et la restauration des volumes FlexGroup. Avec ONTAP 9.12.1 ou version supérieure, vous pouvez sauvegarder des volumes FlexGroup sur un stockage de cloud public et privé. Si vous disposez d'environnements de travail intégrant des FlexVol et des volumes FlexGroup, vous pouvez sauvegarder tous les volumes FlexGroup sur ces systèmes une fois la mise à jour du logiciel ONTAP effectuée.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["Consultez la liste complète des types de volumes pris en charge"].



=== Possibilité de restaurer les données à partir de sauvegardes vers un agrégat spécifique sur les systèmes Cloud Volumes ONTAP

Dans les versions précédentes, vous pouviez sélectionner l'agrégat uniquement lors de la restauration des données sur des systèmes ONTAP sur site. Cette fonctionnalité fonctionne désormais lors de la restauration des données sur des systèmes Cloud Volumes ONTAP.



== 2 novembre 2022



=== Possibilité d'exporter d'anciennes copies Snapshot dans vos fichiers de sauvegarde de base

Si des copies Snapshot locales des volumes de votre environnement de travail correspondent aux étiquettes de votre planning de sauvegarde (par exemple, quotidienne, hebdomadaire, etc.), vous pouvez exporter ces snapshots historiques vers le stockage objet sous forme de fichiers de sauvegarde. Cela vous permet d'initialiser vos sauvegardes dans le cloud en déplaçant d'anciennes copies Snapshot vers la copie de sauvegarde de base.

Cette option est disponible lors de l'activation de Cloud Backup pour vos environnements de travail. Vous pouvez également modifier ce paramètre ultérieurement dans https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Page Paramètres avancés"].



=== Cloud Backup peut désormais être utilisé pour l'archivage des volumes dont vous n'avez plus besoin sur le système source

Vous pouvez maintenant supprimer la relation de sauvegarde d'un volume. Vous disposez ainsi d'un mécanisme d'archivage pour arrêter la création de nouveaux fichiers de sauvegarde et supprimer le volume source, mais conserver tous les fichiers de sauvegarde existants. Cela vous permet de restaurer ultérieurement le volume à partir du fichier de sauvegarde, si nécessaire, tout en libérant de l'espace du système de stockage source. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["Découvrez comment"].



=== Le service de support a été ajouté pour recevoir les alertes Cloud Backup par e-mail et dans le centre de notification

Cloud Backup a été intégré au service BlueXP notification. Vous pouvez afficher les notifications Cloud Backup en cliquant sur la cloche de notification dans la barre de menus BlueXP. Vous pouvez également configurer BlueXP pour envoyer des notifications par e-mail en tant qu'alertes afin de vous informer de l'activité système importante, même lorsque vous n'êtes pas connecté au système. Cet e-mail peut être envoyé aux destinataires qui doivent connaître les activités de sauvegarde et de restauration. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["Découvrez comment"].



=== La nouvelle page Paramètres avancés vous permet de modifier les paramètres de sauvegarde au niveau du cluster

Cette nouvelle page vous permet de modifier de nombreux paramètres de sauvegarde au niveau du cluster que vous avez définis lors de l'activation de Cloud Backup pour chaque système ONTAP. Vous pouvez également modifier certains paramètres appliqués comme paramètres de sauvegarde par défaut. L'ensemble des paramètres de sauvegarde que vous pouvez modifier comprend :

* Les clés de stockage qui donnent à votre système ONTAP l'autorisation d'accéder au stockage objet
* Bande passante réseau allouée pour télécharger les sauvegardes dans le stockage objet
* Paramètre de sauvegarde automatique (et règle) pour les volumes futurs
* Classe de stockage d'archivage (AWS uniquement)
* Indique si des copies Snapshot historiques sont incluses dans les fichiers de sauvegarde de base initiaux
* Si les snapshots « annuels » sont supprimés du système source
* L'IPspace ONTAP connecté au stockage objet (en cas de sélection incorrecte lors de l'activation)


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["En savoir plus sur la gestion des paramètres de sauvegarde au niveau du cluster"].



=== Vous pouvez désormais restaurer des fichiers de sauvegarde à l'aide de la fonction de recherche et de restauration lors de l'utilisation d'un connecteur sur site

Dans la version précédente, la prise en charge a été ajoutée pour créer des fichiers de sauvegarde dans le cloud public lorsque le connecteur est déployé sur site. Dans cette version, le service de support a continué d'être utilisé pour restaurer des sauvegardes à partir d'Amazon S3 ou d'Azure Blob lorsque le connecteur est déployé sur site. La fonction de recherche et restauration prend également en charge la restauration des sauvegardes depuis les systèmes StorageGRID vers les systèmes ONTAP sur site.

À l'heure actuelle, le connecteur doit être déployé dans Google Cloud Platform lorsque vous utilisez les fonctions de recherche et de restauration pour restaurer des sauvegardes à partir de Google Cloud Storage.



=== La page surveillance des travaux a été mise à jour

Les mises à jour suivantes ont été effectuées sur le https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Surveillance des travaux"]:

* Une colonne pour « charge de travail » est disponible. Vous pouvez donc filtrer la page pour afficher les travaux des services de sauvegarde suivants : volumes, applications, machines virtuelles et Kubernetes.
* Vous pouvez ajouter de nouvelles colonnes pour « Nom d'utilisateur » et « Type de travail » si vous souhaitez afficher ces détails pour une tâche de sauvegarde spécifique.
* La page Détails du travail affiche tous les sous-travaux en cours d'exécution pour terminer le travail principal.
* La page est automatiquement actualisée toutes les 15 minutes pour que vous puissiez toujours voir les résultats de l'état des travaux les plus récents. Et vous pouvez cliquer sur le bouton *Actualiser* pour mettre la page à jour immédiatement.




=== Améliorations de la sauvegarde entre plusieurs comptes AWS

Si vous souhaitez utiliser un autre compte AWS pour vos sauvegardes Cloud Volumes ONTAP que celui que vous utilisez pour les volumes source, vous devez ajouter les identifiants de compte AWS de destination dans BlueXP. Vous devez également ajouter les autorisations « s3:PutBuckePolicy » et « s3:PutketOwnershipControls » au rôle qui fournit BlueXP avec les autorisations. Auparavant, il fallait configurer de nombreux paramètres sur la console AWS. Plus besoin de le faire.



== 28 septembre 2022



=== Améliorations de Cloud Backup pour les applications

* Prise en charge de Google Cloud Platform (GCP) et de StorageGRID pour sauvegarder des copies Snapshot cohérentes au niveau des applications
* Création de règles personnalisées
* Prend en charge le stockage d'archivage
* Sauvegarde des applications SAP HANA
* Sauvegardez les applications Oracle et SQL qui se trouvent sur l'environnement VMware
* Sauvegarder les applications à partir d'un système de stockage secondaire sur site
* Désactiver les sauvegardes
* Annuler l'enregistrement du serveur SnapCenter




=== Améliorations de Cloud Backup pour les machines virtuelles

* Prend en charge StorageGRID pour sauvegarder un ou plusieurs datastores
* Création de règles personnalisées




== 19 septembre 2022



=== Vous pouvez configurer le verrouillage des données et les attaques par ransomware pour les fichiers de sauvegarde dans les systèmes StorageGRID

La dernière version a introduit _DataLock et ransomware protection_ pour les sauvegardes stockées dans des compartiments Amazon S3. Cette version étend la prise en charge des fichiers de sauvegarde stockés dans les systèmes StorageGRID. Si votre cluster utilise ONTAP 9.11.1 ou version ultérieure et que votre système StorageGRID exécute la version 11.6.0.3 ou ultérieure, cette nouvelle option de règles de sauvegarde est disponible. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Découvrez comment protéger vos sauvegardes avec DataLock et des attaques par ransomware"^].

Notez que vous devrez exécuter un connecteur avec la version 3.9.22 ou une version ultérieure du logiciel. Le connecteur doit être installé dans vos locaux et peut être installé sur un site avec ou sans accès à Internet.



=== La restauration au niveau des dossiers est désormais disponible à partir de vos fichiers de sauvegarde

Vous pouvez maintenant restaurer un dossier à partir d'un fichier de sauvegarde si vous avez besoin d'accéder à tous les fichiers de ce dossier (répertoire ou partage). La restauration d'un dossier est bien plus efficace que la restauration d'un volume entier. Cette fonctionnalité est disponible pour les opérations de restauration à l'aide de la méthode Parcourir et restaurer et de la méthode Rechercher et restaurer lors de l'utilisation de ONTAP 9.11.1 ou version ultérieure. Pour le moment, vous ne pouvez sélectionner et restaurer qu'un seul dossier, et seuls les fichiers de ce dossier sont restaurés - aucun sous-dossier, ni fichier dans des sous-dossiers, n'est restauré.



=== La restauration au niveau des fichiers est désormais disponible à partir des sauvegardes qui ont été transférées vers le stockage d'archivage

Auparavant, il était possible de restaurer uniquement les volumes à partir des fichiers de sauvegarde déplacés vers un stockage d'archivage (AWS et Azure uniquement). Vous pouvez désormais restaurer des fichiers individuels à partir de ces fichiers de sauvegarde archivés. Cette fonctionnalité est disponible pour les opérations de restauration à l'aide de la méthode Parcourir et restaurer et de la méthode Rechercher et restaurer lors de l'utilisation de ONTAP 9.11.1 ou version ultérieure.



=== La restauration au niveau des fichiers offre désormais la possibilité d'écraser le fichier source d'origine

Par le passé, un fichier restauré sur le volume d'origine a toujours été restauré en tant que nouveau fichier avec le préfixe « Restore_<nom_fichier> ». Vous pouvez maintenant choisir d'écraser le fichier source d'origine lors de la restauration du fichier à l'emplacement d'origine du volume. Cette fonctionnalité est disponible pour les opérations de restauration à l'aide de la méthode Browse & Restore et de la méthode Search & Restore.



=== Effectuez un glisser-déposer pour activer la sauvegarde dans le cloud sur les systèmes StorageGRID

Si le https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] Destination de vos sauvegardes existe en tant qu'environnement de travail sur la toile. Vous pouvez faire glisser votre environnement de travail ONTAP sur site vers la destination pour lancer l'assistant de configuration de Cloud Backup.



== 18 août 2022



=== La protection des données des applications cloud natives a été prise en charge

Cloud Backup pour applications est un service SaaS qui fournit des fonctionnalités de protection des données pour les applications exécutées sur NetApp Cloud Storage. Cloud Backup pour les applications activées dans BlueXP offre des sauvegardes et des restaurations efficaces et cohérentes avec les applications, basées sur des règles, de bases de données Oracle résidant sur Amazon FSX pour NetApp ONTAP.
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protect-cloud-app-data-to-cloud.html["En savoir plus >>"^].



=== La fonction de recherche et de restauration est désormais prise en charge avec les fichiers de sauvegarde dans Azure Blob

La méthode de recherche et de restauration des volumes et des fichiers est désormais disponible pour les utilisateurs qui stockent leurs fichiers de sauvegarde dans le stockage Azure Blob. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#prerequisites-2["Découvrez comment restaurer vos volumes et fichiers à l'aide de Search  Restore"^].

Notez que des autorisations supplémentaires sont nécessaires dans le rôle connecteur pour utiliser cette fonctionnalité. Un connecteur déployé avec la version 3.9.21 du logiciel (août 2022) inclut ces autorisations. Vous devrez ajouter manuellement les autorisations si vous avez déployé le connecteur à l'aide d'une version antérieure. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-azure.html#verify-or-add-permissions-to-the-connector["Voir comment ajouter ces autorisations, si nécessaire"^].



=== Nous avons ajouté la possibilité de protéger vos fichiers de sauvegarde contre les suppressions et les attaques par ransomware

Cloud Backup dispose désormais de la prise en charge du verrouillage des objets pour les sauvegardes sécurisées par ransomware. Si votre cluster utilise ONTAP 9.11.1 ou version ultérieure et que votre destination de sauvegarde est Amazon S3, une nouvelle option de stratégie de sauvegarde appelée _DataLock et protection contre les attaques par ransomware_ est maintenant disponible. DataLock protège vos fichiers de sauvegarde contre la modification ou la suppression, et la protection contre les ransomwares analyse vos fichiers de sauvegarde pour rechercher des signes d'attaque par ransomware sur vos fichiers de sauvegarde. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Découvrez comment protéger vos sauvegardes avec DataLock et des attaques par ransomware"^].

Notez que des autorisations supplémentaires sont nécessaires dans le rôle connecteur pour utiliser cette fonctionnalité. Un connecteur déployé à l'aide du logiciel version 3.9.21 inclut ces autorisations. Vous devrez ajouter manuellement les autorisations si vous avez déployé le connecteur à l'aide d'une version antérieure. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html#set-up-s3-permissions["Découvrez comment ajouter ces autorisations si nécessaire"^].



=== Cloud Backup prend désormais en charge les règles créées à l'aide d'étiquettes SnapMirror personnalisées

Auparavant, Cloud Backup prenait uniquement en charge les étiquettes SnapMirror prédéfinies : toutes les heures, tous les jours, toutes les semaines, toutes les heures et tous les ans. Désormais, Cloud Backup peut détecter les règles SnapMirror qui comportent des étiquettes SnapMirror personnalisées que vous avez créées à l'aide de System Manager ou de l'interface de ligne de commande. Ces nouvelles étiquettes sont accessibles dans l'interface utilisateur de Cloud Backup, ce qui vous permet de sauvegarder des volumes avec le label SnapMirror de votre choix dans le cloud.



=== Autres améliorations de la politique de sauvegarde pour les systèmes ONTAP

Certaines pages de stratégie de sauvegarde ont été redessinées afin de faciliter l'affichage de toutes les règles de sauvegarde disponibles pour les volumes de chaque cluster ONTAP. Vous pouvez ainsi consulter les détails des règles disponibles de façon à appliquer les meilleures règles à vos volumes.



=== Effectuez un glisser-déposer pour activer Cloud Backup sur Azure Blob et Google Cloud Storage

Si le https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-azure-blob.html["Blob d'Azure"^] ou https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-gcp-storage.html["Google Cloud Storage"^] La destination de vos sauvegardes existe en tant qu'environnement de travail sur la toile. Vous pouvez faire glisser votre environnement de travail ONTAP ou Cloud Volumes ONTAP sur site (installé dans Azure ou GCP) vers la destination pour lancer l'assistant de configuration de la sauvegarde.

Cette fonctionnalité existe déjà pour les compartiments Amazon S3.



== 13 juillet 2022



=== La prise en charge a été ajoutée pour la sauvegarde des volumes SnapLock Enterprise

Vous pouvez désormais utiliser Cloud Backup pour sauvegarder des volumes SnapLock Enterprise dans des clouds publics et privés. Cette fonctionnalité requiert que votre système ONTAP exécute ONTAP 9.11.1 ou une version ultérieure. Cependant, les volumes de conformité SnapLock ne sont pas pris en charge actuellement.



=== Vous pouvez désormais créer des fichiers de sauvegarde dans le cloud public lorsque vous utilisez un connecteur sur site

Auparavant, vous deviez déployer le connecteur dans le même fournisseur de cloud que où vous créiez des fichiers de sauvegarde. Un connecteur déployé dans votre environnement sur site permet désormais de créer des fichiers de sauvegarde à partir de systèmes ONTAP sur site vers Amazon S3, Azure Blob et Google Cloud Storage. (Un connecteur sur site était toujours nécessaire pour créer des fichiers de sauvegarde sur les systèmes StorageGRID.)



=== Des fonctionnalités supplémentaires sont disponibles lors de la création de stratégies de sauvegarde pour les systèmes ONTAP

* Nous pouvons maintenant sauvegarder chaque année. La valeur de conservation par défaut est 1 pour les sauvegardes annuelles, mais vous pouvez modifier cette valeur si vous souhaitez accéder à de nombreux fichiers de sauvegarde des années précédentes.
* Vous pouvez nommer vos stratégies de sauvegarde de façon à ce que vous puissiez identifier vos stratégies avec un texte plus descriptif.

