= Améliorations de l'interface utilisateur
:allow-uri-read: 




=== Améliorations de l'interface utilisateur

Cette version améliore votre expérience en simplifiant l'interface :

* La suppression de la colonne Aggregate des tables volumes, ainsi que des colonnes Snapshot Policy, Backup Policy et Replication Policy de la table Volume du tableau de bord V2, entraîne une mise en page plus rationalisée.
* L'exclusion des environnements de travail non activés dans la liste déroulante rend l'interface moins encombrée, la navigation plus efficace et le chargement plus rapide.
* Lorsque le tri dans la colonne balises est désactivé, vous pouvez toujours afficher les balises, en vous assurant que les informations importantes restent facilement accessibles.
* Le retrait des étiquettes sur les icônes de protection contribue à un aspect plus propre et réduit le temps de chargement.
* Pendant le processus d'activation de l'environnement de travail, une boîte de dialogue affiche une icône de chargement pour fournir des informations jusqu'à ce que le processus de découverte soit terminé, ce qui améliore la transparence et la confiance dans les opérations du système.




=== Tableau de bord de volume amélioré (aperçu)

Le tableau de bord de volume se charge désormais en moins de 10 secondes, offrant ainsi une interface beaucoup plus rapide et efficace. Cette version préliminaire est disponible pour certains clients, leur offrant un aperçu de ces améliorations.



=== Prise en charge d'un magasin d'objets Wasabi tiers (aperçu)

La sauvegarde et la restauration BlueXP  étendent désormais sa prise en charge aux magasins d'objets tiers, en mettant l'accent sur Wasabi. Cette nouvelle fonctionnalité de préversion vous permet d'exploiter un magasin d'objets compatible S3 pour vos besoins de sauvegarde et de restauration.



==== Mise en route de Wasabi

Pour commencer à utiliser le stockage tiers en tant que magasin d'objets, vous devez activer un indicateur dans le connecteur BlueXP . Vous pouvez ensuite saisir les informations de connexion de votre magasin d'objets tiers et l'intégrer à vos workflows de sauvegarde et de restauration.

.Étapes
. SSH dans votre connecteur.
. Accédez au conteneur du serveur cbs de sauvegarde et de restauration BlueXP  :
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Ouvrez le `default.json` fichier dans le `config` dossier via VIM ou tout autre éditeur :
+
[listing]
----
vi default.json
----
. Modifier `allow-s3-compatible`: FALSE à `allow-s3-compatible`: TRUE.
. Enregistrez les modifications.
. Sortir du conteneur.
. Redémarrez le conteneur du serveur cbs de sauvegarde et de restauration BlueXP .


.Résultat
Une fois le conteneur à nouveau ALLUMÉ, ouvrez l'interface utilisateur de sauvegarde et de restauration de BlueXP . Lorsque vous lancez une sauvegarde ou modifiez une stratégie de sauvegarde, le nouveau fournisseur « compatible S3 » s'affiche, ainsi que les autres fournisseurs de sauvegarde : AWS, Microsoft Azure, Google Cloud, StorageGRID et ONTAP S3.



==== Limites du mode d'aperçu

Lorsque cette fonction est en aperçu, tenez compte des limitations suivantes :

* Le modèle BYOB (Bring Your Own Bucket) n'est pas pris en charge.
* L'activation de DataLock dans une stratégie n'est pas prise en charge.
* L'activation du mode archivage dans une règle n'est pas prise en charge.
* Seuls les environnements ONTAP sur site sont pris en charge.
* MetroCluster n'est pas pris en charge.
* Les options d'activation du chiffrement au niveau du compartiment ne sont pas prises en charge.


Au cours de cette présentation, nous vous encourageons à explorer cette nouvelle fonctionnalité et à nous faire part de vos commentaires sur l'intégration à des magasins d'objets tiers avant le déploiement complet des fonctionnalités.
