= Configuration réseau requise par Cloud Volumes ONTAP
:allow-uri-read: 


Avant d'activer les sauvegardes dans BlueXP Backup and Recovery, assurez-vous que les systèmes source et de destination respectent la version d'ONTAP et les exigences de mise en réseau.



==== Configuration réseau requise par Cloud Volumes ONTAP

Le groupe de sécurité de l’instance doit inclure les règles entrantes et sortantes requises : plus précisément, les règles pour ICMP et les ports 11104 et 11105. Ces règles sont incluses dans le groupe de sécurité prédéfini.



==== Exigences de mise en réseau ONTAP sur site

* Si le cluster se trouve sur votre site, vous devez disposer d'une connexion entre votre réseau d'entreprise et votre réseau virtuel du fournisseur cloud. Il s'agit généralement d'une connexion VPN.
* Les clusters ONTAP doivent répondre à des exigences supplémentaires en termes de sous-réseau, de port, de pare-feu et de cluster.
+
Comme vous pouvez répliquer sur Cloud Volumes ONTAP ou un système sur site, vérifiez les exigences de peering pour les systèmes ONTAP sur site. Reportez-vous à la section https://docs.netapp.com/us-en/ontap-sm-classic/peering/reference_prerequisites_for_cluster_peering.html["Afficher les conditions préalables au peering de cluster dans la documentation de ONTAP"^].


